### ISSUE TITLE
Research Tables: Hide already researched skills

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoSuggestions#10]
A way to Hide all known skill in the research table, similar to the Show All skills in the Skill Tree.

**Comment by MarjieAVolk** [comment]
We already have something on scrolls if we have learned them
![image](https://user-images.githubusercontent.com/23460210/40027423-d9a9de5a-578e-11e8-8e38-87c790db34b7.png)

maybe add this to a skillbook that we have crafted (something like you already crafted this) to save players accidently duplicating
![image](https://user-images.githubusercontent.com/23460210/40027428-de73419c-578e-11e8-96bf-81b8a5859395.png)

or possibly add something to research table ?
![image](https://user-images.githubusercontent.com/23460210/40027398-b33320a6-578e-11e8-817a-6ff89043b88c.png)

green tick for example saying that this table has crafted this object.

for skillbooks this is a must have to save confusion, otherwise you have to open a chest and hover over each book to see if you have already made it.

The table already checks storage for Amount of Ingredients cannot it also check storage for book?

**Comment by D3nnis3n** [comment]
Merged with #971
