### ISSUE TITLE
Tutorial doesn't continue | Tutorial resets

### ISSUE THREAD

**Issue by DamnDaniel72** [StrangeLoopGames/EcoSuggestions#1000]
When completing the food tutorial (Get started with eating a balanced diet) with every checkbox checked, this specific tutorial stucks. It won't continue automatically but just shows this screen as shown in the picture.

Adding to that, if you're halfway into the tutorial and you exit the game, the specific tutorial resets and you have to do this tutorial again.

![eco_bug](https://user-images.githubusercontent.com/63173500/78463794-64dac700-76e1-11ea-92c6-fe5f47b137b7.PNG)

**Comment by D3nnis3n** [comment]
That's an issue actually and it has been fixed.
