### ISSUE TITLE
Your dedicated vehicle / property list would be appreciated

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoSuggestions#1001]
I've seen this a number of times on the test server - players type in the name of their vehicle (Steam Truck) into chat just to open up the menu and try locating their own vehicle. It would be nice if perhaps there was a dedicated list of your vehicles / properties you could easily reference, maybe with a tab for global vehicle list. This would make it easier to locate these things. Moreover, if this also had the option to change permissions from that list, it would make it even more useful.

**Comment by D3nnis3n** [comment]
That can be done via the Real Estate Desk, actually. We prefer to have stuff in actual objects you need to craft, wherever possible.
