### ISSUE TITLE
[Server] A work around idea for rare unable to connect bugs

### ISSUE THREAD

**Issue by Elliander** [StrangeLoopGames/EcoSuggestions#1003]
Since I encountered an apparently rare bug that prevents a user from signing into a server, a bug which I hear is extremely difficult to reproduce, I got to thinking what could be done to work around such a bug when it occurs. 

Since other users can sign in, I was able to work around this bug:

https://github.com/StrangeLoopGames/EcoIssues/issues/15545

By logging in under a different account, then using admin commands to unclaim property, then using the dev tool to delete objects with uncollectable material from the main user, then used admin commands to regain some of the skill points my original character had, and then was able to resume under the new name. With, of course, the unfortunate side effect of having none of my wolf tier items. Nor did I get to keep any items I was carrying when I logged out last.

That got me thinking: What if, when this bug is detected, it gives the user the option to effectively login under a "different" name? Or rather, a duplicate character that the game presents to be the same name? It could automatically figure out what aspect of the character that is causing the bug, and copy everything else over to the new one.

So any land owned by the other character, any pending jobs or contracts, and currency held, etc. All copied over. Any skill points, likewise, copied over.

Something like: (and I'm just pulling this syntax out of thin air here)

If (System.InvalidOperationExceptionCall = true)
{
     String userCopy = userName;
     copy(userCopy, UserName);
}

So that if the invalid operation exception is called, it tries to recover from it instead of basically telling the user they can't play anymore. 

I get that deleting characters from a server would be a pain. Even deleting the user name from the game.eco > users directory doesn't remove everything. Still, any bug that effectively requires that the user have a second account to continue playing with is very bad, but any bug that is difficult to reproduce is likewise difficult to fix, so I figure a band aid that can work around the damage if and when it occurs would be great. 

All the bandaid has to do, at a minimum, is exactly the same as if the admin created a new account, logged in, and took over everything lost. Even if the inventory cannot be preserved, and is instead replaced with a new character inventory, it can be OK. If the game thinks it's a new character, and just gives the new character stuff the old one had in a batch operation, that should effectively get around any bug of this type (and there appear to be quite a few versions of it).

**Comment by D3nnis3n** [comment]
We fixed the original bug that lead to this issue, it's generally better to just fix bugs instead of providing complex workarounds for rare bugs that could potentially crop up, but likely won't.
