### ISSUE TITLE
[0.9] Give a debug tool to deposit X items into a stockpile

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoSuggestions#1012]
I've been playing a bit in singleplayer to test out some 0.9 recipes and one thing that's still a chore even with debug tools is creating enough resources for a large production (to actually produce a thing and not just conjure it into existence). The `/give` command has been useful, but it's still limited by inventory space - can't easily conjure 500 logs. It would be nice to have something like a `/give` but that targets a stockpile and conjures item into it, like `/deposit CoalItem, 500` to dump 500 coal into the stockpile someone is looking at.

**Comment by johnkslg** [comment]
Theres a command /build stockpile <item name 1> <item name 2> <etc> that will do this
