### ISSUE TITLE
Vegan Food Options

### ISSUE THREAD

**Issue by Elliander** [StrangeLoopGames/EcoSuggestions#1024]
I love how the game is about both nutritional balance and the quality of the nutrition. It's very realistic. Less realistic, however, is that meat is apparently the only option for a balanced diet.

If I eat lots of salad the diet will be deficient in fats and proteins, as an example. If I don't eat Charred Meat (for balanced diet) or Simmered Meat (for higher quality ingredient) or both I won't get as many skill points as I otherwise could. I could eat bean paste for protein, but my tests show that I get more skill points from charred meat over the most advanced bean recipe in the game.

Well, why not Tofu? In real life, most of the calories in Tofu come from the protein and fats, with slightly more protein than fat. Maybe that could be used in a vegetable recipe for a Tofu Stir Fry that is nearly balanced in it's final form, keeping players from having to guess at how to balance separate food items (and, speaking of which, a meat based stir fry could also work like that)

Or Tempe? A scrambled Tempe with Turmeric Powder is highly nutritious in real life. (and speaking of which, domestic birds for producing eggs to make egg based recipes would be great for Vegetarian options of fat and protein)

Overall, the game seems to emphasize meat as a basic requirement for a balanced nutrition and that doesn't seem right. It's good to show that it's the easiest and cheapest option for a balanced nutrition, as that reflects real life, but shouldn't be the only way to go.

**Comment by D3nnis3n** [comment]
That's rather a very philosophical and unfortunately way too idelogical topic. Scientists in my country have proven clearly that a balanced diet without meat and artificial nutritients is impossible, a balanced diet is only possible by actually balancing everything out, including meat. Obviously anyone not agreeing to that study, will now present another stating the opposite and another one will provide another one with again the opposite opinion.

I don't think we really want to dive into that currently, so for now this is not a option. It's a game after all and people of any type of eating habits should be able to understand that killing animals in Eco is as realistic as killing people in Counter-Strike.

The next issue is that while you state it's unrealistic, other people would stay it's unrealistic if all nutritients could be gained in perfectly balanced ways just from regrowable plants - which also has effects on the games simulation, as growing stuff is way easier than getting meat, especially with future additions of animal husbandry and mass-producing of meat via big factories. That's all stuff we already have in our minds and will be used to criticise eating behaviours, but it's rather about the how we do it currently and the effects and not the what we eat, as balancing everything is scientifically the best option for a human being.
