### ISSUE TITLE
Have a notification appear if the drive the server is running on is close to running out of space

### ISSUE THREAD

**Issue by Elliander** [StrangeLoopGames/EcoSuggestions#1028]
I noticed that EcoServer will abruptly crash the moment the server runs out of space. It makes sense for it to do this, since the server will be creating backups that will grow over time, but the crash is avoidable if the host knows that it's running out of space.

Maybe a server setting could exist to put up a dialog box or otherwise notify in some way that a certain percentage of free space is left, so that the host can shut it down gracefully and move to another drive or clear space as necessary?

**Comment by D3nnis3n** [comment]
This is something that should be handled on the server side, not on the program side, therefore closing.
