### ISSUE TITLE
[0.9 Staging-1504] Executing new propositions started by a vote

### ISSUE THREAD

**Issue by NN-Mike** [StrangeLoopGames/EcoSuggestions#1031]
A Capitol has been ratified granting players permissions to perform actions immediately:
![image](https://user-images.githubusercontent.com/54982803/79121911-569a4400-7d8e-11ea-9a65-0da0da7b2278.png)
A player who does not have this executive permission creates and submits a draft, starting an election:
![image](https://user-images.githubusercontent.com/54982803/79122071-ba247180-7d8e-11ea-8fc3-3b3c95e04873.png)
![image](https://user-images.githubusercontent.com/54982803/79122264-2b642480-7d8f-11ea-85be-ff7b217b858b.png)

There is currently no way to immediately pass these propositions once submitted for vote, a workaround found was to veto them at a ballot box, sending them back to draft and then the executive submit the existing draft for immediate passing.
The other would be for other players to not submit them and leave them as a draft instead.

Can we have an option to pass elections if we are an executive with permissions and also, sometimes we may want to submit a vote instead of execute immediately when holding title permissions to execute immediately?

**Comment by D3nnis3n** [comment]
You should be able to have an election type that can be passed by specific people immediately while others need to vote, it should be in the game? If it's not please create an issue over on the bugtracker.
