### ISSUE TITLE
Ecosystem Suggestion - Allow Redwoods to (eventually) become Old Growth Redwoods

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoSuggestions#1050]
If redwoods were able to mature, it would obviously take an absurd amount of time, and be susceptible to other problems of ecosystem and suchlike, but a civilisation that survives long enough might feel a huge amount of achievement for seeing a redwood mature into old growth.

This is clearly more of an achievement/heirloom mechanic, but it seems odd to me that this is just entirely unachievable, even with unreasonably huge amounts of work.

**Comment by D3nnis3n** [comment]
They are hundred of years old, hence they were intended to not be regrowable. They might become a special resource later on as well, so the limitedness is even more intended. I keep the suggestion open, but can't make you any hopes for this in the foreseeable future.

**Comment by trickenso** [comment]
Absolutely not expecting anything - just thinking that a settlement that survives for the equivalent of hundreds of years might look after the survival of redwoods for that long. Definitely agreed that they shouldn't feel like a renewable resource.

> They might become a special resource later on as well, so the limitedness is even more intended.

That makes sense - exciting! Thanks for the feedback.

**Comment by D3nnis3n** [comment]
Hello trickenso,
thanks for your suggestion, we really appreciate it. :)

For now, we want to keep the Old Growth Redwood a unique species that cannot regrow to full potential. They stand out uniquely and their material is planned to be used for special building blocks where the uniqueness and the choice of players to not put them down for max wood gain in early game is an intended challenge. Not everything should be renewable in Eco :)
