### ISSUE TITLE
QoL: Move initial tier benefits delivery into void storage

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoSuggestions#1051]
e.g. meteor shard, alpha hat, etc.
Simply place them in an void storage, player can extract them himself when he wants to use.

Why? Because at the beginning of the game there is a problem with free space and in the void they will not bother.

@mirasrael @D3nnis3n

**Comment by ThePiachu** [comment]
Also, maybe some of the bonus clothing could be just clothing options you could choose during character creation? Not sure if that would mean you could dup the items though...

**Comment by D3nnis3n** [comment]
This has been implemented, hence closing this issue :)
