### ISSUE TITLE
[0.9] Add sample laws for people to use

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoSuggestions#1054]
While creating custom laws is nice and all, it would be useful to have some pre-existing library of custom laws you could easily import into the game. Some defaults could include:

- Laws for building roads and getting paid
- Laws for taxing people turning inactive
- Laws for UBI
- Carbon Tax / emission limit

etc. These would serve as good defaults for new players to use, a teaching tool on how laws work and a good basis to build up and tweak from.

**Comment by D3nnis3n** [comment]
A lot of those can be found in the respective community channel on our discord. They will be updated to 9.0 as well, you can even help with that if you like.

**Comment by D3nnis3n** [comment]
Closing this issue for now. Law Examples will be available on our Discord and possibly on our Wiki. Maybe we'll be putting two or three examples into the Ecopedia as well, but for now we won't provide "ready to use" laws, as that's not the intention of the system. With export / import later on such laws could still provided by the community eventually. All the law features are described in big detail and it should be easy to make laws, especially easy ones.
