### ISSUE TITLE
[0.9] Make creating demographics / groups easier

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoSuggestions#1072]
On our test server we had a group of players that wanted to create a demographics for themselves to make it easier to share authorisation and so on. However, doing that of course involves going through an election process and those might not always pass.

It would be nice if users could create groups / demographics easier so they can group together easier. However, this would mean either creating a separate system that's like demographics but doesn't involve elections and wages, or separating wages into their own thing and making sure it's not that easy to alter the baseline demographic. Probably the first option would be better...

**Comment by SlayksWood** [comment]
Why don't you use Registrar? You can make title and add all people you want.

**Comment by ThePiachu** [comment]
Hmm, I guess that would be the solution that both they and me missed...
