### ISSUE TITLE
SUGGESTION: 2-D Minimap

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#109]
_From @GophTheGreat on April 24, 2018 3:44_

From a Steam comment (https://steamcommunity.com/app/382310/discussions/4/3288067088119203125/):

"The minimap world makes you lag on big worlds and even small ones please optimize! 
It would be nice if their was a 2d minimap that was less intensive for bigger maps maybe?"

_Copied from original issue: StrangeLoopGames/EcoIssues#7362_

**Comment by D3nnis3n** [comment]
We added a 2D Map in 9.0 :)
