### ISSUE TITLE
[Web Or EcoPedia] Law action explaination

### ISSUE THREAD

**Issue by lagonnebula** [StrangeLoopGames/EcoSuggestions#1099]
Hello,

It would be great to have information about law action.
Like what is the value of the Co2 emission (PPM) for the law, is it lifetime emission or daily value, does it apply to vehicule, industry ? ect ... 
Or Play action, is it lifetime or daily value ect ...

**Comment by johnkslg** [comment]
In 9.0, it will show in tooltips

**Comment by lagonnebula** [comment]
I have a question for 0.8.3.3 is it intented to not count industrial machine into Co2 per player in law ?

**Comment by D3nnis3n** [comment]
Hello lagonnebula,
thanks for your suggestion :)

As John already mentioned all the law actions are explained in tooltips in Update 9.0.

Given your suggestion was implemented, i'm closing this issue.
