### ISSUE TITLE
Suggestions for a few small but (in my opinion) fairly important changes to skill selection

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoSuggestions#11]
Instead of spending skill points immediately on the skills menu one should be able to invest points and then have it confirm before the skill points are spent (with the ability to remove skill points from the changes) since the cost per level up isn't listed until you go to invest in that specific level and it varies from skill to skill giving the player a confirmation/edit on the skill tree would help people visualize their builds and plan them accordingly as opposed to "okay get this to level four, and now five and now.......wait what do you mean that's 60 skill points I still needed to buy xyz that's alot cheaper, if I'd have known I'd have waited" should do alot to make the game more accessible especially as an educational tool.

**Comment by D3nnis3n** [comment]
The skill system has since been revamped totally two times, hence this Suggestion is no longer applicable to the current state of the game.
