### ISSUE TITLE
[0.9.0 Staging-1538] - Hammer block type selection is awkward

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoSuggestions#1107]
Holding F while selecting a block type and then having to release F to close the menu is quite awkward, and seems like a holdover from the old block selection, rather than making sense for the new menu.

Since you now have to click to select a block, could you tap F once to open the block selection menu, and then click once to both select the block and close the menu? This might be more streamlined.

**Comment by trickenso** [comment]
I also prefer holding F, it just made more sense when the process was Hold -> Scroll Wheel -> Release.

Right now it's Hold F -> Click block selection -> Release F, and I wondered why clicking the block type couldn't skip straight to building. It feels like there's two confirmation actions for some reason, and it seemed unnecessary to me.

**Comment by elfl0rd** [comment]
Because you may want to change the type of filling (cube/line/plane, etc.).

**Comment by trickenso** [comment]
Thanks for highlighting the use case - having played with higher-tier tools, this makes more sense.

Doing this with only point placement is clunky in comparison, but it's an efficient way of selecting multiple build options.
