### ISSUE TITLE
SUGGESTION: Different seasons and Animal farms

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#111]
_From @AnteThePie on April 23, 2018 11:32_

Hey! I just started to play the game and i realised that there is no seasons implemented and i was wondering if it will and when? I Also woundered about if you will be able to start animalfarms and such.

Thank you for your time!

_Copied from original issue: StrangeLoopGames/EcoIssues#7348_

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoSuggestions/issues/1568

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoSuggestions/issues/1569
