### ISSUE TITLE
Make random avatars less ridiculous

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoSuggestions#1125]
@MarjieAVolk commented on [Tue Dec 12 2017](https://github.com/StrangeLoopGames/EcoIssues/issues/3087)

Suggestions:
- Hard code a set of starting clothing colors
- Make hair color be darker than skin color

**Comment by trickenso** [comment]
Not sure I agree with the hair colour point:

https://www.google.com/search?q=dark+skin+grey+hair+men
https://www.google.com/search?q=dark+skin+grey+hair
https://www.google.com/search?q=dark+skin+blonde+hair+men
https://www.google.com/search?q=dark+skin+blonde+hair

**Comment by WeaselDog** [comment]
I meant to transfer the issue, not necessarily agree. I think you are right with your points.
