### ISSUE TITLE
[Suggestion] add a vanish command

### ISSUE THREAD

**Issue by TazMatic** [StrangeLoopGames/EcoSuggestions#1136]
Justification: With Eco growing in popularity and soon to be getting a huge explosion of players we currently are starting to deal with cheaters on an increasing bases. While tools are being developed to help detect hackers, the good old being able to watch a player to get evidence while they don't know you are watching is crucial.

Issue: Using the current game engine it seems to be impossible for a player to render themselves invisible via server command. This greatly reduces the effectiveness of the game admins.

Proposed solution: Add either a flag on the player object such as isVisible or make an admin command to tell the server not to send player update cords but allow chunk loading.

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoSuggestions/issues/1354
