### ISSUE TITLE
[Suggestion] Z-coordinates

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#115]
_From @Elliander on April 21, 2018 1:57_

I'd like to see the Z-coordinate on a map, as it would help me when digging tunnels since the level ground on one side of a mountain can be different from the other side. I also think that Z-coordinates would be helpful if my other suggestion about mineral rights was ever applied.

_Copied from original issue: StrangeLoopGames/EcoIssues#7318_

**Comment by D3nnis3n** [comment]
The Z (depth / height) can be viewed on the right bottom side for a while now.
