### ISSUE TITLE
Solar Panels change request

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoSuggestions#1156]
1) it should be a "Solar Tower" or "Heliostat" it is not real solar panels
2) Solar tower needs water for function. But output clear water too.

https://github.com/StrangeLoopGames/EcoIssues/issues/11385

**Comment by elfl0rd** [comment]
Useless pipe ports are not covered by other issues as @keegan-o mentioned in linked issue.

**Comment by D3nnis3n** [comment]
Solar Panels were renamed Solar Generator as has been intended from the beginning, the friendly names were bugged.
In regards to the need of Water, that's handled by Keegan, hence i'm closing here.
