### ISSUE TITLE
Ability to Output /help and /helpful and other /commands to a text file like Windows command prompt can do in Windows

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoSuggestions#1157]
is there anyway that a simple command option in chat can be implemented like
**/help >some-descriptive-filename.txt** 
**/helpful >some-descriptive-filename.txt** 
will output the commands to a named text file in root directory instead to chat window?

it saves having to snapshot 6 pages of chat channel (see below) to work out the commands (then having to manually copy from the snapshots to a text file or spreadsheet)

also if commands change in versions a simple command to text will give exact commands for version on rather than having to check all ones in chat against ones already manually typed previously.

Got this idea from help list that you get from type /help after a few Executable programs and the following page will show that just adding a simple > after /help  will output to a file or a >> will append to the same file

https://www.howtogeek.com/306682/how-to-save-the-command-prompts-output-to-a-text-file-in-windows/

will leave it up to you where the file can be saved, example root of eco.exe or maybe the ability to add the path to a location

**Comment by Conchipedia** [comment]
![snap6995](https://user-images.githubusercontent.com/29383891/88960959-34282a00-d29c-11ea-90b8-af68403db5ed.png)
![snap6996](https://user-images.githubusercontent.com/29383891/88960960-368a8400-d29c-11ea-9d58-e56daa2a7913.png)
![snap6997](https://user-images.githubusercontent.com/29383891/88960968-38ecde00-d29c-11ea-9219-7c09b0915368.png)
![snap6998](https://user-images.githubusercontent.com/29383891/88960977-3ab6a180-d29c-11ea-972d-8133b1cf001e.png)
![snap6999](https://user-images.githubusercontent.com/29383891/88960984-3db19200-d29c-11ea-9dcc-cabfb3f31e47.png)
![snap7000](https://user-images.githubusercontent.com/29383891/88960990-40ac8280-d29c-11ea-9c50-63878b41dfc6.png)

**Comment by D3nnis3n** [comment]
Your suggestion has been accepted, but will be done in a different way, see here: https://github.com/StrangeLoopGames/EcoIssues/issues/17591
