### ISSUE TITLE
[0.9.0.0 beta staging-1702] Game claim I am on someone property when I am not

### ISSUE THREAD

**Issue by matheod** [StrangeLoopGames/EcoSuggestions#1165]
opelwork property is the one we can see behind, but it's not where the tree log is.

![image](https://user-images.githubusercontent.com/339611/89191777-b61d9900-d5a3-11ea-8c08-dda1551c0878.png)

![image](https://user-images.githubusercontent.com/339611/89191854-d0f00d80-d5a3-11ea-95bb-2fe78878eceb.png)

**Comment by D3nnis3n** [comment]
This is working as intended. Trees retain the ownership of the property they were one before felling when they fell.
