### ISSUE TITLE
[v9] Allow admin to use /civics spawngov

### ISSUE THREAD

**Issue by matheod** [StrangeLoopGames/EcoSuggestions#1166]
This is usefull for player to do test in solo

**Comment by D3nnis3n** [comment]
The command can be used by owners of developer tier in singleplayer which seems sufficient. It is a QA command that is used in development only and while I see that it is useful for admins, it can also cause irreveokable damage and should never be used on live servers, allowing them for all admins would do that though. The time needed to spawn stuff in and set it up by using the /build or /spawn commands is not so much higher that it leads admins to buy dev-tier just for this command, so it's not a cash-grab either.

As we don't plan to implement this suggestion, I'm closing this issue.
