### ISSUE TITLE
[v9] Allow admin to use /meteors comamnds

### ISSUE THREAD

**Issue by matheod** [StrangeLoopGames/EcoSuggestions#1169]
In V8, admin could use the meteors commands which is very usefull if for example the admin want to extend the meteor life duration. It was also used by youtuber (and player) to show meteor crash after winning a game.

In V9, all /meteors commands require to be dev. It should be reverted to admin level.

**Comment by D3nnis3n** [comment]
Hello matheod,
thanks for your suggestion. I just confirmed /meteor addhours does work as an administrator without dev-tier.

The other commands are intentionally locked from administrators, hence i'm closing this suggestion.

**Comment by matheod** [comment]
Yea sorry, addhours are avaible to admin.

![image](https://user-images.githubusercontent.com/339611/89532545-3afdf200-d7f2-11ea-9c31-88f08bbc3653.png)

However, there are a lots of command that were for admin in v8 that are now restricted to dev in v9 like the fall command youtuber used. Rain was also used by some.

I am also suprised that spawn is dev. It's seems a very basic command.

**Comment by D3nnis3n** [comment]
Those commands have been used in non-revertable ways, causing major issues on servers. We decided to remove all dangerous and QA commands from multiplayer and restrict them to dev-tier users. For /meteor spawn i'll add an issue over at GitHub.
