### ISSUE TITLE
Add server config to disable predator attacks

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoSuggestions#1170]
In fact, after turning it on, you get invisible spiders that keep biting you, which the game carefully informs you about.

I think that this setting should be a server that disables biting spiders as a class.

Besides, as a suggestion - the ability to disable biting animals at all - would be nice.

**Comment by elfl0rd** [comment]
In this case, you're wrong.
The main request here is the ability to totally turn off spiders, biting animals - an ugly innovation that does not add interest, but the ability to turn them off is an optional and difference suggestion.

**Comment by johnkslg** [comment]
Closing for now, sorry @elfl0rd we have to focus on other important issues like performance.

**Comment by elfl0rd** [comment]
No problem, for many reasons, I'm not gonna play 9 anyway.
Performance issues, ugly additions like biting animals, annoying taranrulas, annouing "brand new" sounds. etc.

And after closing the current topic in the suggestions, I will probably not disturb you with my suggestions and bug reports at all.
