### ISSUE TITLE
Add buy/sell material tags for shops.

### ISSUE THREAD

**Issue by SkyllarRisen** [StrangeLoopGames/EcoSuggestions#1180]
Now that processed stone isnt a thing anymore it would be really nice if we could set the shop to buy/sell any type of a material using the "tag" you already use for crafting recipes instead of having to set up all types. So basicly a "buy any rock/wood/etc." option.

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/14630
