### ISSUE TITLE
suggestion  Animal authority change

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#119]
_From @10KEco on April 20, 2018 0:7_

If you remove the property authority off of the animals it will give players more of a need to create laws about hunting. This will also give the opportunity to charge players who hunt on owned land. 

_Copied from original issue: StrangeLoopGames/EcoIssues#7300_

**Comment by BlazeGuy2** [comment]
_From @Elliander on April 21, 2018 5:44_

I like this idea. I didn't even realize people could hunt on my lands. Without fixing this I would easily expect people to hunt in other people's land preferably - just like how I catch players preferring to cut down trees at the edge of my property our outside their own rather than spoiling their own view.

**Comment by D3nnis3n** [comment]
Authentication can be overridden by laws now, which makes this possible.
