### ISSUE TITLE
Cast Iron Stove generates ground pollution

### ISSUE THREAD

**Issue by BrewCrewECO** [StrangeLoopGames/EcoSuggestions#1191]
Cast Iron Stove produces ground pollution.  Status tab of the object provides info about CO2 air pollution emissions, but no info on ground pollution.
0.9.0.0 build 1732
![Screenshot (66)](https://user-images.githubusercontent.com/70082568/90969548-52f69680-e4bf-11ea-9cc7-eb8292d50d1b.png)

**Comment by BrewCrewECO** [comment]
Sorry for making you repeat yourself but thank you for the explanation.
🍻

**Comment by D3nnis3n** [comment]
Engimage explained correctly the reason for this, hence i'm closing this suggestion.
