### ISSUE TITLE
Client Bug: Cannot use Books / scrolls

### ISSUE THREAD

**Issue by blumbee82** [StrangeLoopGames/EcoSuggestions#1208]
Windows 10
Client Version  0.9.0.1 beta
No Mods, clean fresh install
Unable to use books or scrolls
No claims gained or traid learned

**Comment by Thiritin** [comment]
To clarify he cannot Right-click on any scrolls or books. Elsewhere in the Game it works perfectly fine.

**Comment by Thiritin** [comment]
@blumbee82 could you resolve the issue?

**Comment by blumbee82** [comment]
yep

**Comment by Thiritin** [comment]
@blumbee82 could you explain how you solved the issue?
