### ISSUE TITLE
[Suggestion] Bug Zapper

### ISSUE THREAD

**Issue by Huntermeign** [StrangeLoopGames/EcoSuggestions#1212]
With the bugs and such added maybe a bug zapper wouldn't be a bad idea as a way to set up areas where people don't want bugs, and also serve as decoration.

**Comment by D3nnis3n** [comment]
Hello Huntermeign,
thanks for your suggestion, very appreciated.

Unfortunately we do not see this being implemented to Eco in the foreseeable future, so i'm closing this issue for now.
