### ISSUE TITLE
Allow deed owner to cancle projects started by others

### ISSUE THREAD

**Issue by Kenionatus** [StrangeLoopGames/EcoSuggestions#1214]
Currently, the only way to deconstruct a workstation that has other people's projects on them is to finish them. This can be somewhat annoying in the case of abandoned properties (Unclaimed by Law after a certain inactivity period.)

I suggest that the owner of a workbench should be able to cancel all projects. Maybe even every player authorised on the deed.

There is conflict or trolling potential with open workstations if this suggestion gets implemented. The owner could waste other players labor by cancelling their projects. If this needs to be stopped, I'd suggest to only give the option to cancel projects if the workstation is idle. However, I don't think that it would be a problem if they were cancellable all the time.

**Comment by kyle079** [comment]
I also think other should be able to cancel jobs. We had an issue with someone who left but had active jobs so we couldn't remove any of their crafting benches.

**Comment by Blanclour** [comment]
Yes I have noticed this to be an issue on my server as well, I feel the owner should be able to cancel other's jobs on their property.

**Comment by D3nnis3n** [comment]
Hello Kenionatus,
thanks for your suggestion.

This is actually already possible after a waiting time of 24 hours. We do not plan to extend this currently, hence i'm closing this suggestion.
