### ISSUE TITLE
Add ability to set inputs/outputs

### ISSUE THREAD

**Issue by IdkIjustwantedtosuggestsomething** [StrangeLoopGames/EcoSuggestions#1220]
It would be nice if you could set specific inputs/outputs on crafting stations and stores. Due to the way storage works in the game, it would be very useful if you could set a crafting station/store to pull materials from specific stockpiles and output the crafting products into specific stockpiles as well, maybe even with a way to filter where specific items are taken from/go to if multiple inputs/outputs are selected. This would also work well for shops to prevent the store storage from filling up to the maximum, or so that when a store buys materials it end up in a stockpile or chest that the right crafting station can reach.

**Comment by Kenionatus** [comment]
Output limits would be great as well. E.g. have the order for Hewn Logs pause when there are more than 100 in the output storage.

**Comment by IdkIjustwantedtosuggestsomething** [comment]
Just realized this has already been mentioned. Link to issue if you want to vote on it: https://github.com/StrangeLoopGames/EcoSuggestions/issues/654
