### ISSUE TITLE
Registrar

### ISSUE THREAD

**Issue by Artem314159** [StrangeLoopGames/EcoSuggestions#1224]
It would be logical to transfer the regitrator's craft to the capitol, to other government objects. And then it is not logical that the elected and non-elected titles are not only divided by government tables, but also divided by epochs - almost all government objects can be crafted from hewn logs and mortared stones, and the registrar can be created only by reaching the lumber.

It might also be logical for the Registrar to use civil articles on title changes.

**Comment by ThePiachu** [comment]
Agreed that Registrar should be a gov building, same with a number of things from #1056

**Comment by D3nnis3n** [comment]
The registrar is not supposed to be a government building, as it is supposed to be used by players to form entities, be it a company or anything similar. While it does also serve the purpose of providing government with manual titles, that is not the only purpose. The epoch thing on the other hand is very true, but already mentioned in ThePiachus issue, hence I'm closing this issue, as we do not intend to change this.
