### ISSUE TITLE
Option to separate Character XP from the multiplayer

### ISSUE THREAD

**Issue by xKingPanda** [StrangeLoopGames/EcoSuggestions#1227]
We keep having the problem where we some people make some amalgamation of a house that just gives them xp and everyone else has to rush and do the same thing otherwise they will be overwhelmed by the player who focuses on that and thus making that players job have less value. I know that there is a server option to change the cooperation level but you still run into the same problem. It would be nice to just have an option that way people can choose how they would like the server to play

**Comment by D3nnis3n** [comment]
Can you specify what you mean with "seperate Character XP from the multiplayer"? It seems like you rather want to disable Housing XP?

**Comment by D3nnis3n** [comment]
As we got no response to our question and the point of the suggestion not being clear enough, I'm closing this issue.

I guess that you maybe meant 'multiplier', but the whole skillsystem is made around the factor of character XP being based on a multiplier, it would equal a near complete removal of the housing and food xp if that was no longer the case. Players that focus on better houses early should get this benefit and players that build ugly stuff that the server doesn't like should be dealt with by server rules or laws. We also do look into systems of rating houses and other possibilitites to make incentive to build houses at least in a basic nice way - but this is a different issue, even though a possible solution to your issue.
