### ISSUE TITLE
Add a Work(all) button when crafting.

### ISSUE THREAD

**Issue by edwardt4482** [StrangeLoopGames/EcoSuggestions#1233]
Clicking the "Work" button when crafting large batches gets extremely tedious.  Some of my large batches have required over 400 clicks to perform all the labor.  My suggestion is to add the ability to perform all the labor possible based on the amount of calories you have, of something similar.

**Comment by IdkIjustwantedtosuggestsomething** [comment]
That already exists. Press Alt then you click the work button. (it may be ctrl. One is for 5x labor, one is for max labor)

**Comment by samlander25** [comment]
Would suggest adding a tool tip when mousing over the work button to make that more verbose/evident

**Comment by D3nnis3n** [comment]
Closing, as this feature already exists.
