### ISSUE TITLE
Input and Output separate priority list / separate check-boxes

### ISSUE THREAD

**Issue by ShoppyCodes** [StrangeLoopGames/EcoSuggestions#1235]
Input and output priorities should have the ability to be different, and also the tick boxes separated for input/output too. 

Example: I have Stockpile A, a building producing things, and Stockpile B. I want to only take from Stockpile A for this building but not EVER put back into the same stockpile with with the finished product. Yes I can prioritise, but if Stockpile B (output) gets full it then fills up A (input). It would be nice to be able to be able to separate this so it doesn't block things and/or get messy.

**Comment by IdkIjustwantedtosuggestsomething** [comment]
https://github.com/StrangeLoopGames/EcoSuggestions/issues/654 This has already been mentioned. Go vote for it (thumbs up) on that thread :)

**Comment by D3nnis3n** [comment]
Duplicate of #654
