### ISSUE TITLE
Stockpile Filters

### ISSUE THREAD

**Issue by ShoppyCodes** [StrangeLoopGames/EcoSuggestions#1236]
It would be useful for more complex builds to be able to set a filter of what can automatically go into stockpiles from buildings.

**Comment by IdkIjustwantedtosuggestsomething** [comment]
This has already been mentioned. Go vote for it (thumbs up) on that thread :)
 https://github.com/StrangeLoopGames/EcoSuggestions/issues/654

**Comment by D3nnis3n** [comment]
Duplicate of #654
