### ISSUE TITLE
Make Eco Server GUI display world name, ask to generate a new world or load existing world on startup

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoSuggestions#1241]
I've tried using the Eco Server standalone (0.9.0.3 br-78) to generate a new world with some tweaked parameters. Unfortunately, before I could change those parameters, the program already decided to generate a new world with old parameters. Same if I try changing existing world - the server program will load the default world first rather than ask you which world you'd like to host.

It would be nice if the Eco Server asked which world you want to load on startup, or if you want to generate a new world and/or tweak the world generation settings before you do. It would save a lot of hassle.

Also, it would be nice if the world name was front and centre on Eco Server GUI, so I don't have to guess if it loaded the correct world or not :P.

**Comment by D3nnis3n** [comment]
I don't see this being implemented anytime soon, especially as GUI use is getting rarer and rarer and getting rid of it completely is something that might happen as well. The GUI starts after the server has already booted, doing this would require to change how it works - but that would possibly infringe with people that run the game in background without the GUI.

I'm therefore closing this issue.
