### ISSUE TITLE
Logging tevel 6 talent "Cleanup Crew" doesn't work

### ISSUE THREAD

**Issue by jtac** [StrangeLoopGames/EcoSuggestions#1243]
According to description, logging level 6 talent 'cleanup crew' should negate calories used when cleaning up debris (wood pulp), this doesn't work.

bug: Chopping debris uses calories as normal.
expected: Chopping doesn't use calories.

**Comment by D3nnis3n** [comment]
The description only states it removes the penalty on the calorie consumption. So what it does is effectively reducing debris cleanup calorie consumption to about what it takes to chop trees, but it neither says nor is intended to remove the cost completely.

I'm therefore closing this issue.
