### ISSUE TITLE
Collaborative skill progression rate

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoSuggestions#1252]
I'm one of those players that tends to go all-in when playing the game and wants to squeeze out every bit of Skill Point progression I can not to be behind other hardcore players. This, however, makes the game a bit more competitive and sometimes you want to have a more relaxing experience where everyone is on an even footing. For this we would need a new way of acquiring skill points - a collaborative skill progression rate.

Basically, room SP bonus would be more communal. Every housing room does not count towards the owner's skill point progression, but goes into a global pool. Then the SP from that pool either gets averaged out between the (active?) players, or assigned in a reverse order - those with the least skill points get assigned the best rooms, etc. to catch them up to speed.

This incentivises you to build more rooms with equal SP ratings, a bit reminiscent of [Khrushchyovkas](https://en.wikipedia.org/wiki/Khrushchyovka). This way the only way to benefit yourself is to make sure everyone is taken care of. You could have people building skyscrapers with these kinds of rooms, same floor design over and over. This would increase the demand for furniture (now you need to build 100 fancy bathrooms for everyone on the server rather than 10 for the richest ones), it would encourage rich players to spend and build more (the only way for you to benefit is to raise everyone up, and those with the means should contribute to the ones without), and it would be a large project for the government (see #1084 , #1079 ).

It would also impact some of the food situation - you would want everyone to get good food because that means their SP would go up faster and they wouldn't need to be assigned more housing to make up the difference. This could encourage some investing into better foods and maybe some communal kitchens...

Perhaps this idea would work well as a government setting. Default government would be about private house ownership where you get the house SP the normal way. An alternative system would give people the communal housing. This would work really well for when you'll have more than one government and then you could opt-in to such a commune!

**Comment by D3nnis3n** [comment]
Seems very similar to https://github.com/StrangeLoopGames/EcoSuggestions/issues/1147, hence i'm closing as a dup, copying it over.
