### ISSUE TITLE
meteor difficulty setting

### ISSUE THREAD

**Issue by DanielKispert** [StrangeLoopGames/EcoSuggestions#1285]
When entering settings for your new world, a "meteor difficulty" setting could have some presets, like the collaboration setting. 
It would change how many lasers are required to shoot the meteor, e.g. easy/normal/hard/very hard for 2/4/6/8 required lasers.

Very closely related to https://github.com/StrangeLoopGames/EcoSuggestions/issues/76, just a lot smaller.

**Comment by D3nnis3n** [comment]
We already have such a setting as in Expensive Mode for the Computer Lab. Hence, i'm closing this issue.
