### ISSUE TITLE
Add a sign / text color / etc. guide to the wiki / ECOPedia

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoSuggestions#1286]
Playing on some servers recently I noticed people were putting icons on their signs, which looked pretty cool. A lot of players, myself included, had to ask how to do that. Same with changing the colour of text in store's name and so on - I still can't figure out how to do it properly.

It would be nice if the game wiki or the ECOPedia had some pages describing what you can do with those and what exact commands to use to make that happen.

**Comment by DarkDaskin** [comment]
There is already the [Chat Commands wiki page](https://wiki.play.eco/en/Chat_Commands) for that. The title is not very intuitive though, but I easily found that page via Google.

**Comment by D3nnis3n** [comment]
Indeed, the intention of the Ecopedia is displaying actual game mechanics, not information on configuration or chat features, for those please use the Wiki (where you can add pages at any time).
