### ISSUE TITLE
Money transfer window needs a search functionality

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoSuggestions#1292]
When you want to transfer money, first you need to scroll down to select the proper currency:

![image](https://user-images.githubusercontent.com/964559/98226615-202f3c80-1f0b-11eb-8c2b-12f20ffc53bf.png)

And then you need to select the proper account:

![image](https://user-images.githubusercontent.com/964559/98226679-33daa300-1f0b-11eb-8211-81f76cfd4f08.png)

However, there are three problems with these:
- The minted currencies are not separated from IOUs
- The created bank accounts are not separated from personal bank accounts
- There is no search for either of them

However, there already exists a solution for these problems right here:

![image](https://user-images.githubusercontent.com/964559/98226874-77cda800-1f0b-11eb-94bf-391863a15ea2.png)

- The list is way faster to operate than the other list
- You can actually search for things and that's awesome!
- Things are clearly separated based on what they are - demographics are separate titles, which are separate from people!

Could we have this but for money?

- Minted currencies should be separate from IOUs and on top of the list (most people will use those!)
- Created accounts should be separate from personal accounts and also on top of the list (for consistency)
- Search would let you find what you are looking for easily

Bonus - IOU currencies should only be displayed when you actually search for them (so if you only have "Dollar" and "ThePiachu IOU" in your wallet, your list by default only has those until you start searching for "Den" and then it reveals that there is also "Dennis IOU" or the like) to make the list only contain what's useful to you - you can't make a transfer in an IOU you don't own, so why display it? If you want to transfer something, first select a proper account that has a balance!

**Comment by D3nnis3n** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/14356
