### ISSUE TITLE
Skid Steer drop "ghost" rubble

### ISSUE THREAD

**Issue by Dani1973** [StrangeLoopGames/EcoSuggestions#1296]
When digging in stone with a skid steer some rubble falls on the ground but it cannot be picked up.
Rubble disappears after relog.

**Comment by ThePiachu** [comment]
This is a space for suggestions. For bugs and errors, check https://github.com/StrangeLoopGames/EcoIssues/ . Your issue has been reported https://github.com/StrangeLoopGames/EcoIssues/issues/19100 .
