### ISSUE TITLE
Research should be a separate skill to survivalist

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#130]
_From @CuAnnan on April 16, 2018 13:24_

Once the skill tree is complete, the research skill becomes useless.

Worse yet, it is unrefundable. So, if you're like me, you've sunk a considerable amount of SP for the good of everyone. But you can't get it back (at whatever the server penalty is)

_Copied from original issue: StrangeLoopGames/EcoIssues#7228_

**Comment by D3nnis3n** [comment]
No longer applicable.
