### ISSUE TITLE
Server browser "Online" should be players who are online/not abandoned

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoSuggestions#1303]
Server browsers "Online" should show players online/NotAbandoned

Ie server has 125 characters on it, 75 of them are abandoned and 15 online it would show 15/50 not 15/125

This will give a more realistic player count in the server browser due to the amount of players who hop onto a server never to come back again.

**Comment by BartonsGit** [comment]
I love this idea. Perhaps a calculation on the server population can be done against the swagger API running on every server?

An API call against the in-game Abandoned demographic or some other stat on the server can be used.

**Comment by D3nnis3n** [comment]
The value of players is intended to display all players that ever have been online. While this suggestion would be very possible, there is the issue of administrators being able to adapt the abandoned demographics to their liking, allowing them to effectively manipulate the server listings and player opinion. We also have plans to no longer have these default demographics at all, but only providing a template for easy enacting of them.

Compares to these options and difficulties the system of showing all players that ever joined is much fairer to the potential joining player, as he can be assured the value is based on the same data - not to mention that it is quite interesting to see how many players ever joined a server and something the community loves to compare.

I don't see this being implemented at this time, hence I'm closing this issue.
