### ISSUE TITLE
Placing Waterwheels in Aqueduct to make power

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoSuggestions#1309]
I saw this bit from Codestream 
The Waterwheel must be in non-ocean water to function. (It is not a tidal generator!)
The Waterwheel can generate double its normal output if the Waterwheel's lower edge is submerged AND one edge is inserted into a waterfall.

and was wondering if Aqueducts could be made to help us get a waterwheel working (it would encourage players to use them more)

these
![snap7658](https://user-images.githubusercontent.com/29383891/99852550-206d4000-2b79-11eb-8026-af08a0ee7a5c.png)
![insta](https://user-images.githubusercontent.com/29383891/99852707-717d3400-2b79-11eb-8776-1e50f300938b.gif)

![snap7659](https://user-images.githubusercontent.com/29383891/99852588-3418a680-2b79-11eb-8403-8a69fb02db1f.png)
![insta](https://user-images.githubusercontent.com/29383891/99852782-970a3d80-2b79-11eb-9f97-029c0013a78a.gif)

couple of ideas i had, not sure if this counts as waterfalls
but i did have trouble with the waterwheel being placed into the downward generated waterfall as it said it was blocked, i stopped the waterfall by turning off the pump and blocking top aqueduct then placed waterwheel in exact same spot and restarted them
for some reason waterwheel seems to think falling water blocks it

**Comment by Engimage** [comment]
Neat idea. Create an aqueduct from a river/whatever to power the waterwheel.
The last screenshot is absolutely wonderful!
https://user-images.githubusercontent.com/29383891/99852782-970a3d80-2b79-11eb-9f97-029c0013a78a.gif

**Comment by IcedForge** [comment]
Will be working in 9.4, will close this.
