### ISSUE TITLE
Add the ability to play on small or very small planets

### ISSUE THREAD

**Issue by lou-vier** [StrangeLoopGames/EcoSuggestions#1325]
### **Actual situation**
Currently, the tiniest planet we can play on it is 0.52km², and I think it's a too large world to play on it when we are only 5 people or less on this planet. It does that the pollution system is not really impacting the ecosystem, and so the game is not really challenging on this point, unfortunately.

### **The dream**
So I've imagined a game for example in a tiny tiny world (like 0.26km²), and I've thinked it would be very challenging to not destroy the ecosystem on it, so the challenge would be real, and the game would be harder on this configuration.

### **The big dream**
I've imagined too, a playable planet very tiny for one player (like 0,13km²), where the ecosystem is a fragile balance, with small animal & plants populations, it would be very fun and challenging to play on it.

### **The end of the suggestion**

**Comment by D3nnis3n** [comment]
Hello Lou,
worlds below 0,52 km² can already be created, but may be unstable just as worlds above 4km². Anything 20x20 and below will work as well but bug out, due to the wrapping being no longer technically possible at this size. Official support for sizes below that will not be given, though, hence i'm closing the suggestion.

**Comment by lou-vier** [comment]
Thank you for your answer ! But where is the parameter for the world size when I create a game world ?

**Comment by D3nnis3n** [comment]
World size can only be edited via config files in WorldGenerator.eco - you need to use a dedicated server for it.
