### ISSUE TITLE
Fishing Expansion for the Hunters/Butchers

### ISSUE THREAD

**Issue by no85611** [StrangeLoopGames/EcoSuggestions#1346]
Hello,

I just started playing the game for about 3 days and managed to have 30 hours on the official Christmas server. 
The games amazing and will blow up. Ya'll already know the glaring issues also.

Hunting is fun and rewarding except for fishing: I haven't caught  a single fish. As a hunter I feel I am needed to provide protein and fats in everyone's diets. When I go to the big city and go too all the food shops, not one of them sells food that uses fish.
If ya'll add fishery boats and nets maybe the hunters can have something extra to do besides shooting teleporting animals.
Have animals provide the proteins and fish the fats.

I bet ya'll are already aware of this.

**Comment by D3nnis3n** [comment]
This is a mix of an issue (can't catch fish) and of already existing suggestions.
(For example here: https://github.com/StrangeLoopGames/EcoSuggestions/issues/976)

Expansion on fish is planned and we're aware of some issues making catching fish hard, but there also has been an intended change for fishing: You won't find fish in salt water, hence rivers is where you need to search for it.

As this is already existing, I'm closing the suggestion.
