### ISSUE TITLE
Animal Suggestion

### ISSUE THREAD

**Issue by Zephi** [StrangeLoopGames/EcoSuggestions#1359]
I like this game, in particularly enjoy the game for building and things. It would be nice to be able to tame and breed animals as a farmer, maybe add creatures like horses (and other farm animals not in the game). Perhaps you can breed either for food, stats and/or colors. It would also be fun to have animals you can tame, perhaps that give special perks, like cats and dogs. 

Another thing that would be nice is more furniture and block choices for building. Perhaps you can make artificial woods (for example) to make different colors and combinations of woods, or artificial items for detail. It would also be nice to have blocks like fences for both building and also keeping livestock. 

For a last suggestion, maybe there could be a way that people can make things like ponds, lakes, and rivers by taking water.

**Comment by JestinJae** [comment]
I also felt like there was a lack of a "breeding" mechanic to the farming aspect of the game.  It would only make sense for certain animals though and I think that perhaps part of why this isn't already in the game is that none of the animals are really appropriate for farming/taming.  The closest would be the buffalo, which I believe in some cases has been tamed.

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoSuggestions/issues/1568
