### ISSUE TITLE
Mail box,  or way to send a message to someone offline.

### ISSUE THREAD

**Issue by sirPattrick** [StrangeLoopGames/EcoSuggestions#1364]
Having a "mailbox" item,  createable at the workbench, that can be placed, and used to leave someone messaged when they are offline would be extremely helpful.  I know you can leave signs, but those are usually limited, and everyone can read them.  Plus if on unclaimed land, they can be edited by anyone.

**Comment by JestinJae** [comment]
I agree that this would be useful.

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoSuggestions/issues/1711
