### ISSUE TITLE
Question/Design info/Suggestion: ABCD vs "ramp" Pavement/Asphalt placement

### ISSUE THREAD

**Issue by JestinJae** [StrangeLoopGames/EcoSuggestions#1366]
Is there any particular reason that pavement follows the ABCD pattern for placement instead of the "ramp" placement used for earlier roads? Is this just a placeholder?  I know it isn't extremely time consuming to make a wide ramp because of the line tool, but I still think it would be easier to have a "ramp" archetype which would be the 1/4 slope still.  I know that would introduce a new concept to the currently single-block-size "forms", but I think it would be a nice QOL item.

UPDATE: I just found #1097 which is the exact opposite of my point.  However, if I'm understanding the OP's reason for the post it sounds like altering the placement formula would work for his scenario.  EG: You are at the top of a structure and want a ramp down, you hover over the edge of the structure and it would place the ramp there.  As it presently stands, 0.9.2.4, you can't do this, the ramp must be placed over flat ground.

**Comment by D3nnis3n** [comment]
Hello JestinJae,
as you have already noticed, we did indeed make this change on purpose and with the intention of allowing finer grained usage of the ramps and to get rid of the multiblock structures that were only present in roads and caused issues both with the law system and with the hammer that is now used to pick them up and is not intended to pick up multiblock structures. It also removed the needs for ramps.

As the vast majority of roads used are at least 5 blocks wide or wider, there also is no real time loss involved, it rather is faster to do than before, as roads are typically at least 5 wide when stone roads come into play with dirt roads as early roads still using the ramp system.

As we do not intend to change this behaviour, I'm closing this issue.
