### ISSUE TITLE
Add keybinding menu/settings

### ISSUE THREAD

**Issue by JestinJae** [StrangeLoopGames/EcoSuggestions#1367]
It would be nice if there were a keybinding menu.  

Sorry I don't have more of a description, but it seems pretty straight-forward to me.  If anyone would like an explanation of what a keybinding menu is they can reply and I will provide an actual explanation.

**Comment by D3nnis3n** [comment]
Hello JestinJae,
yes, a bit more of explanation would be needed, as we already have a menu for keybinds:
![image](https://user-images.githubusercontent.com/25908592/108944005-28e28480-765a-11eb-828e-2f3a9c94c5f9.png)

**Comment by Cretoriani** [comment]
Honestly I thought that was just a display of the default keybinds, I don't recall seeing the "secondary" item and don't remember any of them being blank like auto-moving.

Sorry for the erroneous suggestion.

**Comment by D3nnis3n** [comment]
I'll just assume that you have two GitHub Accounts given your answer is not made with the original one :D

As this suggestion has already been part of the game, I'm closing it :)

**Comment by JestinJae** [comment]
@D3nnis3n yep, sorry about that.  I didn't even realize I was signed into the other.  The other account is for "business" where as this one is my gaming identity.
