### ISSUE TITLE
[Feature Request] Make speed skills retroactive

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#137]
_From @CuAnnan on April 13, 2018 18:10_

Cancelling projects and restarting them, from a software perspective, is easier. But from a human experience perspective, makes no sense.

_Copied from original issue: StrangeLoopGames/EcoIssues#7178_

**Comment by BlazeGuy2** [comment]
_From @ecoemmeck on April 13, 2018 18:41_

I like this idea but how would the game deal with the efficiency side of it, would it just deposit the now extra materials back into a stockpile / chest or would it order more to the extent of materials given to the project.

**Comment by BlazeGuy2** [comment]
_From @CuAnnan on April 13, 2018 19:33_

I don't know. I was actually just thinking about speed because it wouldn't have to deal with "Is there room for the items you would get back".

**Comment by BlazeGuy2** [comment]
_From @ecoemmeck on April 13, 2018 20:19_

I imagine the speed side of it would be relatively easy to it implement

**Comment by BlazeGuy2** [comment]
_From @mcunha on April 13, 2018 20:37_

Maybe we could adjust the output and the speed ? I'm thinking of places where people leave standing orders [high # of items on order] with their skills so others can leverage them. Forcing everyone to go around and redo the long standing orders is tedious. If we simply adjusted speed and output, people could skill up and everyone would benefit right away. This may be more of a game balance / emergent play incentives conversation.

**Comment by D3nnis3n** [comment]
No longer applicable, stuff is calculated on each new craft.
