### ISSUE TITLE
Option: Constant music

### ISSUE THREAD

**Issue by JestinJae** [StrangeLoopGames/EcoSuggestions#1376]
It would be nice if there were an option to have constant music in the background.  They day/night music is nice, but I would like more frequent music and it could be an option so that those who only want the dynamic music would still be able to be satisfied.

**Comment by D3nnis3n** [comment]
Hello JestinJae,
the music system is newly introduced in Update 9.0 and is currently not completely implemented, both from technical perspective as well as from the the amount of tracks we have. This will become noticeably more in the future - but we do not plan to have a permanent music mode, hence I'm closing this issue.
