### ISSUE TITLE
Sometimes hard to find ore

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#138]
_From @Dreepa on April 13, 2018 15:23_

Finding ore is just based on luck

Sometimes you can get unlucky, and dig super long, without finding what you look for. This is rather boring (and annoying, as you have to always bring back 20 stone before you can continue digging, making it tedious).

Suggestion:
Add a device to the game (maybe something that you need to craft, like the soil sampler) that helps you find a specific ore/coal. Maybe something showing the general direction in which you would find the selected ore, or maybe something that has a signal-strength display, which rises when you get closer to the ore, and drops when you move away from it.

_Copied from original issue: StrangeLoopGames/EcoIssues#7176_

**Comment by BlazeGuy2** [comment]
_From @zimmah on April 16, 2018 2:36_

Maybe have the regular ore be surrounded by an amount of lower density ores.  
Currently stone and ores break into 4 pieces. So why not have some stones and ores drop into 3 ore and 1 stone, 2 ore and 2 stone or 1 ore and 3 stone?
This will help you locate ore deposits, since if you start finding low density ores, a deposit may be close.   
This could also overlap with each other (an iron deposit close to a gold deposit may have 1 gold, 1 iron and 2 stone for example).

**Comment by BlazeGuy2** [comment]
_From @PacifyerGrey on April 16, 2018 7:55_

Ore Prospector device would be really cool. But I would add a twist to it. You should have some skill learned to be able to see the data provided by this tool. This would make a miner profession so more effective as a standalone thing on high cooperation servers! And with this change you can lower ore generation in the world making it even better overall

**Comment by D3nnis3n** [comment]
We added the Mining Drill in Update 9.0 that allows you to prospect the ground for ore before digging :) Ores also got a much better distribution now.
