### ISSUE TITLE
[Idea] Option for server's & Local host's

### ISSUE THREAD

**Issue by SGZ-Creations** [StrangeLoopGames/EcoSuggestions#1399]
Hey an idea to the game. That I feel is the biggest game-braking aspect currently. that's the Storages having distance limits to them making it hard to maintain sorting + if u have a lot of piles that have to be placed further away it ends up not being found in crafting systems. So I am asking to make some option for the server admins to choose if there is going to disable all distance totally. Making it still exist but make it to ignore when both parts are inside your territory/claim. The third option as it is now basically the default. 

Please let me know if this is a thing already so I can fix it for my gameplay.

If not please post anything u would want them to add if they choose to do so

**Comment by D3nnis3n** [comment]
Hello SGZ-Creations,
unfortunately I'm going to close this issue as this suggestion will not make it into the game, out of several reasons:
1. The stockpile range is a big factor in calculations and even slight increases can have massive impact of game performance.
2. Eco does not intend you to be able to move around items through stockpiles with unlimited range, this would strongly hinder the goal of transportation via players and make a whole part of the game become a UI clicker, very opposite to what Eco is about.
3. You can already increase (though not remove) the range of stockpiles via modding, but we strongly advise against for performance and gameplay reasons.
