### ISSUE TITLE
[Industry] Pneumatic Tube Transport

### ISSUE THREAD

**Issue by karlthepagan** [StrangeLoopGames/EcoSuggestions#1400]
This is probably an architecture change, but it is motivated by real historic industrial solutions.

> The Prague pneumatic post, established in 1889, is is the world's last preserved municipal pneumatic post system. It's a system of metal tubes underneath the city center of Prague -- tubes totaling some 34 milies in length.

https://www.theatlantic.com/technology/archive/2013/08/pneumatic-tubes-a-brief-history/278604/

This is "Ender Chests the Eco way" -- two containers linked by pipes requiring mechanical power to operate. Two containers (source / sink) in the world are linked via the tech.

When the system is active putting an item in the source container moves it at a determined speed "through" the pipes to the sink container.

ENGINE INTERNALS - when active if the chunk of the sink container is not active it will need to be partially loaded.
(??? NOTE: assuming Minecraft architecture until I look)

**Comment by D3nnis3n** [comment]
Hello,
as you already remarked, this is likely out of scope of Eco.
We have already planned to introduce Conveyor Belts in the farer future for very short range transport in factory buildings only which would suit the goal way better than a pneumatic system (that I know a building that still uses it) that might be able to transport bigger stuff as well, but that being rather fricky from a scientific standpoint with Conveyor Belts being the better alternative. (I'm personally not sure what it would take to send whole industrial parts through a tube, I don't think that's as easy as sending post and light packages)

An automated transportation outside of very short range is not intended for Eco, as the manual transportation sector is a very important activity in Eco and we want that to stay like this.

I'm therefore closing this issue, as I don't see this being implemented in Eco given a better already planned alternative.
