### ISSUE TITLE
Add Rich Presence

### ISSUE THREAD

**Issue by Dave247** [StrangeLoopGames/EcoSuggestions#1415]
While I noticed the [attempt to integrate Discord game invites were likely abandoned (StrangeLoopGames/EcoIssues/issues/11415), I hope that [Rich Presence for Discord](https://discord.com/developers/docs/rich-presence/how-to) is still something that will be added at some point in the future. Something simple like showing the name of the server that is currently being played on and the current day would be enough, though it of course could be expanded to include any number of things!
The same can also be added for Steam too with it's [Enchanted Rich Presence](https://partner.steamgames.com/doc/features/enhancedrichpresence).

**Comment by redwyre** [comment]
I've added https://github.com/StrangeLoopGames/EcoIssues/issues/20946 for discord integration

**Comment by D3nnis3n** [comment]
Closing, as has been moved to issues.
