### ISSUE TITLE
Treetrunks that land on someone else's property become their property

### ISSUE THREAD

**Issue by schbrongx** [StrangeLoopGames/EcoSuggestions#1418]
When felling a tree on land owned by player A and the tree-trunk lands on land owned by player B, player A can chop the trunk but not pick up it's part, even when the chopped parts roll back to player A's land.

Steps to reproduce:
- Stand on land owned by yourself and chop a tree on that land so that it lands on someone else's property
- Chop the fallen tree into smaller pieces
- Try to pick up pieces -> not possible (working as intended)
- Roll pieces back to own land (i.e. running against them, pushing them)
- Try to pick up piece on own land -> not possible (probably not working as intended)
- 
![trying_to_pickup_on_owned_property_working_as_intended](https://user-images.githubusercontent.com/11025579/111624447-fdcbfa80-87eb-11eb-8dc0-e9a4925b757d.png)

![trying_to_pickup_on_unowned_property_NOT_working_as_intended](https://user-images.githubusercontent.com/11025579/111624449-ff95be00-87eb-11eb-82d5-f3369c81096a.png)

SLGID: slg196861

**Comment by D3nnis3n** [comment]
This does work as intended. When the tree falls, it is owned by you for anti-griefing protection as long as it does not land on someone elses property, which makes it their property. We don't have plans to change that.
