### ISSUE TITLE
Add helicopters

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoSuggestions#1423]
I was thinking about what vehicles might be cool in the game and I think helicopters might be a good choice for something to add.

They could provide some good end-game all-terrain long-range transportation. Maybe their cargo space wouldn't be too big, but you could use them for some small amount of valuable items.

Probably their main use would be to allow players to take some nicer screenshots of the world without having to get admin permissions to /fly. It would be nice to have some built-in camera or generally some option to view everything in 360 view of the helicopter without it obstucting the view for those nice aerial shots.

**Comment by LightOracle** [comment]
I can see it now. Helicopters on the city roads turned upside down. haha

**Comment by D3nnis3n** [comment]
Helicopters, as with any flying vehicles at this point are out of scope of Eco and will likely never happen, hence keeping the suggestion open would not make any sense. Even trains are not a set thing yet and they'd definitely come before any flying stuff. I'd suggest to repost that in about five years, that might be the better fitting time for this :D
