### ISSUE TITLE
Add job-specific clothes that unlock when you take a skill

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoSuggestions#1438]
Looking at https://github.com/StrangeLoopGames/EcoIssues/issues/21291 gave me a neat idea. Not sure if this is already planned, but it would be neat to have some job-specific clothes people can unlock when they take a skill. It could be similar to ONI's hats:

![image](https://user-images.githubusercontent.com/964559/113940394-3a1ec500-97b2-11eb-98e0-0ad700838026.png)

Or something more expansive that also covers full body clothing like aprons, lab clothes, wellington boots, etc.

It would be nice for tailors to make them perhaps, but maybe they could only be worn by people with a given skill? Or maybe you could have some skill-patches to display on clothes. Or they could give bonus to a given skill somehow.

One or either way, it would really be nice to have such clothes to show off what your job is on the server :).

**Comment by D3nnis3n** [comment]
Part of the clothing update is profession outfits for every profession giving them bonuses to their profession, all those are made by the tailor. As this suggestion hence is already being worked on, I'll close it.
