### ISSUE TITLE
Power grid improvements - Power Grid Extensions

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#144]
_From @ClayC90 on April 11, 2018 14:59_

In the real world, we transfer power over long distance with cables and power poles.

Having a power pole will allow for us to extend the range of our power grid easily, without placing down useless devices around where we don't need them and waste useful power.

_Copied from original issue: StrangeLoopGames/EcoIssues#7134_

**Comment by Daniel-Magulado** [comment]
Closing. Power Pole is now an existing item in Eco.
