### ISSUE TITLE
Create "ECO macros" for doing stuff like admin commands, claiming property, etc.

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoSuggestions#1443]
Setting up White Tiger from what I heard is a lot of work, would be nice to have some automation for it. Maybe it would be neat to be able to record and play back some "ECO macros" for things like admin commands ("flatten area"), claiming property ("claim property at coordinates X, name plot Y"), etc. to speed up server setup for this and similar servers.

**Comment by D3nnis3n** [comment]
That's nothing for the default game and can be dealt with with external tools, as we do.
Import / Export law is different suggestions that do already exist.
