### ISSUE TITLE
Recipes allow location of Ecko Statue to be revealed.

### ISSUE THREAD

**Issue by russnash** [StrangeLoopGames/EcoSuggestions#1447]
While creating a mod for a new skill, I included an 'Easter Egg' recipe for turning the Ecko Statue into wood, stone and fish.  However, I then noticed that by hovering over the ingredients and following the links I could use it to reveal the Ecko Statue's location.  I've removed this recipe from my mod (which thankfully hasn't been released yet), but thought that you might want to block this ability somehow so that people could not abuse it to find the Ecko Chamber location.  Client version is 0.9.2.4 beta release 156.

**Comment by D3nnis3n** [comment]
Hello russnash,
as vanilla Eco does not offer the ability to find the statue this way, we have no plans to take additional steps to hide it.
