### ISSUE TITLE
Land Claim Stakes and Papers should be combined into one

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoSuggestions#1464]
Tose two items need one another to function and neither of them degrades or is meaningfully used up like Arrows, so it really doesn't make sense to have them as separate items. You can already edit properties you own without using the Stake, and the only time they come up is when you forget to bring a Stake somewhere remote to claim an area, which is just adding frustration to the game. Might as well keep them as one item - Land Claim Stakes that you stake into the ground.

**Comment by D3nnis3n** [comment]
With Towns & Nations that is already the case, as every town will have different Land Claim Papers.
Hence closing this suggestion :)

**Comment by ThePiachu** [comment]
Sounds awesome, can't wait!
