### ISSUE TITLE
We could use executive actions triggered by a vote ("run once laws")

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoSuggestions#1473]
Executive actions are neat and all, but sometimes you don't want to give this large amount of power to an individual. Instead, it would be nice of one could trigger executive actions via the normal voting process, creating essentially "run once laws". You would probably want to define them separately in the Constitution to define who can create such laws, their voting process, etc. This would be great for say, reclaiming abandoned properties after a few slipped by some late abandoned property reclamation law, etc.

**Comment by DanielKispert** [comment]
this is what the default constitution does already. In the constitution you can set executors or proposers.
![grafik](https://user-images.githubusercontent.com/34270661/117571783-44452380-b0d0-11eb-837c-fd2bf5894de9.png)
executors can do it immediately while proposers do what you want, they can only propose a vote with the executive action being executed as a result of the vote.
![grafik](https://user-images.githubusercontent.com/34270661/117571814-66d73c80-b0d0-11eb-8dc9-05967ed00c80.png)
