### ISSUE TITLE
Add a custom demographic for a server that carries between cycles

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoSuggestions#1491]
We had a small issue on White Tiger with people taking loans and ditching the game soon after or doing something shady with the money. It would be nice to be able to create a kind of demographic that tracks well behaving and dedicated players so they can be offered bigger loans and so on. However, something like that would have to be re-created each time the server restarts, so it might be a pain to maintain, especially when some players might join later in the cycle, etc.

It would be nice to be able to import some demographics into a server via some simple list that would keep track of such players across cycles. Then you would only need to maintain one master list and whenever a player from that list would join they could be given a certain demographic / role / etc. automatically, kind of like admin / gm / etc.

**Comment by D3nnis3n** [comment]
This would mostly benefit White-Tiger and a few other servers. Our focus is on generally enhancing gameplay time to not need such workarounds that also have a lot of technical implications to make a partly persistance possible. This hence is something we're unfortunately not going to do.
