### ISSUE TITLE
Add Server configurations for pollution threasholds

### ISSUE THREAD

**Issue by Dave247** [StrangeLoopGames/EcoSuggestions#1496]
This is mainly a expansion of #228 where I think one of the easier way to give negative pollution more of an effect in the game without having to wait until new systems are introduced/reworked, is to add options that can be configured as a server settings that would allow players to easily change the threshold before the sea level and temperature rises. Possibly a multiplier would be easier to understand then setting a hard coded number, but just to have some way for players to change it as to my knowledge there is currently no way outside of someone potentially making a mod for it.

**Comment by D3nnis3n** [comment]
This actually already exists, in EcoSim.eco:
```
  "ClimateSettings": {
    "$id": "2",
    "InitialOxygenPercent": 0.0,
    "InitialNitrogenPercent": 0.04,
    "InitialCO2Percent": 0.96,
    "AirPressure": 0.006,
    "AtmosphereVolume": 1000000.0,
    "AtmosphereDisplayEnabled": false,
    "AtmosphereSizeInTons": 1000000.0,
    "PollutionMultiplier": 1.0,
    "MinCO2ppm": 325.0,
    "SeaLevelSimEnabled": true,
    "TemperatureSimEnabled": true,
    "SeaLevelsRiseAtCO2ppm": 420.0,
    "CO2ppmPerSeaLevelMeterRise": 20.0,
    "MaxSeaLevelRise": 20.0,
    "MaxTemperatureRise": 30.0,
    "MaxSeaLevelRiseRatePerDay": 1.0,
    "MaxTemperatureChangePerDay": 1.5,
    "TemperaturesRiseAtCO2ppm": 340.0,
    "CO2ppmPerDegreeTemperatureRise": 20.0,
    "MaxCO2PerDayFromAnimals": 25.0,
    "MinCO2PerDayFromPlants": -500.0,
    "PollutionPerTailingPerTick": 0.016,
    "MaxDebrisBlocks": 1.0
  },
```
