### ISSUE TITLE
Add dynamic and contextual music

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoSuggestions#1500]
After playing enough ECO you start noticing how sparse the music is. It would be nice to perhaps have someone compose a few pieces of connected music that could play based on where the player is at. I was thinking we could have:

- Music that is tied to a biome
- Music based on if the area is wild or developed

Ideally, those tracks could blend together to reflect how well developed the area is and when someone moves form biome to biome they could have the tracks fade into one another. It would probably take some effort to compose something right, but it might be a really neat feature once implemented.

**Comment by D3nnis3n** [comment]
WWise has been introduced to do exactly that, but the audio, as announced back for 9.0 isn't yet fully implemented. The full implementation will have this though, hence I'm closing this suggestion.
