### ISSUE TITLE
We need better storage stacking for tools, clothes, workstations, signs, etc.

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoSuggestions#1504]
ECO has a few different professions that have to deal with the same issue of size 1 stack items. Those would include tools (#1257), clothes (https://github.com/StrangeLoopGames/EcoIssues/issues/22031), workstations, signs, etc. I get that those items have some extra data that is carried with them, but at least until the item is used and acquires that custom data, it would be really nice if they would stack.

Similarly to #1257 , it would be ideal if the items you produce would come in some kind of "container", maybe something like an Ikea flat pack:

![image](https://user-images.githubusercontent.com/964559/120872004-2c878080-c552-11eb-8594-037dd1ba88b6.png)

That's what you produce, the items stack to 10-100 per item, and the primary sellers can hold a good stack of those items ready for sale without using 50 chests. Then when someone wants to use the item, they right-click and remove the item from the container and it functions as normal. You could then also have something like #1086 for re-packaging the items back into stacks.

This would make it so people are more willing to have like 20 signs made from every kind of wood, or a stack of 50 backpacks, rather than making them to order or storing like, 3 at a time in the store.

**Comment by D3nnis3n** [comment]
Actually, aside of clothes, these objects are not supposed to stack to begin with. We did not yet add weight to objects and in the same fashion stuff is still stackable that is not supposed to be stackable, which is pretty much everything you mentioned but clothes and potentially signs. So this suggestion actually goes in the opposite direction of what future development is going to head and as there is an issue for clothes stacking already, which is pretty much the only one where it would be viable to be stackable, I'm closing it.

I remember there to already be a suggestion for packaging in conjunction with a postal network, but can't quickly find it, so feel free to make a suggestion for that explicitly.
