### ISSUE TITLE
Add some mega-storage

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoSuggestions#1509]
In the vein of #1079 , it would be nice to have some kind of mega-storage in the game. I know Large Lumber Stockpiles have been great (and would be even greater with this fix - https://github.com/StrangeLoopGames/EcoIssues/issues/18619 ), so have Silos, and we have some larger storage for small items coming with a future update, but I'm talking something even bigger.

Basically, it would be great to have some mega-storage that would be fit for a large government or a megafactory. Something akin to these:

![image](https://user-images.githubusercontent.com/964559/121801249-42004880-cbeb-11eb-94d8-5c093f26caca.png)
![image](https://user-images.githubusercontent.com/964559/121801252-44fb3900-cbeb-11eb-8358-0ad5b9baba7f.png)

and I'm talking those as a single, placeable item. It's really a pain to juggle 20 chests, and if you want to supply people with a buttload of stuff like ore, crushed stuff, set up some large government trading hub, etc., you need more. It would really be nice to be able to plonk some storage worthy of a warehouse or a dock and be able to connect to it. Make it expensive, make it big and unwieldly, but it would be a godsend to your hardcore industrialists. They'd gladly flatten 20 claims to be able to put a giant storage up.

**Comment by D3nnis3n** [comment]
Shelves as such storage were already announced in a dev-blog about a month ago and ship containers will make their way with trailers and boats (not necessarily in the first update introducing boats, though!) as well, so this is already planned :)
