### ISSUE TITLE
Use server unique ID for favorites/history instead of IP

### ISSUE THREAD

**Issue by msgerbs** [StrangeLoopGames/EcoSuggestions#1516]
A server I play on had to change hosts, and their IP changed. As a result, the server shows offline in favorites and history, making players who were not aware of the new IP unable to join and simply thinking the server shut down. We went from 40+ concurrent active players to 6. History and favorites should use the server's unique ID to track the server so that if its IP changes players are still able to find and join it. This would prevent communities from fracturing if the server must be upgraded or moved.

**Comment by D3nnis3n** [comment]
This is already the case. I took some time to test it, and it works.

**Comment by msgerbs** [comment]
My bad, apparently the new host didn't let them import the old server ID for some reason and the admin I talked to just didn't realize.
