### ISSUE TITLE
(Suggestion) Unpredictable technology tree

### ISSUE THREAD

**Issue by m-r-Gamez** [StrangeLoopGames/EcoSuggestions#1518]
Hello... 
I was thinking that every Eco game would become even more interesting if it was impossible to predict the upcoming technologies....like there was a certain randomness on the technology tree or something like that.
I'm not sure it's even possible given all the technologies' dependencies. I guess it would be a big challenge to have a dynamic dependencies tree. And even a bigger challenge to balance all these dependencies.
But I thought it could be a nice idea and maybe it could lead to another interesting place too.

**Comment by D3nnis3n** [comment]
This would require a whole remake of the technology system to make it unpredictable and would necessarily require technologies to not be based on each other - on the other hand it would also no longer resemble a real-life like progression system. I unfortunately don't see this fitting the concept of Eco, nor the resources for such a feature, which ultimately would need to be optional, available. Hence I'm closing this suggestion.
