### ISSUE TITLE
HTTPS support & minify/uglyfy JS/CSS

### ISSUE THREAD

**Issue by bartimaeusnek** [StrangeLoopGames/EcoSuggestions#1522]
Hello,
i'd like to suggest HTTPS support for security, and the minification and/or uglyfication of Javascript and CSS for the webserver, since this would reduce traffic and is implemented quite trivial.

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoSuggestions/issues/308
