### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by QdawgS765** [StrangeLoopGames/EcoSuggestions#1530]
There should be support for mac so that I can play it, as I have a mac and this game looks like one of the best games I've ever seen, and it would be so cool if people like me could play it on a mac. Now I realize that it is very difficult to add support to a whole other OS after you've already added so much to the game but just think of how many people out there that are like me, they only have a mac and they really want to be able to play this AWESOME game that you've created and you could open this amazing game up to everyone else who agrees with me. So please, add mac support.

**Comment by Crazy-Spy** [comment]
Hey @QdawgS765 

They have MAC support...

https://play.eco/s3/release/EcoOSX_v0.9.3.6-beta.zip

Check it out the website https://play.eco/

![image](https://user-images.githubusercontent.com/67368828/127880178-021f0ce4-ba7f-4883-b667-25391d75b276.png)

**Comment by redwyre** [comment]
You can play from the site or with steam, but Mac is not officially supported so expect some bugs

**Comment by QdawgS765** [comment]
how did you get to that download page?

**Comment by redwyre** [comment]
Login and you should get redirected to https://play.eco/account

**Comment by redwyre** [comment]
Though I'd recommend using steam

**Comment by QdawgS765** [comment]
but you cant get it on steam for mac

**Comment by QdawgS765** [comment]
ok so i logged in and i did get redirected to that page but what do i do from there?

**Comment by D3nnis3n** [comment]
Mac is both available via Steam and via the website. Just click on the "Game Mac *" link to download it from the website.

**Comment by QdawgS765** [comment]
first of all it doesnt show that it works for mac on steam (see attached image) second of all how do you get to the "Game mac" link on the website?
<img width="631" alt="Screen Shot 2021-08-06 at 7 22 08 PM" src="https://user-images.githubusercontent.com/88155946/128579685-9645a473-704d-46b3-874b-7ff1da3eff3c.png">

**Comment by D3nnis3n** [comment]
Eco does not officially support Mac, but builds are available. As we do not officially support it, it's not being advertised as we don't give a guarantee on it working at all times. A support for Mac is not planned at this time.

To be able to download it on the website you need to have bought it there or you must have linked your Steam Account on which you own Eco with the website.
