### ISSUE TITLE
Byproduct goes in different stockpile

### ISSUE THREAD

**Issue by JaVolimKatarinu** [StrangeLoopGames/EcoSuggestions#1542]
Hello, 
I have a quite simple suggestion. When you are crafting some metal bars, let's say Steel or Iron, your output from the machine is the metal bar and a slag block. And you want metal bars to go in stockpile named Metal Bars, and Slag to go in Slag stockpile. Can something like that be done? Literally, the game could check for names of activated stockpiles in range, and if the name of the stockpile is the same as the name of the product or the name of the tag that product has ( Crushed Rock) it will move the product in that stockpile.

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoSuggestions/issues/1570
