### ISSUE TITLE
Train Tracks / Stations for mines automation.

### ISSUE THREAD

**Issue by Crazy-Spy** [StrangeLoopGames/EcoSuggestions#1545]
I was wondering how cool would be to have train tracks and train carts that could be automated to transport ores.
I do visualize a equipment that would be connected to the stockpile... which would load automaticaly a mine train cart that would go back and forward loading and unloading the ores. 
With that we could automate the way the mines works. 
We could focus on extract the ores and have the mine train cart to take care of bring the ores to the surface.

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoSuggestions/issues/1571
