### ISSUE TITLE
Increased land claim papers based on tier of skill

### ISSUE THREAD

**Issue by ApatheticSchizoid** [StrangeLoopGames/EcoSuggestions#1555]
I think a big problem I've been noticing is that there isn't enough land claim papers to really build cool things without needing to spawn them in and have a store setup. I think you could define the tier of skill scrolls and have them provide more per tier. Say masonry and carpentry are tier 1, so they get 5 papers. Milling, mechanics, advanced smelting are tier 2 so they get 10. Industry and such are tier 3 so they get 15.

**Comment by D3nnis3n** [comment]
Land Claim Papers in future updates will no longer be linked to skills, but distributed by the government, so this suggestion is no longer applicable to to the future game systems.
