### ISSUE TITLE
make Bank Accounts balance not visible to all players

### ISSUE THREAD

**Issue by Alteraner** [StrangeLoopGames/EcoSuggestions#1563]
Hello at all,
 we are playing ECO in a version where we use the full capabilities of the commercial and Gouvernement system. While this brings in a lot of fun, we are although facing human behaviours. Specially jealousy and envy are a big problem when it comes to the bank accounts. As everybody can see the balance of each account, this human behaviour creates a lot of pain within the players.
 
 I would like to recommend making the balance of an account not visible to all players and only to the managers or users of the bank account. Or even best would be to have it optional and each bank account manager can decide to show the balance or not.
 
 This would although reflect reality much better as i although don't know your balance on your bank account in real life. In my point of view, a simple feature, but brings in a lot of quality in gameplay. Of course, we can now discuss about Jealousy and envy, but at the end this is a human behaviour on big servers. We won't be able to change that within one game.
 
 Thanks in advance.

**Comment by D3nnis3n** [comment]
We have already debated that in the past and decided on purpose to make this visible.
Everything else would be a big hassle for taxation, calculation and people wishing to see if people actually got money for their shops.

I'm hence closing this suggestion.

**Comment by Alteraner** [comment]
@D3nnis3n, i fully understand your point and as 90% of the players are not consuming the full functionality of ECO with all its economy and governance features, your view on it is the best way to go. But there are some servers not playing ECO like Minecraft and they are playing with all these advanced features of ECO. But all players are humans with all the human "features" like jealousy and envy. We have now successfully run 15 Servers of ECO with it's a full economy and governance feature and all the time the discussion, who has more money, and all its related issues were killing the gameplay fun within the players. It's the way it is, we are all humans and we cannot work against that. Making this optional, so everybody can decide, who want's to show his balance would be an easy to build feature and gives a lot of gameplay fun back to the players who plays ECO in the way ECO was designed. 


Thanks for your support on this.

**Comment by D3nnis3n** [comment]
This has never been a problem on White-Tiger or any of the other major servers I know that use all the tools you mention, in the opposite those servers do heavily rely on the account data being publicly accessible to actually make educated decisions when using the governance features.

In general we do need to use our resources efficiently for features that fit our design, benefit a majority of players and optional features should be kept to a minimum, as each of the options need to be supported. I cannot see this being viable for this suggestion, unfortunately.

**Comment by Zocker-Kalle** [comment]
From experience I can only agree that it would be better if other players could not see the other accounts. Unfortunately, I have found that there are really disadvantages when others see my account balance.
