### ISSUE TITLE
Building Pipe Exhaust

### ISSUE THREAD

**Issue by jemmotion** [StrangeLoopGames/EcoSuggestions#1622]
Please can they add this it is so stressful seeing a hole in the roof or side of a building, especially when this game is heavily about building this seems silly not to either have a chimney block added or have the pipes go through the walls/ceilings so they clip into the wall/ceiling without being blocked/obstructed!!?? Should be an easy fix.

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoSuggestions/issues/587
