### ISSUE TITLE
Not Connecting: Asphalt white center lines

### ISSUE THREAD

**Issue by jemmotion** [StrangeLoopGames/EcoSuggestions#1625]
When you do an asphalt ramp with the center line the white line does not connect to the next descending ramp going in the opposite direction it should look like a U but instead it is a line, then a dash, and then a line like this: | _ |  Please fix
![20220329131307_1](https://user-images.githubusercontent.com/90909384/162756828-c562aff5-b029-42f2-80f3-6fa1c730a5c5.jpg)

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/17781
