### ISSUE TITLE
Item "Filtering" in storage chests and stockpiles

### ISSUE THREAD

**Issue by Assimilater** [StrangeLoopGames/EcoSuggestions#1640]
In factorio you can "filter" / reserve (keybind middle mouse click but this can be anything) a specific slot of a chest or train cargo for a specific type of item (see attached image)
![image](https://user-images.githubusercontent.com/689486/167022914-be09e7fb-7d5e-44a1-b77c-a6a0be6aa35e.png)
With the new 9.5 change, coupled with this would make shops and tables very powerful and flexible in how you set them up.

I think this could be possibly merged with #1570 but it is different enough I thought to put it in its own thread just in case for now as you have iterations off that issue

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoSuggestions/issues/1570
