### ISSUE TITLE
Video about how your round cube world works.

### ISSUE THREAD

**Issue by Catboy422** [StrangeLoopGames/EcoSuggestions#1645]
(I have also sent this message in email and on discord, sorry if you see it multiple times, not trying to spam, just wanna make sure this message gets through to someone)
People have long desired and pondered how to make Minecraft style worlds round. It is an extremely difficult problem with no clear solution. You can look up on YouTube, videos with millions of views on this issue, with the only solutions to the problem being made into small demos. Then your game came out of nowhere, solving the problem so effortlessly, and going on to make a full game out of it on top of that. I can't imagine the amount of math, brainstorming and problem solving your developers went through to get it working. It's an absolute technical marvel and I think you underestimate just how incredible of a game you've made. As far as I know you are the ONLY game to have solved this problem and be a full game on top of it as well. It's absolutely perplexing to see, you can go high up, deep underground, and it's all still blocks, the same size, yet somehow in a round world and I just can't wrap my head around it. I think you've done your game a disservice by not having this as a main, if not the primary selling point, instead marketing as educational and focusing on your environmental mechanics. You could easily create so much hype and popularity to this game simply by shouting out, "We've made a game with Minecraft styled terrain on a round world!" to the large community of people interested in that subject, no further information necessary, that's all I need to know for you to have my full attention. I would really love if you could publish a video doing a deep dive into how exactly your blocky yet round world works, how you overcame that problem, and the math you've done to make it happen. As well as the minimap/terrain gen. You don't seem to realize how cool of an accomplishment this is, and I beg you to brag about how you've achieved it, as full of yourself as you want, you deserve it for being so humble about it for so long. This is interesting enough to even write and publish a paper about in a scientific journal in my opinion. A kind of journal focusing on simulation/game design technology.

**Comment by D3nnis3n** [comment]
Mail has been answered.
