### ISSUE TITLE
Game crash stating no info

### ISSUE THREAD

**Issue by MasonBeGaming** [StrangeLoopGames/EcoSuggestions#1647]
World crashes stating not enough log info available

[Player.log](https://github.com/StrangeLoopGames/EcoSuggestions/files/8743983/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoSuggestions/files/8743984/Player-prev.log)

**Comment by D3nnis3n** [comment]
Would need the server logs, not the client ones. This is the suggestion tracker, though, hence closing, as it's not a suggestion.
