### ISSUE TITLE
Balance coal by introducing coal processing

### ISSUE THREAD

**Issue by 1ntrospect1on** [StrangeLoopGames/EcoSuggestions#1666]
Most specializations are set for the whole game if they go to a coal vein and gather 1 cart of coal in 5-10 minutes. Steelproducers are obviously an exception.

This could be solved with the "crushed coal mod" which introduces processing to coal. Similar solutions are welcome. 

Bear in mind it shouldn't make steel production too grindy, that's not the intention. Intention is making the miner a bit more useful, and coal as a resource more scarce.

**Comment by D3nnis3n** [comment]
The crushed coal "mod" is actually the in-dev version that is going to vanilla backported for White-Tiger.
So that's going to happen, hence closing this suggestion :)
