### ISSUE TITLE
Improve Animal AI with quite few changes

### ISSUE THREAD

**Issue by 1ntrospect1on** [StrangeLoopGames/EcoSuggestions#1669]
I read #1549 about improving animal behaviour, i concur and wanted to expand on that. 
Problem: It breaks immersion when 10 deers/animals is running around your town center, or even running down in your mine.

It should be quite easy to improve the AI with few changes:

Animal AI should seek to (prefer, not categorically)
- Avoid "trampled" areas
- Avoid non-natural block surfaces like hewn and mortared stone (would see less animals wandering our bridges)
- Avoid areas that have blocks above them (would basically mean avoiding houses, mines and tall structures)

Other suggestions to improve immersion/fun:
- There simply is too many animals. Decrease general animal population by say 20%, but compensate with +20% resources for carcass processing.  (Would require abit testing as to how easily the animal go extinct)

- Predators should be abit more aggressive when attacked than they are, but shy away abit more if not attacked.
(i.e the jaguar will walk right past you, then run if you attack it. Instead it should lurk in woods and defend itself when attacked)

**Comment by D3nnis3n** [comment]
All of that planned, aside of the last point, as explained in your issue about hunting :)

**Comment by 1ntrospect1on** [comment]
Great, i guess the issue can be closed then :)
