### ISSUE TITLE
Possible solution to GeForce Now Integration

### ISSUE THREAD

**Issue by gustavo-sant** [StrangeLoopGames/EcoSuggestions#1705]
Hello!

Searching for info about ECO being curated into GFN available games I came upon these topics:
https://steamcommunity.com/app/382310/discussions/0/3278067618875221354/
https://www.reddit.com/r/EcoGlobalSurvival/comments/raq8ji/geforce_now_support_please/

IF the issue is with steam cloud, a quickfix to this would be to enable Steam Cloud in a way like Space Engineers did. They only upload Blueprints made in-game and not the Saves to the cloud.

A possible simple solution would be to enable a minimal steam cloud as a dummy, like saving your game settings (such as recent servers and preferences). Since it would be a few configuration files, I believe this could be fast to implement since the testing-part would be simple, and it would be great news for all those needing GPUs with more than 2GB to run the game smoothly, helping in the way of performance updates the game has been through recently.

This would solve the issue for anyone who wants to play multiplayer, but what I've noticed too is that GFN seems to keep a persistent disk of your sessions, for Space Engineers at least, because I played for over a month with friends, hosting the game on my GFN session itself, and the save was kept there (The default "cloud" for saves SE has is uploading to Steam Workshop, and that was not needed after noticing it was persistent on the virtual machine)

**Comment by D3nnis3n** [comment]
We plan to introduce Steam Cloud in a very basic way that only copies folders over, without an integration to the game. This will allow it to work if we're able to save less backups (which we're not sure if we want to), but also cause people to get a request whenever they start the game on a different computer on which version of files they want to use. Which is the main problem, as the folder on the local PC will simply be overriden and the amount of failure that can happen here is problematic.

Our configuration files are also not per world, but per server, so syncing them can cause additional issues. If we roll out, it needs to work mainly for singleplayer, for multiplayer no Steam Cloud would be needed other than GFN requiring it.
