### ISSUE TITLE
Kelp harvesting is not affected by Gathering perk

### ISSUE THREAD

**Issue by EddEco** [StrangeLoopGames/EcoSuggestions#1706]
As per the game tooltip, and testing, it appears that the harvestable amount of Kelp is not affected by gathering perk.
I believe that this is to the detriment of the gathering perk, and it would benifit changing to effect the harvest amount.

**Comment by IcedForge** [comment]
Closed as fixed with the next hotfix (currently pending PR on staging branch) also increased max yield to 3
