### ISSUE TITLE
Mailbox system for players | Solution for different time zones

### ISSUE THREAD

**Issue by WyattParker** [StrangeLoopGames/EcoSuggestions#1711]
Not everyone uses Discord, while it would make things difficult, I think I may have came up with a solution to fix players "just missing each other" and they don't use Discord.
Mailbox. T1 could be just a wooden one, crafted out of hewn logs (if going by a Tier system) and set out in front of their house, next to the road/sidewalk, whatever.
Players can receive letters, for example custom orders, communicate to plan to be on at a specific time, etc. 

Now, those that are looking to leave a letter can write it on "paper", maybe limited uses, this also gives a benefit of giving paper another use other than just creating a bookcase. They can drop the letter into the receivers mailbox. 
Without the mailbox, players cannot receive messages. 

I know some will just say "use a public sign", in which we've all seen but sadly, you can't trust everyone. There is, and always will be that one person who lives to mess up the game for others and "edit" some ones message just to troll. This fixes it and makes sure messages are private and received.

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoSuggestions/issues/1370
