### ISSUE TITLE
Suggestion: Rework Mechanical and Electric Power Grid

### ISSUE THREAD

**Issue by maginator** [StrangeLoopGames/EcoSuggestions#1717]
Hi,

It would be very cool if Eco got away from the area system for the energy. So that for mechanical power you have gears and axles and belts with which you then connect the machines and for electrical power you have to lay cables to the machines and then you could build on that with batteries and transformers and so on.

Idk if this was allready suggested but i think this is a really cool Idear

**Comment by Sarah-Graesyn** [comment]
While I personally am a fan of seeing all the cogs and gears and such working together to make something work; I honestly don't think that Eco is the game that should use that system. It would just create too much bog and slowness when it comes to working with the industry and such when Eco already has a real time cost to the skill system and to doing well pretty much everything tbh.

**Comment by D3nnis3n** [comment]
We do have no plans for that, unfortunately. That would extend a side mechanic too much - we plan to add the need to bring electricity towards a house with a pole, but anything within would be automatically connected.
