### ISSUE TITLE
[QoL] Storages set up by a property owner are set up for all residents of the property

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoSuggestions#1718]
My wife had this idea more than I did but she looked at me in frustration as she had to individually set up her campfires after I had set them up for myself and literally said "I wish that when you set up the campfires and other workbenches that they were also set up for me since we share a property when we play this"

- Suggestion: Create a property based Worktable Storage link so that all players who have access to a property no longer have to individually set up their own storage tab once a table has been set up by the "owner" of the property.
- Addition: Create a "opt in" option where a player can still individually set up their own independent flow if they wish but the set up created by the property owner is the default when someone is granted authorization for a property.

**Comment by D3nnis3n** [comment]
We unfortunately have no plans to do that, the linking per person is working as intended.
