### ISSUE TITLE
Night / Day Cycle

### ISSUE THREAD

**Issue by Crazy-Spy** [StrangeLoopGames/EcoSuggestions#1730]
If possible enable GAMA configuration to be possible make the night "less dark"
Currently the game is awesome during the day with bright into 100% but nights are too dark.
I know that I'm not the only one that keeps switching between 100% and 300% on the brightness configuration.

Another option could be an Always Day option. Where it will be always day, even with the world time ticking as it should.

**Comment by D3nnis3n** [comment]
Such a feature is not planned, it was purposefully made darker to require light sources based on community feedback.

**Comment by GabyForester** [comment]
Hello, you can increase day duration under the tab "simulation" of your server, increase the number of day scale will make the day last longer.
This is my setting : "TimeOfDayScale": 69.0 , my day last 15 mins, and my nights last less than 5 mins, it's not really what you want but this can help ...
