### ISSUE TITLE
The most rewarding mode for those playing alone.

### ISSUE THREAD

**Issue by JonathanLemke** [StrangeLoopGames/EcoSuggestions#1732]
I'm copying here a pain I have when playing the game and I wanted to make a suggestion for improvement for those who play alone.

I just have one point for you, it's more personal and I think it will interest more people. I know that the idea of your game was to be something engaging with more people playing. But I find it very difficult to play with other people or even people around me or in my social circle. Wouldn't it be possible to create a little function that would be easier to set up or that would make the experience of advancing alone more rewarding? I've had the game for a long time and 70 hours in, I always give up playing (and always want to go back). But I never manage to play for long, the slow progression for solo play gets discouraging very quickly, because I have to wait many hours to be able to learn something on my own, even by increasing the multipliers. As long as I don't go up, I get stuck doing repetitive things that I've already achieved.

It doesn't have to be something very dedicated, it could just be a little button there that changes these parameters for those who want to play alone. I bet a lot of people love the idea of the game, but find it unfeasible to play. Because it's too time-consuming to play alone (for those who like to play with other people, it's perfect). But alone is a bit hard).

**Comment by CraigWCooper** [comment]
If it helps, you can sleep in beds to speed up time to get to your next skill points, be careful though its easy to sleep through the days and get hit with the meteor.

**Comment by D3nnis3n** [comment]
We already provide the option to sleep for single players as well as full configurability of skill progression and many other factors like resource costs and crafting times when starting a "custom" world. Hence everything you wish for is already there.

**Comment by JonathanLemke** [comment]
Thank you very much for the tips, I think you've helped a lot now. At first I had doubts about setting up the custom menu. I had forgotten that I could sleep. 

And I managed to configure the settings, but it would be nice to have one or two simple profiles for those who want to play alone :).

Also because it's a bit difficult to get a sense of how much the multipliers increase. Like comparing Miles with Kilometers and so on. They are different measures and it takes time to get used to the proportionality.

But thank you very much!

Special thanks to @CraigWCooper and @D3nnis3n.
