### ISSUE TITLE
Rather hard to judge excavator shovel interaction

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#179]
_From @Dreepa on March 27, 2018 15:20_

The excavator shovel is hard to judge: What block is exactly below it, when dropping stuff, but also how close it is to another block when mining (like when you try to only pick up stuff but not damage blocks).

Maybe a highlight of the blocks could help here? Or give the excavator a strong light source, so that the shadow of the shovel can be related to.

_Copied from original issue: StrangeLoopGames/EcoIssues#6533_

**Comment by SeanAtr0n** [comment]
Fixed w/ https://github.com/StrangeLoopGames/Eco/pull/2980
