### ISSUE TITLE
USER ISSUE: Rice

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#180]
_From @Hanumavilasumica on March 26, 2018 20:19_

**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Get some rice
2. Plant it
3. Pick it up with E

**Expected behavior:**
The rice should disappear on the field and get into my inventory or backpack.	

**Actual behavior:**
Instead it disappears completely

_Copied from original issue: StrangeLoopGames/EcoIssues#6521_

**Comment by BlazeGuy2** [comment]
_From @MarjieAVolk on March 26, 2018 20:29_

So it was a newly planted plant.  I guess baby plants don't give you anything.  Maybe they should just give 1 seed back?

**Comment by elfl0rd** [comment]
@D3nnis3n realised by restrict harvesting not-growth plants
