### ISSUE TITLE
Suggestion: Different forms of government

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#189]
_From @zEverdeen on March 22, 2018 13:39_

I think it would be interesting to let the players themselves have a vote, in an effort to choose what type of government that they would like to be ruled by.

Obviously, we start in anarchy and end up somewhere.

Maybe a republic, maybe a president, who knows? Maybe there are two parties, maybe there are four?

_Copied from original issue: StrangeLoopGames/EcoIssues#6368_

**Comment by BlazeGuy2** [comment]
_From @Huntermeign on March 22, 2018 14:54_

Laws are there to simulate this. The name is just what is used to give a general idea of how the government works. 

The only thing selecting a government would be needed for is if there were leaders in zones as opposed to worlds and even then the laws could just be used to manage certain zones making it a whole new website interface system since not every player will live in every zone

**Comment by BlazeGuy2** [comment]
_From @zEverdeen on March 22, 2018 22:56_

Huntermeign, I think you are on to something, when you think about time zones, a big BIG server, and different governments for different timezones.

When I say governments, the way decisions are made are different. Are a certain amount of votes needed? or does the acting president have a lot of power on his own?

**Comment by D3nnis3n** [comment]
Basically what the constitution in current Eco is for, to lay out a basic government type with maximum flexibility.
