### ISSUE TITLE
Property Claims per research config

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#190]
_From @xtreampb on March 21, 2018 23:26_

As a server admin I would like to configure the amount of Property Claims given to a player after researching technology.  I would like the government of the people to be able to set how many claim flags are awarded for researching.  Would also like to be able to set it via a config file so that the gov't will be able to issue claim flags how it sees fit, something like building permits.  Is it possible for a mod to hook into when a scroll was read, and remove the claim flags from the inventory?  Maybe have an admin "give" the server 500 Property Claims?

_Copied from original issue: StrangeLoopGames/EcoIssues#6353_

**Comment by D3nnis3n** [comment]
No longer applicable, as claim papers will no longer be granted by skills.
