### ISSUE TITLE
SaveFrequency default setting in Stoarge.eco issue

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#194]
_From @pamduncan on March 19, 2018 20:42_

When savefreguency in Storage.eco was changed from minutes to seconds then default amount of 60 was not adjusted.  This means that games are auto saving every minute but default.  We are seeing more and more server that have gotten to where autosaves are exceeding this time and causing db lockups, and crashes and when they crash while saving they end up missing parts of the save. (seen saved worlds isising 1 to numerous folders and unable to load)

Could the default config file be adjust to perhaps 300 seconds so that players that do not know to adjust this themselves don't have issues with it?

_Copied from original issue: StrangeLoopGames/EcoIssues#6287_

**Comment by BlazeGuy2** [comment]
_From @MarjieAVolk on March 19, 2018 20:47_

Saving shouldn't affect the db at all, that is a separate issue.  I am not sure about the crashing.

**Comment by BlazeGuy2** [comment]
_From @pamduncan on April 3, 2018 3:18_

This is not the db is
sue this is about thesave to  .eco issue that is causing game lag :)

Its a support issue we get constantly - even people with new servers experiencing lag from the start and adjust the save so the game does not save every 60 seconds and often save while still saving and causing corruptions because they don't know to change that one config setting.  This was originally supposed to happen once and hour and players wanted to save more frequently which was why you changed it to seconds.  But did not change the default in the config that was originally there.... now saving every 60 seconds instead of every 60 minutes because the frequency was adjusted.  All that needs to be changed is the default setting for savefreqency in the default Storage.eco folder

**Comment by D3nnis3n** [comment]
The default setting of saving every 60 seconds proofed to be viable, hence closing this issue.
