### ISSUE TITLE
USER ISSUE: Looking for supplies

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#197]
_From @chopperprop on March 18, 2018 5:12_

**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
When you look at ORE in the world and or get close to it to see what type it is

**Expected behavior:**
the type of ore or stone should be displayed

**Actual behavior:**
nothing happens

_Copied from original issue: StrangeLoopGames/EcoIssues#6222_

**Comment by D3nnis3n** [comment]
In Update 9.0 we added a feature that shows what block you are looking at :)
