### ISSUE TITLE
Feature Request: Powered Cart Horn

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#203]
_From @CreeperLord on March 15, 2018 1:49_

It would be nice to have a horn bound to a key such as space;

The horn would be nothing more than aesthetic / cosmetic or could "scare" animals in the area of the car

_Copied from original issue: StrangeLoopGames/EcoIssues#6074_

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoSuggestions/issues/677
