### ISSUE TITLE
Mint default auth should not be public

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#204]
_From @Thyriel on March 13, 2018 16:9_

Mint should not default to public. When you create a currency and don't change that everyone can just print money while you obviously would want to control how much currency is around

_Copied from original issue: StrangeLoopGames/EcoIssues#5997_

**Comment by BlazeGuy2** [comment]
_From @Thyriel on March 13, 2018 23:40_

We thought more that the intention behind a mint was to use it like real world currency works, so we restrict the crafting of mint to one person with a law and have the leader exlusively print money so the goverment controls how much money there is in the world. ;)
New players that actually play and not just visit the server get some starting cash then (so every new player causes basically inflation) and the tax in treasury works against this by causing deflation.

If it's public the main problem would be that you have no control over money, a huge inflation and everyone would want to skill smelting

**Comment by D3nnis3n** [comment]
We're not implementing this suggestion and keeping the mint with the same defaults as any other items as public mints are not uncommon in Eco. In case you want a private mint, please change the authorization after placing it :)
