### ISSUE TITLE
USER ISSUE: Bookshelf doesn't work

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#232]
_From @Skelun on February 26, 2018 1:8_

**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Pick a lot of materials
2. Do a lot of researchs
3. Pick even more materials
4. Make the bookshelf
5. Try to store your books in it

**Expected behavior:**
You storing your books

**Actual behavior:**
Just paperweight

_Copied from original issue: StrangeLoopGames/EcoIssues#5103_

**Comment by BlazeGuy2** [comment]
_From @MarjieAVolk on February 26, 2018 21:26_

Yeah the book shelf does not store books.  It does increase your skill point gain if you have it in your house though.

**Comment by BlazeGuy2** [comment]
_From @Skelun on February 26, 2018 22:50_

It is so incredibly frustrating I decided to make the issue on the bug session.

**Comment by BlazeGuy2** [comment]
_From @Thyriel on February 26, 2018 23:39_

I agree that the bookshelf should be able to store ALL skillbooks at once. Additionally it would be great too to use it to store scrolls generated with skillbooks and deeds.

**Comment by BlazeGuy2** [comment]
_From @MarjieAVolk on February 26, 2018 23:40_

That does sound pretty nice

**Comment by D3nnis3n** [comment]
This has been implemented quite a while ago.
