### ISSUE TITLE
REQUEST FOR X3 RATE FOR ALL CRAFT ITEMS(MODS/AUTOGEN)

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#235]
_From @JuzuYT on February 22, 2018 19:34_

Hello dear sup. Today I ran into the problem that I can not change the crafting criteria of items and recipes in one click, you need to change each file, but it's difficult for me. Could you make this configuration files and attach in the next message. With a reduced crafting time of recipes and things in x3 Rate. For example from 1 hour to 20 min. Thanks

_Copied from original issue: StrangeLoopGames/EcoIssues#4953_

**Comment by D3nnis3n** [comment]
We added a crafting time and resource multiplier that does exactly this in Update 9.0! :)
