### ISSUE TITLE
(Suggestion) Weed Pulling

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#238]
_From @Blanclour on February 21, 2018 15:53_

Currently, in order to remove grass that has grown into my field, I have to dig the dirt up, place it back down, and then re-till it. Perhaps grass can be removed from fields using a tool without having to excavate the dirt that it's grown on.

_Copied from original issue: StrangeLoopGames/EcoIssues#4903_

**Comment by BlazeGuy2** [comment]
_From @LiaungYip on February 25, 2018 1:58_

https://github.com/StrangeLoopGames/EcoIssues/issues/4185#issuecomment-368166680

**Comment by craig-jong** [comment]
We're allowing the re-hoeing of land now which will remove weeds.
