### ISSUE TITLE
(Suggestion) click and drag building

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#250]
_From @ecoemmeck on February 18, 2018 6:45_

so i was playing empyrion awhile back and their building system makes things a little easier by being able to click and drag to build with blocks so that you could build a large structure in a short amount of time 

_Copied from original issue: StrangeLoopGames/EcoIssues#4756_

**Comment by BlazeGuy2** [comment]
_From @MarjieAVolk on February 21, 2018 0:12_

You mean like drag an item out of your stockpile straight into the world?

**Comment by BlazeGuy2** [comment]
_From @ecoemmeck on February 21, 2018 4:3_

as in with the hammer in hand and carried items in the carry slot you click and drag to build a line of 10 or more depending on the block

**Comment by BlazeGuy2** [comment]
_From @MarjieAVolk on February 22, 2018 23:54_

Oooohhhh I see now.  Yeah that sounds legit.

**Comment by D3nnis3n** [comment]
We added this in Update 9.0, the hammer can now build several different shapes to make building faster :)
