### ISSUE TITLE
You don't get your barrels back

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#251]
_From @slgbex on February 18, 2018 3:6_

Just to let you know, when you use your barrels for gas or to make something. You don't get them back. This honestly doesn't follow logic since you use what is inside and not the barrels itself. So I figure I would let others know

EDIT on the post:
I just found another bug dealing with oil.

On my server, we have a line of about 10 pumps. After 4 pumps out, you can't q up anything beyond 1 oil. Like you can tell it you want 999, but it only adds 1 to the 1 q.

https://steamcommunity.com/app/382310/discussions/0/3377008022029944272/

_Copied from original issue: StrangeLoopGames/EcoIssues#4750_

**Comment by Ketrai** [comment]
Can we please get this fixed already? It makes no sense right now balance wise and logic wise. A steam truck is better to drive as it's miles cheaper once constructed...

**Comment by D3nnis3n** [comment]
In Update 9 you get 75% of the barrels back, the rest is lost due to wear and tear :)
