### ISSUE TITLE
USER ISSUE: Road Construction Skill Max Lv 3

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#252]
_From @Brianqq3 on February 18, 2018 2:30_

**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Raise skill to max level

**Expected behavior:**
Max Level should be 5 for 80% time reduction for roads. Considering the number of needed to make decent length.	

**Actual behavior:**
Max Level is 3, resulting in only 50% time reduction and 1 minute per block. Not an issue for long servers but for shorter ones it's not helpful enough to make roads viable.

_Copied from original issue: StrangeLoopGames/EcoIssues#4747_

**Comment by BlazeGuy2** [comment]
_From @Sirisma on February 18, 2018 17:28_

Roads are powerful and imho shouldn't take only 12 seconds to produce. It isn't like you can't use multiple benches anyway.

**Comment by D3nnis3n** [comment]
The skill system has since changed completely twice, hence this suggestion is no longer applicable.
