### ISSUE TITLE
USER ISSUE: Suggestion - Large Signs or Billboards bring back

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#254]
_From @midn8t on February 17, 2018 20:6_

**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
for our stores and contracts we need a large billboard to explain cost of why you selling stuff or what to do exmaple of what go on it 

Glass = cost 1 sand 1 sand = 1 stone  Glass sales = 2 credit 1 stone = 1 credit  so that people understand why we selling our buying things at what rates.
also we where using them to tell people where roads went to what stores locations where along the roads.

small signs do not have enough space for this information...

also diff colors be nice its hard to see the text when your color blind.

**Expected behavior:**

**Actual behavior:**

_Copied from original issue: StrangeLoopGames/EcoIssues#4732_

**Comment by BlazeGuy2** [comment]
_From @DiploBlock on February 17, 2018 21:14_

large signs are still in game. they are made in the sawmill. billboards would be good to bring back though

**Comment by BlazeGuy2** [comment]
_From @midn8t on February 17, 2018 22:2_

o so u dont make then at carpenter table any more.

**Comment by D3nnis3n** [comment]
There are large signs now.
