### ISSUE TITLE
[Suggestion] Adding VOIP

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#261]
_From @WildJester on February 15, 2018 13:5_

Hello, I would like to suggest adding in the future the in-game voice chat (VOIP) feature. It can be easier to communicate with other players closer to you (an admin could set the range to hear someone talking). I mean, it can be more practical than using the text chat in some situations.

_Copied from original issue: StrangeLoopGames/EcoIssues#4586_

**Comment by BlazeGuy2** [comment]
_From @ecoemmeck on February 15, 2018 13:52_

This would be nice. However most servers have discord for this function and the ability to have server info and be able to talk to each other while out of game

**Comment by BlazeGuy2** [comment]
_From @WildJester on February 15, 2018 15:45_

True. Still should be a good feature, for whoever does not use Discord hehe :).

**Comment by BlazeGuy2** [comment]
_From @MarjieAVolk on February 17, 2018 0:22_

I doubt we will support this, as there are lots of existing tools for this sort of thing.

**Comment by BlazeGuy2** [comment]
_From @KPInc425 on March 29, 2018 0:59_

Would love to see this Feature as I see massive RP potential in this game, and discord won't cut it for that. :)

**Comment by D3nnis3n** [comment]
VOIP was added to the game via Vivox already :)
