### ISSUE TITLE
[Suggestion] Districts and laws rework

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#272]
_From @Huntermeign on February 12, 2018 18:55_

Current mechanics: Districts cannot overlap. Districts and laws take a whole 24 hours to vote 

Proposed change: Districts should be able to overlap with option to either ignore or inherit parent districts laws. Laws should be added as an addendum to proposed districts to save time that could be crucial in saving the environment. 

Reasons: 
- More incentive to vote on laws that may affect area.
- Can be used to create road districts on Industrial/commercial/residential districts but can remove restrictions or can add laws to specific areas of attention without effecting entire communities because of unforeseen planning 
- Laws take too long to pass. Addendums can do both create districts and pass laws in half the time.

_Copied from original issue: StrangeLoopGames/EcoIssues#4400_

**Comment by BlazeGuy2** [comment]
_From @CompactDisc on February 12, 2018 18:57_

I agree, attaching laws to districts on creation would be a great thing to have. Halving the time that things can still go wrong.
Child-parent relations would also lower micro-management needs.

**Comment by BlazeGuy2** [comment]
_From @SeanAtr0n on February 12, 2018 19:11_

Overlapping seems unlikely, but i agree with your other points 👍 
Voting to shorten the voting window would be cool

**Comment by BlazeGuy2** [comment]
_From @Huntermeign on February 12, 2018 19:18_

I only suggest the overlapping because if there was ever an instance where the entire town planning had to be removed it would require periods of time to remove districts and reinstate new one. Perhaps instead of overlapping we have subdistricts?

**Comment by BlazeGuy2** [comment]
_From @MarjieAVolk on February 12, 2018 23:18_

You can already propose a law that both changes districts and has an action prevention clause (as you say, and addendum, if I understand the suggestion).

I would also like to revisit voting so that it is possible to reduce voting time.  The issue of course is that you don't want to allow a troll to propose a law while most people are away and then it passes before anyone sees.  Letting servers vote on what the voting time should be is one option.  Another thing that I have been hoping to do is let severs define what a 'citizen' is (Eg. like the default Citizenship law, but more customizable), and then laws can be automatically passed early if a majority of citizens have voted yes on it, etc.

**Comment by BlazeGuy2** [comment]
_From @Huntermeign on February 16, 2018 13:32_

Sorry, have been away past couple days. Whats the status on the criminal justice system as shown to be featured on the site?

https://www.strangeloopgames.com/how-the-player-run-criminal-justice-system-works-pvp/

**Comment by BlazeGuy2** [comment]
_From @MarjieAVolk on February 17, 2018 0:38_

We have not started working on it yet.

**Comment by BlazeGuy2** [comment]
_From @Huntermeign on February 17, 2018 21:7_

But is still planned?

**Comment by BlazeGuy2** [comment]
_From @MarjieAVolk on February 23, 2018 20:0_

Yes :)

**Comment by D3nnis3n** [comment]
Voting time can now be configured and districts can overlap.
