### ISSUE TITLE
Suggestion - Add recipe hewn logs to lumber

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#275]
_From @stormoffires on February 11, 2018 14:26_

as title states this would help folks out a lot in low wood/no wood areas in advancing their buildings. Can be a reduced rate due to the log already being hewn.

_Copied from original issue: StrangeLoopGames/EcoIssues#4323_

**Comment by BlazeGuy2** [comment]
_From @MarjieAVolk on February 13, 2018 3:41_

So you want to be able to cannibalize your hewn log houses after upgrading them?  Haha

**Comment by WeaselDog** [comment]
This was added in update 8
