### ISSUE TITLE
Suggestion: car jack

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoSuggestions#28]
Currently, you need deed and hammer (and unload, ofc!) if your vechicle flip.
I want a single tool, allow you to short move and flip vechicle back.
Car jack!
![39620824-26fbd142-4f95-11e8-9cc5-e40da8165051](https://user-images.githubusercontent.com/4980243/40278279-a02b8d48-5c36-11e8-8794-cb8d5bd478b3.jpg)
![39620823-26daf42c-4f95-11e8-8f77-e93266dcd584](https://user-images.githubusercontent.com/4980243/40278280-a04b4cc8-5c36-11e8-86d7-80133b530f2c.jpg)

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/7580

**Comment by AntimatterMemes** [comment]
this would be great, for when that time an angry Elk knocks your truck full of stone off the road....
