### ISSUE TITLE
Suggestion: Add WoodPulpItem as fuel to campfire/stone brazier

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#280]
_From @stormoffires on February 10, 2018 12:44_

pretty straight forward. most server already do this change for their people.

i have included the changed files as examples
[woodpulpfuel.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1713373/woodpulpfuel.zip)

_Copied from original issue: StrangeLoopGames/EcoIssues#4243_

**Comment by D3nnis3n** [comment]
Implemented in the meanwhile.
