### ISSUE TITLE
Laws: Import/export law via string

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#284]
_From @MarjieAVolk on February 8, 2018 2:54_

So picture this, I create a law on my server and my friend wants to use it on their server.  So I go into my law window and click like 'copy', which puts a string on my clipboard, which I can give to my friend.  Then my friend goes to their server, clicks Propose Law, and on the web site there's like an Import Law button or something, that brings up a box I can paste this string into, which will update my law draft to match the other law draft.

I think it will make sense to have this be on both the web site and the game client, but the server can handle all the packing/unpacking of law proposal to string.

_Copied from original issue: StrangeLoopGames/EcoIssues#4090_

**Comment by BlazeGuy2** [comment]
_From @rainfarmer on May 9, 2018 0:27_

sounds cool, will get to it eventually

**Comment by MarjieAVolk** [comment]
Moving this back to issues - this is a much requested feature at this point
