### ISSUE TITLE
Suggestion, QoL (Quality of Life) - excavator, skidsteer "targed" on ground. Indicate excavator bucket position.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoSuggestions#29]
Hello there! I really want small addition, to excavator and skidsteer (and future working machinery).
Target on ground, indicates this bucket position.
Like this
![39763066-d8fb2fa8-52e4-11e8-977f-78bebdbb3d91](https://user-images.githubusercontent.com/4980243/40278286-c64e4704-5c36-11e8-944a-eb95b5e40287.jpg)
Or light "spotlight" as target, if mark "unrealistical".
![39763361-9419391a-52e5-11e8-88a7-ee57d516064d](https://user-images.githubusercontent.com/4980243/40278289-ceb3c004-5c36-11e8-9fc3-fd93b2d4b2a8.jpg)

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/7629

**Comment by SeanAtr0n** [comment]
Fixed with https://github.com/StrangeLoopGames/Eco/pull/2980

**Comment by elfl0rd** [comment]
hm... about https://github.com/StrangeLoopGames/EcoSuggestions/issues/29 this suggestion is not about stockpile interaction, this suggestion about bucket position - what block digs and where new block place.
