### ISSUE TITLE
Inactive Law Treatment

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoSuggestions#306]
Laws need some condition on inactivity for example, to remove coin and plots from inactive players when the law is passed.

**Comment by MarjieAVolk** [comment]
Actually you can do this with the changes in https://github.com/StrangeLoopGames/Eco/pull/2877 now.  What you will want to do is something like 'Every 0.5 days, for each player, if your Play hours where (time performed (days) > current time (days) - 2) = 0, tax 5 dollars'

**Comment by MarjieAVolk** [comment]
What we don't have thought is a way to unclaim their property.

**Comment by D3nnis3n** [comment]
Implemented.
