### ISSUE TITLE
Suggestion: block to close pipes hole.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoSuggestions#31]
Hello! Please add full block, with pipe connectors.
To close holes on wall.
![38378835-9140a7c0-3907-11e8-8fd6-6e9fb73f2a04](https://user-images.githubusercontent.com/4980243/40278296-084bd6bc-5c37-11e8-8211-c110a0f3ce6c.jpg)

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/7000

**Comment by D3nnis3n** [comment]
Not my decision to make, unfortunately.

**Comment by peternightingale** [comment]
What about this as a possible solution:

pipes can be placed as different kind of blocks, like building materials. So you would hold down shift and select a roof block, wall block, etc. and the model could essentially have a plate that covers the hole in the wall, roof, etc. that you have to make for the pipe to pass through. If not passing through something, it could be placed as a regular pipe.

This would not help with water, though...
