### ISSUE TITLE
Idea: List/Graph of Player's Professions

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#313]
_From @MasterWhoMW on January 20, 2018 18:12_

Like the title says, Have a chart or graph to list what players are profession-wise. That way, when a new player logs on, they can see if a world has 256 Carpenters and 0 Hunters, and won't waste the point on going to carpenter.

_Copied from original issue: StrangeLoopGames/EcoIssues#3547_

**Comment by D3nnis3n** [comment]
We do have that now.
