### ISSUE TITLE
Why can't Road Tool still be called Road Tamper?

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#318]
_From @MarjieAVolk on January 18, 2018 23:33_

'Road Tool' sounds less cool and less finished to me

_Copied from original issue: StrangeLoopGames/EcoIssues#3508_

**Comment by BlazeGuy2** [comment]
_From @Nanders on January 18, 2018 23:41_

Used to be called this, but was changed - iirc - due to worry that people wouldn't know what a tamper was.

I think it should be called Road Tamper

**Comment by BlazeGuy2** [comment]
_From @MarjieAVolk on January 18, 2018 23:51_

I think so too.  IMO even if you don't know the word Tamper, you can guess pretty well because of the word Road.  And you will learn some vocabulary, very educational :P

**Comment by BlazeGuy2** [comment]
_From @MarjieAVolk on January 18, 2018 23:58_

oh you seem to be right.  Look how educational this is!

**Comment by D3nnis3n** [comment]
Not worth of an suggestion.
