### ISSUE TITLE
[Suggestion] Soil Sampler allowed to be crafted with no skills

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#319]
_From @Conchipedia on January 15, 2018 21:46_

Reason for this, some people will be planting gathered seeds, and seeing as we can make and repair all basic tools now under the Survivalist Skill, it would be nice to it have so players can inspect land to see when a plant is ready to be harvested (as often a plant looks full grown but isnt until it is checked), also if someone is smithing they will need one to check Pollution from Tailings, also handy for Players to check their own land for Pollution if someone close by has stored Tailings incorrectly or causing Air Pollution.

Will also give the players an idea of how plants and land works, possibly add this to a tutorial??

_Copied from original issue: StrangeLoopGames/EcoIssues#3415_

**Comment by D3nnis3n** [comment]
We changed it so you only need to know the fertilizer skill, but don't need to learn it. Making it free for everyone wouldn't fit the intention of specializing.
