### ISSUE TITLE
Getting a shovel is still pretty confusing

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#322]
_From @MarjieAVolk on January 13, 2018 0:20_

Digging doesn't belong under Farmer.  I actually think digging should be a free specialty under Survivalist.

Also, we can have as many starting specialties as we want now, so we could split the survivalist specialty up if desired.

_Copied from original issue: StrangeLoopGames/EcoIssues#3374_

**Comment by BlazeGuy2** [comment]
_From @craig-jong on February 1, 2018 4:55_

I'm hesitant to agree with this, though I do agree the shovel is one of the more "utility" tools. Still, you don't need the skill to get a shovel, nor do you need the skill to use it.

Might consider pushing this to survival but I don't think this is medium priority.

**Comment by D3nnis3n** [comment]
Digging skill was removed.
