### ISSUE TITLE
[Enhancement] Add reputation color variable to reputation config settings in User.eco

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#335]
_From @pamduncan on December 14, 2017 19:58_

Add the variable for the color of a reputation level to the reputation section in Users.eco.  Currently it appears that rep level colors are either green or yellow - some server owners that are configuring their reputation levels to be more themed with their server would like to know if there is a way to set the color for each reputation level

_Copied from original issue: StrangeLoopGames/EcoIssues#3117_

**Comment by D3nnis3n** [comment]
Implemented.
