### ISSUE TITLE
Fallen tree not pickable on someone else's property

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#336]
_From @ClayC90 on December 12, 2017 11:37_

If I chop a tree around someone else's property and the tree decides to fall into their property,
the tree should still be chopable by me,

_Copied from original issue: StrangeLoopGames/EcoIssues#3081_

**Comment by elfl0rd** [comment]
@D3nnis3n fixed, lol, new issue from realisation of these - https://github.com/StrangeLoopGames/EcoIssues/issues/10114 :D
