### ISSUE TITLE
[Suggestion] Rails & Trains

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#345]
_From @fillion07 on November 13, 2017 17:33_

Is adding trains into Eco could be something that will add value to the game?

![image](https://user-images.githubusercontent.com/7052045/32739706-b17f342a-c86e-11e7-9d78-aa0f03d8fd7f.png)
Credit: http://traincraft-mod.com/
![image](https://user-images.githubusercontent.com/7052045/32739756-dcab4f62-c86e-11e7-9205-7c3d203a4cf9.png)
Credit: http://traincraft-mod.com/

_Copied from original issue: StrangeLoopGames/EcoIssues#2812_

**Comment by BlazeGuy2** [comment]
_From @Nanders on November 14, 2017 20:28_

Those are awesome screens

**Comment by BlazeGuy2** [comment]
_From @knexer on November 15, 2017 21:24_

What Minecraft shader mod is that?

**Comment by BlazeGuy2** [comment]
_From @fillion07 on February 13, 2018 23:56_

@knexer Traincraft ^^

**Comment by Lagicrus** [comment]
Rails would be awesome for an actual working minecart system with either the current carts or making iron carts Minecraft like which would also mirror irl

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoSuggestions/issues/1571
