### ISSUE TITLE
Citizen screen ENHANCEMENT

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#358]
_From @Dr-Hardware on November 1, 2017 6:37_

•	On the Players screen show a data column for the skill page each player has assigned the most points to (helps with choosing a specialization as a new player)

_Copied from original issue: StrangeLoopGames/EcoIssues#2686_

**Comment by D3nnis3n** [comment]
We do have a display of skills taken and which level now.
