### ISSUE TITLE
Economy Viewer ENHANCEMENT

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#359]
_From @Dr-Hardware on November 1, 2017 6:36_

•	Add filter options to Economy viewer so you don't have to sift through endless "zero stock" items, or stores that are half a world away or using a different currency - or perhaps a search akin to the adding items to a store so you can narrow your field to just what you're looking for? 

_Copied from original issue: StrangeLoopGames/EcoIssues#2685_

**Comment by D3nnis3n** [comment]
Filter is implemented.
