### ISSUE TITLE
Ballast Roller tractor module

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoSuggestions#36]
Another usefull module for tractor.
Ballast Roller
Ideal to fast create dirt roads!
![rim35009_big12](https://user-images.githubusercontent.com/4980243/40581686-7e208632-6167-11e8-90be-119b834d55fd.jpg)
![tractor-and-roller-stock-photo-949501](https://user-images.githubusercontent.com/4980243/40581687-7e405bce-6167-11e8-943d-95452fc211a7.jpg)
![image1474964839dscn2184](https://user-images.githubusercontent.com/4980243/40581688-7e5e5d04-6167-11e8-98d2-f32bb167f089.JPG)

**Comment by johnkslg** [comment]
Great idea
