### ISSUE TITLE
Suggestion: Add different Input/Output Storage Links

### ISSUE THREAD

**Issue by MikeW27** [StrangeLoopGames/EcoSuggestions#38]
It would be cool to have two checkmarks for linking storages.
One for input, one for output.
For example to set the input box for ironingots in one box, but output steel to another box so a production-chain could be set up.

Mentioned also there: https://github.com/StrangeLoopGames/EcoIssues/issues/7285

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoSuggestions/issues/1570
