### ISSUE TITLE
[Suggestion] Mortared Stone color mismatch w/natural Stone 🤷

### ISSUE THREAD

**Issue by indie-kaname** [StrangeLoopGames/EcoSuggestions#395]
Ask: Mortared stone is somehow a different more purple color than the stone it was cleaved from? Perhaps we could get it in a matching grey hues palette? ...but unsure if this was a deliberate artistic choice

Rationale/Support: aesthetics and consistency I guess. I wanted to build my farmhouse on the naturally generated stone outcropping/pad in the lowlands of my map (photo attached)

![stone mismatch](https://user-images.githubusercontent.com/26205872/41137803-6103f3a4-6a9a-11e8-9ce2-3a61f83ad3c1.jpg)

**Comment by D3nnis3n** [comment]
This type of stone is legacy, therefore closing.
