### ISSUE TITLE
[Enhancement] QOL Feature: toggle in linked storage to indicate push, pull, or both ⬆⬇↕

### ISSUE THREAD

**Issue by indie-kaname** [StrangeLoopGames/EcoSuggestions#396]
**Concept:** QOL toggle indicating push/pull (diode) or bidirectional flow between two storage/crafting entities.

**Use Case:** I prefer to have crafting stations linked to my wood cart, but nearly all the stations I'd rather not have drop items to the wooden cart. My desire is to set up most crafting stations to be **pull only**. Especially relevant when I'm spamming torches since they are consumed, but don't stack. I'd like them to sit in the chest or crafting station, not end up filling my wooden cart without me noticing.

**Rationale:** Ease of use for storage systems, anti-frustration. Principle of Least Astonishment (POLA)

**Comment by PacifyerGrey** [comment]
I fully support the idea.

**Comment by FireByTrial** [comment]
same here, would love to see this implemented. commented on #654 some use cases but pretty similar to this

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoSuggestions/issues/1570
