### ISSUE TITLE
Feature: Stores that buy/sell using Treasury funds

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#406]
_From @LiaungYip on March 5, 2018 12:1_

Our server runs a number of "public service" store fronts, that operate as a public library of skill books, skill scrolls, and crafting tables.

![image](https://user-images.githubusercontent.com/2173684/36973836-366998ac-20c0-11e8-8ca2-3fb2356062ee.png)

![image](https://user-images.githubusercontent.com/2173684/36973846-418d6db2-20c0-11e8-85fe-e027792b5e61.png)

Currently, these stores have to be owned by a player, who 'bears the loss' / 'gains the profit' from running them.

It would be more in keeping with our intent if the "public service" stores could buy and sell using Treasury funds - i.e. an extra revenue stream for the Treasury (to be used for public works), or as a subsidised service (*paid for* out of Treasury funds.)

#5409 is a similar suggestion for public Contracts.

_Copied from original issue: StrangeLoopGames/EcoIssues#5410_

**Comment by LiaungYip** [comment]
@johnkslg,

> Also your currency name made me laugh and I had to google this: https://www.youtube.com/watch?v=-w3iPFl-cfI

Glad I could brighten your day.

Do the proposed features also allow contracts to be paid for out of government funds? (https://github.com/StrangeLoopGames/EcoIssues/issues/5409 .)

**Comment by MarjieAVolk** [comment]
Yes, the doc should include that also.

**Comment by D3nnis3n** [comment]
Already implemented.
