### ISSUE TITLE
Store state should be saved when they are picked up

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#407]
_From @MarjieAVolk on February 2, 2018 21:0_

Like Mints

_Copied from original issue: StrangeLoopGames/EcoIssues#3798_

**Comment by D3nnis3n** [comment]
Same for real estate desks and similar tables.

**Comment by D3nnis3n** [comment]
This has been done for nearly all objects in Update 9.0! :)
