### ISSUE TITLE
Dynamic music system?

### ISSUE THREAD

**Issue by Dave196555** [StrangeLoopGames/EcoSuggestions#413]
I personally find it annoying that the music keeps on cutting out and then restarting every time I go into a building, so I think it would be awesome to have a music system where once you walk in, the music fades out, then when you walk back outside, it fades up again at the same spot it ended when going inside. Also having different music for indoors that works the reverse (Plays only when indoors) would be cool.

**Comment by D3nnis3n** [comment]
Hello Dave196555,
thanks for your suggestion :)

In Update 9.0 we implemented a new sound system with dynamic music and lots of new sounds. Both of it will be further improved over the next few patches.

As your suggestion has been implemented, i'm closing this issue :)
