### ISSUE TITLE
Write a note to offline user

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#420]
_From @Voosle on June 15, 2018 1:54_

Sometimes it would be helpful to write a note to an offline Player that will be shown when he comes online next time. A kind of an ingame email system e.g. to coordinate work.

_Copied from original issue: StrangeLoopGames/EcoIssues#8064_

**Comment by elfl0rd** [comment]
Mmm... Have paper ingame.
Add mailboxes and using paper to write notes - better!

**Comment by indie-kaname** [comment]
#391

**Comment by CobaltEcho** [comment]
I agree, a Mailbox would be AMAZING.  An early game item, people can "create a note" sort of similar system as a contract board, but just text notes.  Go to a person's mailbox, write a note.  Check your mailbox, read notes people left you.  Owner of mailbox can delete any/all notes.  If you create a note at a Mailbox, you can remove/edit.

In reguards to paper, I think requiring an item to create a note would make it more complicated (would the note be permanent then?  How would you edit? etc).  I could see paper as a requirement to crafting a Mailbox.

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoSuggestions/issues/1711
