### ISSUE TITLE
Admin ability to full remove player from world

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoSuggestions#422]
For example where it needed.
If player with inadmissible nickname join - they saved in multiple places, currences, eg.

**Comment by Elliander** [comment]
In line with that,maybe there could also be a way for a user to leave a world voluntarily? Although I imagine that could be potentially abused. For example, you join a world - give property claim flags to a friend - and then leave world only to rejoin and repeat. There would have to be some kind of data to indicate if someone is rejoining or not, regardless of if the admin kicks them or they leave on their own. Maybe leaving puts the user on a blacklist automatically?

**Comment by D3nnis3n** [comment]
#158
