### ISSUE TITLE
Treasury + Store

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoSuggestions#425]
From @Myrhaug

I have a request for you guys.
We got a public library, instead of giving away property claim for free, we want to take payment for skill scrolls. BUT we want the world leader and/or admins to have the possibility to add Treasury as payment reciever.

When player buys skill scroll for ex. 100€, the payment goes straight into treasury.

**Comment by D3nnis3n** [comment]
Possible in 8.0
