### ISSUE TITLE
Linked Inventories / seperate check for input and outout

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoSuggestions#426]
It would be helpful to link Inventories seperate for Input and Output at tabels.

E.g. put crafted stuffed turkey to chest 1 to sell it in a store but take the bread from a nother chest 2, because there are other bread in chest 1 I want to sell as well.

**Comment by indie-kaname** [comment]
#396

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoSuggestions/issues/1570
