### ISSUE TITLE
Suggestion: Info about which Skillbook I already learned on the Researchtable

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#43]
_From @BadHarry00 on May 19, 2018 6:33_

Research Table: 
An information in the list of skill books, which I already learned. Maybe under the name of the skill book or in the tooltip.

_Copied from original issue: StrangeLoopGames/EcoIssues#7826_

**Comment by BlazeGuy2** [comment]
_From @Deantwo on May 27, 2018 8:35_

FYI: Tooltip of the skill book says it is learned.

**Comment by BlazeGuy2** [comment]
_From @BadHarry00 on May 27, 2018 17:45_

This skill was learned:
![2018-05-27 19_41_55-eco746](https://user-images.githubusercontent.com/30983485/40588985-3208d176-61e6-11e8-81fb-29bd3927907b.png)

this wasn't learned:
![2018-05-27 19_35_47-eco746](https://user-images.githubusercontent.com/30983485/40588986-42bb6d4e-61e6-11e8-82e7-f1d92815e4e1.png)

I dont see the difference.

**Comment by BlazeGuy2** [comment]
_From @Deantwo on May 28, 2018 8:47_

Oh, I guess I am thinking of the **Skill Scroll**'s tooltip.
So easiest solution would be to just copy that to the **Skill Book** too.

**Comment by D3nnis3n** [comment]
Merged with #971
