### ISSUE TITLE
A place to ask questions?

### ISSUE THREAD

**Issue by Elliander** [StrangeLoopGames/EcoSuggestions#432]
The official forum outside of Github has long been dead, but there's no place to ask questions on Github. There should be a place for simple use questions, and maybe even a FAQ list to prevent over asking certain questions. The Wiki is helpful, but only to a point.

Even the private dev forum doesn't really have a place to ask questions, just post issues, so I'm more than a little hesitant to dive into doing anything.

Since I see that suggestions now have their own category, I wonder if something similar can be for questions?

**Comment by elfl0rd** [comment]
discord :))

**Comment by Elliander** [comment]
Um... Where in Discord? For what? I know individual servers have Discord channels, but is there an official discord channel for asking technical questions about the game, either in general, or from a development perspective?

**Comment by elfl0rd** [comment]
https://discord.gg/eco
![20180628100042_1](https://user-images.githubusercontent.com/4980243/42018277-482bf40a-7aba-11e8-8d62-8df9a9935040.jpg)
Then use
#general #community-support #support channels...

**Comment by D3nnis3n** [comment]
We've got social channels, forums and discord - that should be enough.
