### ISSUE TITLE
Jetpacks, and a Fly mode with Collission

### ISSUE THREAD

**Issue by Elliander** [StrangeLoopGames/EcoSuggestions#436]
Since the game has a Fly mode for admins, I think it would be interesting if there was a craftable item that gives the same effect, but with object collision (not flying through walls) and - similarly - would be nice if the host had a fly mode where they don't fly through everything.

The jetpack could look kinda steampunkish with a giant petroleum slot sticking out, and naturally be highly polluting considering it would need to burn just to hover in place. It would really serve as one of those items that no one really should use for environmental reasons, but everyone would want to for the joyride.  It could have different speed modes, where higher speeds burn through it's fuel faster.

In line with that, it would be nice if we could have no fly zones setup by property owners and/or as passed laws. There should also be a height limit, so the average player can't just fly out of the world.

**Comment by D3nnis3n** [comment]
Hello Elliander,
thanks for your suggestion, we appreciate it :)

Unfortunately at the current time we don't think this suggestion fits the design of Eco, hence we're rejecting it for now. Please don't be disappointed about that, we unfortunately need to organise suggestions as well for an efficient process. Please feel free to post further suggestions at any time, we appreciate all of them, no matter if they make it into the game or not :)
