### ISSUE TITLE
Get rid of block 'Construction' skills or give them more purpose

### ISSUE THREAD

**Issue by nmdanny** [StrangeLoopGames/EcoSuggestions#438]
The 'Construction' skills perform a mostly cosmetic duty with no tangible gameplay benefit. 

With a minor caveat to brick aqueducts used for routing water, the default building blocks(walls and solid blocks) are enough to build rooms of any tiers, and the fancier blocks(stairs, roofs, windows, columns) don't give any gameplay advantage - making it hard to justify the acquisition of said construction skills when there are much more useful/important skills available.

Therefore, I propose one of the following

* Construction' skills will be deleted, any SP spent on them will be refunded, any player will be able to use all construction forms of building materials of any tier.
* Heavily nerf the SP required to unlock a construction skill/specialty, perhaps by using a special, cheaper SP calculation. Maybe have their SP costs constants and not affecting/affected by the number of acquired specialties.
* Get rid of construction specialties, move their skills to relevant and useful specialties.
  For example, delete the 'Wood Construction' specialty, move the 'Hewn Log Construction' and 'Lumber Construction' skills into the 'Hewing' and 'Lumber' specialties, respectively.
* Find a way to give those skills more purpose - some ideas are proposed at #378

**Comment by D3nnis3n** [comment]
Hello nmdanny,
the construction skills have been removed from the game long ago, hence your suggestion was implemented and i'm closing this issue :)
