### ISSUE TITLE
Way to extension any existing deed

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoSuggestions#439]
Hello there!
in 7.6, deed system changed.
And you no more continue selected deed.

It's bad change :( please add way to select deed to attach claimed plots to it!

It's needed for farm (multiple plots on distance from other, happines periodically, based on world generation)
It's needed for cover Point of Interest on servers
It's need to create public bridges on servers
It's need to protect public items (e.g. street lamp) from stealing.

And makes players more free!

Checkbox on deed interface like "expand this" maybe?
If checked - all new claim attached to it.
or
>I think it would be cool if the deed tool had a deed selection interface, similar to how the hammer + constructs selection works - like you hold shift to open the pull out, scroll to select the deed you want, something like that. (And the default option would be 'auto') It isn't exactly the same as the hammer though, since it doesn't involve carrying anything.

p.s.
yes, you can protect it by law, but law is not fast to edit... In active expanding process - claim is better solution!

p.p.s.
Yes, you can POSTmanage by estate desk, but this is not easy to know, and is not good to use on the fly

Based on https://github.com/StrangeLoopGames/EcoIssues/issues/8165

**Comment by elfl0rd** [comment]
![default](https://user-images.githubusercontent.com/4980243/42193052-2199af3a-7e75-11e8-82ec-e7361a096dc8.png)
Purple - wheat farms. I not want to split it :(

**Comment by elfl0rd** [comment]
another
Claim plots for trading in new desk. Terrible :(
![20180718043032_1](https://user-images.githubusercontent.com/4980243/42854473-b84c1fa0-8a44-11e8-857b-7d1bc19da216.jpg)

**Comment by Deantwo** [comment]
I believe it currently attempts to add the new plot to any adjacent claim. A highlighing of which claim the plot will be part of could be useful.

Alternatively you could have the players location help in claim selection. For example make the claim you are standing on or standing closet to determine which claim the plot is added to.

**Comment by elfl0rd** [comment]
@D3nnis3n another player interested about it, can you look? :D
