### ISSUE TITLE
Return direct barter trading

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoSuggestions#443]
It's really need in some cases.
(E.g. automated crafting, or provide items based on their components cost.
Usefull for crafters)
http://www.strangeloopgames.com/eco-blog-5-how-the-player-run-economy-works/
![storeui-1024x427](https://user-images.githubusercontent.com/4980243/42215600-a15d54cc-7ec7-11e8-9fea-6e45c7f7b80d.png)

**Comment by Deantwo** [comment]
But player credit already all for this.

Setup a store to buy logs for 10 credit, and sell hewn logs for 5 credit. That is a simple one to two ratio.

One downside with it is that you might need multiple stores if you also have multiple currencies you want to trade with.

Sadly we only have one player credit each, so you will have to mix your "1 log to 2 hewn logs" with your "2 stone to 1 mortared stone" trades.
Unless maybe: #453

**Comment by elfl0rd** [comment]
More actions, problems with goverment taxes...
Players credit is not solution (

**Comment by Deantwo** [comment]
Why is player credit even taxed.
The real-world government doesn't want a percentage of all the IOUs I give to people.

Sounds more like an issue with how simplified the trade tax system is. Maybe it should only tax minted currencies, or maybe the leader should be able to select individual currencies that should be taxed.

**Comment by elfl0rd** [comment]
Bartering is much easier to understand than using an intermediate currency

**Comment by elfl0rd** [comment]
I like your suggestions too, but more trading option - make players more free.

**Comment by elfl0rd** [comment]
And additional note, using currency as a layer - require create and place multiple stores.
e.g.
one for log to hewn log
one to log to tools

You can not hardcode "one log+one stone = one tool"

**Comment by Deantwo** [comment]
Another fun way of doing this would be to improving contracts. Allow us to give items using contracts, so we can make contracts like; "put items in container, and take product when it is done crafting".
