### ISSUE TITLE
In/Out Inventories

### ISSUE THREAD

**Issue by LittleTahoma** [StrangeLoopGames/EcoSuggestions#449]
When dealing with large closely placed inventory storage, it would be great to be able to choose the in put and out put inventories. For example: I have a cart that I use to carry stone to the station, but if I leave it in range it will then be filled with mortared walls and I don't want that. I need it linked for input, but I want it to remain empty.

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoSuggestions/issues/1570
