### ISSUE TITLE
Electricity improvement!

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoSuggestions#451]
Hello there!
Currently, you can steal electricity from other player. Easy.
And another problem, you need place lot of electricity objects (e.g lamps) to make electricity line.

But...
Ingame - Transmission pole!
Please add it to crafting. It's answer to creating lines problem.
Steal electricity? Make Transmission pole configurable, to allow\restrict other users connect to electricity network.
And ofc! Sell and Buy electricity trough it!
![20180711042534_1](https://user-images.githubusercontent.com/4980243/42545885-24f7cf96-84c3-11e8-8fd4-e8f29c6c0e82.jpg)

**Comment by D3nnis3n** [comment]
Oh one can steal electricity? So i could make a global net already but without them paying? Could be financed by taxes.
