### ISSUE TITLE
CO2 Time Slot Laws Conditions

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoSuggestions#455]
An easy way to limit the amount of air pollution a player can make at once, and actively make the crafting stations that go over that limit pause.

A way to limit the amount of CO2 a player can emit per second/minute/hour/day would be useful.
To make it easier for law creation, maybe a "amount of CO2 emitted this second/minute/hour/day" law condition would be more the best way to make it.
```
When player emit CO2:
    If ( amount of CO2 emitted this day > 200 )
        Then prevent
    Otherwise allow
```
Branched idea from: https://github.com/StrangeLoopGames/EcoIssues/issues/8431

**Comment by elfl0rd** [comment]
Prevent what?
E.g. driving?  :D

**Comment by Deantwo** [comment]
Yes that too. 😆 

Could always add a where condition to not prevent it if it is a vehicle.

**Comment by Deantwo** [comment]
I have gotten better with laws since I posted this.
This is already somewhat possible. And this suggestion is too specific to make sense.
