### ISSUE TITLE
Campsite

### ISSUE THREAD

**Issue by ghost** [StrangeLoopGames/EcoSuggestions#479]
This is a suggestion for the campsites. With campfires only able to be crafted at the campsite now, these are kind of important. I have been playing for a little while, so I had a campfire at one point, but gave it to someone else who used it more. I need one now though, and can't craft it, because established players did not receive campsites when the patch went live. So please, either give all players a campsite, or make campfires able to be crafted at a station that we *can* craft

**Comment by D3nnis3n** [comment]
Given the patch that changed this behaviour has been over two years ago this should be a non-issue today.
