### ISSUE TITLE
Hard to kill Hares

### ISSUE THREAD

**Issue by Ruthgar** [StrangeLoopGames/EcoSuggestions#482]
It`s a pain to fulfill butchery skill book requirements. Hares is very hard to hunt down. They rendering distance is lower than other species and they at my opinion do not respect Predatory Instincts skill.
I`m usually must spend 2-3 real time hours to kill 4 Hares... Every time you see it - it runs away due to low appearing distance.They fast and sneaky, please change rendering distance or check Predatory skill is applied.

**Comment by Nicolausi113** [comment]
That's also my experience. They vanish in a short distance and has nothing to do with View Distance.

Should we move this to Issues not Suggestion?

**Comment by keegan-o** [comment]
Considering this a bug, about to fix and there is already a bug open for it.
