### ISSUE TITLE
issue: server crashing

### ISSUE THREAD

**Issue by greengoseven** [StrangeLoopGames/EcoSuggestions#485]
**was crashing a lot. first when trying to zoom in on map, then map failed altogether, then finally the program refused to load.  I finally managed to delete the game and reload, but somehow it is recognizing my setup which is why i suspect I didn't get everything, which is why the totally new installment map crashed when the game opens it up at the beginning.  I use an old 64 bit quad core, so I am wondering if it is just overwhelmed? **

**Comment by elfl0rd** [comment]
@D3nnis3n not suggestion :D
