### ISSUE TITLE
[Modding] Add OnPropertyUnclaimed

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#49]
_From @ClayC90 on May 14, 2018 11:21_

We already have access to OnPropertyClaimed in PropertyManager, please add the opposing event of OnPropertyUnclaimed.

Thanks,

_Copied from original issue: StrangeLoopGames/EcoIssues#7761_

**Comment by elfl0rd** [comment]
@D3nnis3n unclaim action added as law parameter.
