### ISSUE TITLE
Tailings suggestion

### ISSUE THREAD

**Issue by Boldee** [StrangeLoopGames/EcoSuggestions#493]
Firstly let me say I have no problem with tailings being produced it is part of the process of smelting ores however I do feel that one tailing per ingot from the blast furnace with skills at full efficiency is ridiculous. I think the production of tailings should be skills based with the blast furnace, so when max efficiency for example ten ingots would produce one or two tailings and no more. Being an engineer by trade I can safely say that skill level and experience cuts down on waste no matter what the process.

I run a private server that a few friends and I play on and we have made approximately one thousand ingots the vast majority in the blast furnace at max efficiency and we have eight stockpiles in our tailings vault full to the brim. All of this just to make tier one and two machines and we are still using steam as our main source of power just reaching oil production, we seem to spend a inordinate amount of time hacking out more space for our tailings vault.

It would also be very helpful if the stack size was increased to 10 from 5 to avoid the never ending tailings vault excavations we currently have with so many being produced for so little gain.

**Comment by Nicolausi113** [comment]
I’m missing an intelligent and useful recycling, maybe an ingredient for concrete, burn it to potassium or use for fertilizer production.

**Comment by Boldee** [comment]
I see recycling is in the road map but what they are planning with that is still a little vague.

**Comment by elfl0rd** [comment]
reported, fixed!
https://github.com/StrangeLoopGames/EcoIssues/issues/8947#issuecomment-415887712

**Comment by D3nnis3n** [comment]
Fixed long ago.
