### ISSUE TITLE
USER ISSUE: Elevator

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#497]
_From @EiKiDa on August 10, 2018 10:48_

**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
---

**Expected behavior:**
If there is a "normal" elevator, there should be one for vehicles too.

**Actual behavior:**
There is just one type of elevator.

_Copied from original issue: StrangeLoopGames/EcoIssues#8933_

**Comment by BlazeGuy2** [comment]
_From @elfl0rd on August 10, 2018 17:5_

This is not issue, place for suggestions here - https://github.com/StrangeLoopGames/EcoSuggestions

**Comment by D3nnis3n** [comment]
There is now a industrial elevator.
