### ISSUE TITLE
[Suggestion] Illness

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#50]
_From @GophTheGreat on May 13, 2018 21:56_

From the support queue:

Hey, im a brazilian fan in love with your game and thinking about the possibility of introducing some kind of illness to the game, not something really complex just a few health problems capable to prejudice you somehow, like low stamina for example until you find a recipe or some cure. A good ideia delivering all this is bringing to the game some animals like rats, that players would try to eradicate for health. Thank you guys, this game is awesome !!!

_Copied from original issue: StrangeLoopGames/EcoIssues#7754_

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoSuggestions/issues/1567
