### ISSUE TITLE
tree disappearing

### ISSUE THREAD

**Issue by papakonnekt** [StrangeLoopGames/EcoSuggestions#500]
when i spam e, while the tree is on the ground and im chopping it into smaller pieces (to auto pick up the smaller pieces,) the tree completely vanishes.

**Comment by SeanAtr0n** [comment]
your log file might be useful if you haven't restarted the game since it happened... could you upload it? (paste this into explorer to find it)

`%APPDATA%\..\LocalLow\Strange Loop Games\ECO`

**Comment by elfl0rd** [comment]
@D3nnis3n can be closed, not suggestion, reported issue - https://github.com/StrangeLoopGames/EcoIssues/issues/8823
