### ISSUE TITLE
Add a way to pay people for placing ramps out of the treasury.

### ISSUE THREAD

**Issue by matta22** [StrangeLoopGames/EcoSuggestions#501]
Our server passed a law that made "public roads" district where you were paid for placing road blocks in a certain district on the map , worked VERY well except you couldnt pay people for placing ramps. ive been told other servers use similar laws with property claims instead of districts,  Not sure if this is an already planned addition or not as I know ramps are changing and that may be why they are missing currently from Bleeding edge, but it would definitely help "public works" out on our server if we had some way to subsidize ramps as well as road blocks. thanks for your time

**Comment by elfl0rd** [comment]
ramps moved to blocks, you can use it in laws.

**Comment by johnkslg** [comment]
Cool :)
