### ISSUE TITLE
4x4 Doors

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoSuggestions#503]
I'd love to see 4x4 doors that fit in with asphalt ramps and roads. The big ones now are 5 wide and asymmetrical which looks ugly as hell.

At least the carpenter could not yet find any, i unfortunateley can't look for them myself, i'm smith.

**Comment by elfl0rd** [comment]
ramps are revorked now, to 1x wide.

**Comment by D3nnis3n** [comment]
That indeed is even better, now street can fit exactly into a claim - great.

**Comment by elfl0rd** [comment]
but more doors is a good tho :P
