### ISSUE TITLE
Introducing Player IDs and command usage of them

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoSuggestions#504]
At the moment it's impossible to use commands on about 9/10 of my population. Most of them got special characters i can see, but not type or copy. Many have special signs, that are invisible in the game uis. Even spaces don't work in commands. Also there are some players that use names in arabic, cyrillic, japanese, korean or chinese. Those are shown, but i can not type or copy them either.

A command giving a list of players with id numbers would fix that, as in i can type /players, it lists me the online players with their ids and i can then transfer money with e.g. /pay ID,Dollars,Number.

Maybe even show the id when pressing o for all players, even offline ones.

**Comment by Deantwo** [comment]
Suggestion:
Why not just implement a simple admin user panel? Buttons on a list of usernames is easier than chat commands.

_Originally posted by @Deantwo in https://github.com/StrangeLoopGames/EcoIssues/issues/10648#issuecomment-453859440
