### ISSUE TITLE
Allow changing of laws instead of repealing

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoSuggestions#510]
We got a pretty long tax law that we need to do completeley from scratch when we just want to adjust a small number, it would be great if one could propose changes / additions / removals in clauses for a law (edit) or at least be able to copy one existing law as template for a new law as a quality of life change.

**Comment by Deantwo** [comment]
Or at least that nice import and export feature would help, so making a new copy of an existing law was easier.

**Comment by CobaltEcho** [comment]
Agree!  Holy cow if I could upvote this a million times.

https://github.com/StrangeLoopGames/EcoIssues/issues/9381

**Comment by Reyalsorik** [comment]
Law management is a large pet peeve of mine when I need to change/edit/add.
This would be very useful.

**Comment by D3nnis3n** [comment]
Laws can be copied for proposal in 9.0, fulfilling this need.
