### ISSUE TITLE
[Suggestion] Indicator showing something is already researched

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#515]
_From @NtropicZ on August 25, 2018 2:43_

Title speaks for itself. I'm playing singleplayer and want some sort of indication that research is already completed. Also, if I have a collection of research books, any of them that have been researched by me should be greyed out in some way. 

_Copied from original issue: StrangeLoopGames/EcoIssues#9074_

**Comment by BlazeGuy2** [comment]
_From @Nicolausi113 on August 25, 2018 21:30_

Suggestions should be made here:
 https://github.com/StrangeLoopGames/EcoSuggestions/issues
But we are not the only struggling on this. 
See also
 https://github.com/StrangeLoopGames/EcoSuggestions/issues/10
and
 https://github.com/StrangeLoopGames/EcoSuggestions/issues/43

**Comment by D3nnis3n** [comment]
Merged with #971
