### ISSUE TITLE
Framed Glass is much to cheap for being T4

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#517]
_From @D3nnis3n on August 26, 2018 15:36_

As of materials needed and skills needed the Framed Glass which is T4 is much too easy to make in comparison with the T3 materials Reinforced Concrete and Corrugated Steel. That makes all people just skip that and go for framed glass, as that can literally be made much earlier.

_Copied from original issue: StrangeLoopGames/EcoIssues#9085_

**Comment by D3nnis3n** [comment]
Oh well, i'm sorry. I personally consider broken balance a bug rather than a suggestion.

**Comment by D3nnis3n** [comment]
Framed Glass now requires T3 before it can be crafted which fixes this.
