### ISSUE TITLE
Law Clauses for price regulation

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoSuggestions#522]
I'd like to propose a law clause that enables you to prevent a sale if the price is above or below a given number in a law. In our case we want to use that for disallowing the sale of skill scrolls for below 500 $ as we want "Land Claim Papers" to be used in the economy with an fixed value of 100 $. When people now start giving out the scrolls for free, that will not work, as they give free claim papers. Neither can we use them in a mint at the moment. We also found out giving skill scrolls out for free does hurt the property usage very bad and people get demotivated pretty fast, because of which we now give out free food to get people started instead - e.g. that will not hurt the gameplay.

Most probably there are many other uses for this, such as regulating the market.

**Comment by MarjieAVolk** [comment]
Moved to https://github.com/StrangeLoopGames/EcoIssues/issues/9124
