### ISSUE TITLE
USER ISSUE: Electric Wall Lamps not clipping to walls

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#523]
_From @Boldee on March 5, 2018 0:27_

**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Make Electric Wall Lamp
2. Attache to narrow wall

**Expected behavior:**
Position flush to wall

**Actual behavior:**
Positions with gap from wall maintaining same distance as foundation block

_Copied from original issue: StrangeLoopGames/EcoIssues#5395_

**Comment by BlazeGuy2** [comment]
_From @MarjieAVolk on June 25, 2018 20:46_

![image](https://user-images.githubusercontent.com/23460210/41874923-2d030670-787e-11e8-985a-3f4053d4577e.png)
-- @kshood

**Comment by BlazeGuy2** [comment]
_From @metachronism on August 30, 2018 0:16_

@BlazeGuy2 can you move this to suggestions?  not a bug

**Comment by D3nnis3n** [comment]
Also happens with signs and anything else placed there.

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/15329

**Comment by beastyn** [comment]
Moved to the issues for later updates
