### ISSUE TITLE
Road Tool can ONLY be repaired by someone with Road Construction 1

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#525]
_From @Conchipedia on August 30, 2018 0:10_

![snap2542](https://user-images.githubusercontent.com/29383891/44822084-e2c71a00-abf0-11e8-9832-d820490eb99e.png)

this is a bit silly as Stone tools, Iron Tools and Steel Tools (i think the higher ones  as well) can be repaired by **ANYONE** with the Ingredients to repair an item

_Copied from original issue: StrangeLoopGames/EcoIssues#9125_

**Comment by D3nnis3n** [comment]
The road tool can be repaired by anyone in Update 9.0.
