### ISSUE TITLE
Framed Glass Door needs to be crafted at a Kiln not at a Robotic Assembly Line please

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#526]
_From @Conchipedia on August 30, 2018 2:23_

**Version:** 0.7.6.3 beta

Here are the Door Recipes and Current Location for Crafting

Door
This can be crafted at a Carpentry table and ingredients logs
![snap2562](https://user-images.githubusercontent.com/29383891/44825269-caabc680-ac01-11e8-9544-bb16940ce145.png)
![snap2569](https://user-images.githubusercontent.com/29383891/44825272-d39c9800-ac01-11e8-8055-f1ea7ab671a5.png)

Stone Door
This can be crafted at a Masonry table and ingredients Stone
![snap2561](https://user-images.githubusercontent.com/29383891/44825319-05adfa00-ac02-11e8-9f3d-79fc4d85aa05.png)
![snap2568](https://user-images.githubusercontent.com/29383891/44825326-0ba3db00-ac02-11e8-8bae-2c5af4da919d.png)

Large Lumber Door
This can be crafted at a Sawmill ingredients Lumber
![snap2564](https://user-images.githubusercontent.com/29383891/44825390-5160a380-ac02-11e8-8dd8-670bf0ae8941.png)
![snap2566](https://user-images.githubusercontent.com/29383891/44825399-5887b180-ac02-11e8-9618-029349a9f68d.png)

Large Windowed Lumber Door
This can be crafted at a Sawmill Ingredients Lumber and Glass
![snap2563](https://user-images.githubusercontent.com/29383891/44825459-97b60280-ac02-11e8-80ce-f8ab68e3cb58.png)
![snap2566](https://user-images.githubusercontent.com/29383891/44825464-9d134d00-ac02-11e8-9dbd-7114d69c9f96.png)

Framed Glass Door
You have this crafting at Robotic Assembly Line
![snap2560](https://user-images.githubusercontent.com/29383891/44825511-cd5aeb80-ac02-11e8-8764-e85ca1223125.png)
![snap2567](https://user-images.githubusercontent.com/29383891/44825518-d3e96300-ac02-11e8-8084-a8755cc0be68.png)

As you can see Framed Glass is made at a Kiln
![snap2570](https://user-images.githubusercontent.com/29383891/44825567-114df080-ac03-11e8-9c09-e2f9070868c5.png)
![snap2572](https://user-images.githubusercontent.com/29383891/44825597-3c384480-ac03-11e8-9387-e38acbe142fb.png)

and seeing as Framed Glass is a Building Block that can make Floors, Walls, Solid Block, Roof, Column, Window and Stairs with a Hammer Please can we Make this Framed Glass Door at a simple Kiln?

_Copied from original issue: StrangeLoopGames/EcoIssues#9127_

**Comment by WeaselDog** [comment]
We have moved both Framed Glass and Framed Glass Door to the Electric Machinist Table.  We found Kiln was too early for T4, while Robotic Assembly Line was too late.
