### ISSUE TITLE
SolarPanels wrongly named and produce electricity while night

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#527]
_From @D3nnis3n on August 29, 2018 22:26_

Two issues:
1. The Solar Generator is only called like that in it's recipe and when you make it in the Electronics Assembly, afterwards you get "SolarPanels". You can't link the word Solar Generator, Solar Generators, Solar Panel or Solar Panels to it, like you can with all other items in the game.
2. The Solar generator seems to produce electricity at night, which just seems very wrong.

_Copied from original issue: StrangeLoopGames/EcoIssues#9123_

**Comment by D3nnis3n** [comment]
Fixed.
