### ISSUE TITLE
Contracts/trades payed by Treasury

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#528]
_From @hamisoulseeker on August 23, 2018 16:38_

Hi!

It would be greate if the worldleader would be able to set up stores that trade with the treasury money. Also the worldleader should have the possibility to choose between private pocket and treasury if he buys stuff or adds contracts.

_Copied from original issue: StrangeLoopGames/EcoIssues#9055_

**Comment by D3nnis3n** [comment]
Implemented in 8.0
