### ISSUE TITLE
0.7.6.3 Server Crashing

### ISSUE THREAD

**Issue by fjamieson** [StrangeLoopGames/EcoSuggestions#530]
Trying to get  a server up and running using the 0.7.6.3.beta files.  It keeps crashing and generating dump logs

Ecxtract:
--BEGIN DUMP--
Dump Time
08/30/2018 17:42:17

Exception
Exception: Exception
Message:Error in Deed at 28: The type or namespace name 'DeedItem' could not be found (are you missing a using directive or an assembly reference?) (CS0246)
Error in Deed at 34: The type or namespace name 'DeedItem' could not be found (are you missing a using directive or an assembly reference?) (CS0246)
Error in BasicCrafting at 26: The best overloaded method match for 'Eco.Shared.Localization.Localizer.Do(System.FormattableString, params string[])' has some invalid arguments (CS1502)
Error in BasicCrafting at 26: Argument 1: cannot convert from 'string' to 'System.FormattableString' (CS1503)
Error in BasicCraftingEfficiency at 26: The best overloaded method match for 'Eco.Shared.Localization.Localizer.Do(System.FormattableString, params string[])' has some invalid arguments (CS1502)
Error in BasicCraftingEfficiency at 26: Argument 1: cannot convert from 'string' to 'System.FormattableString' (CS1503)

Running on Windows 2016 Server wit .NET 4.6.2 installed.. 

Any ideas what is causing this?

**Comment by ClayC90** [comment]
I am assuming, that this issue was being thrown because the mods directory was not properly installed, therefore this ticket should be closed.
