### ISSUE TITLE
Law Clause or setting for global currency

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoSuggestions#533]
I'd like to have something to change the default currency when placing new objects that use it, players very often forget to set their currency to the global backed currency.

**Comment by Conchipedia** [comment]
maybe not change it automatically but have something like a pop-up window to remind you that you are still using Player credit would you like to change to (and then show a list of available created Currencies)

**Comment by D3nnis3n** [comment]
Already implemented.
