### ISSUE TITLE
[QoL] server "discord" config.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoSuggestions#535]
ideal, if it like this.
![default](https://user-images.githubusercontent.com/4980243/44938349-07ed9100-ad87-11e8-9b32-9229ae51d459.png)

**Comment by elfl0rd** [comment]
(https , ofc)

**Comment by D3nnis3n** [comment]
Its mentioned in the description but i agree anyway, as that is easier to see and understand.

**Comment by elfl0rd** [comment]
Yep, QoL - quality of life :P
