### ISSUE TITLE
Efficiency for campfire cooking overpowered

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#54]
_From @TahuW12 on May 13, 2018 6:56_

https://steamcommunity.com/sharedfiles/filedetails/?id=1384765177

_Copied from original issue: StrangeLoopGames/EcoIssues#7746_

**Comment by BlazeGuy2** [comment]
_From @Kumagor0 on May 13, 2018 7:3_

Wait till you discover butchery and advanced campfire cooking.

**Comment by D3nnis3n** [comment]
Based on old skill system, no longer applicable.
