### ISSUE TITLE
Chopping trunk of tree - suggestion

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#549]
_From @dwujcik on September 5, 2018 18:56_

When I'm chopping trunk of tree. I should have the wood.
I haven't nothing.
game v0.7.7.0

![20180905205047_1](https://user-images.githubusercontent.com/17785084/45114622-c3c70b80-b14d-11e8-9bde-06ac62b4a04c.jpg)

_Copied from original issue: StrangeLoopGames/EcoIssues#9190_

**Comment by WeaselDog** [comment]
We now receive wood pulp for clearing stumps.
