### ISSUE TITLE
Delete Game Option

### ISSUE THREAD

**Issue by Ket-SLG** [StrangeLoopGames/EcoSuggestions#550]
Can you please add a DELETE GAME option to the menu ? I don't understand why this was never an option. Most all games that save, have this option to both overwrite, and/ or delete old games.

EDIT UPDATE : A friend who saw this message just told me where I can physically delete the old saved games. But it would still be nice not to have to go out of the game to do that when you are trying to create a new game with the same name.

**Comment by Ket-SLG** [comment]
https://steamcommunity.com/app/382310/discussions/8/2590022385669518658/?tsc

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/10301
