### ISSUE TITLE
[Suggestion] Steam Server Link ?

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#56]
_From @GophTheGreat on May 11, 2018 6:1_

From Steam https://steamcommunity.com/app/382310/discussions/0/2561864094340711197/: 

Hello

I would like to add a direct Steam-link to a posting that points to my server. On click.. Steam would start Eco ( if not running ) and connect Eco to the server ip/port from link.

Should be the same as to "join friends game+server" in your Steam friends list.

Is this possible?

_Copied from original issue: StrangeLoopGames/EcoIssues#7711_

**Comment by BlazeGuy2** [comment]
_From @elfl0rd on May 11, 2018 6:14_

like as  steam://connect/ip:port

**Comment by BlazeGuy2** [comment]
_From @Nanders on May 11, 2018 19:16_

This is possible right now.

steam://rungameid/382310// -connectTo=<your servers' unique ID>

ex.
steam://rungameid/382310// -connectTo=7002578218773351703

This will connect to Stuffed Elk testing server

**Comment by BlazeGuy2** [comment]
_From @Nanders on May 11, 2018 19:17_

Really, the only thing this needs is an easy way to see your servers' unique ID

**Comment by BlazeGuy2** [comment]
_From @elfl0rd on May 11, 2018 19:17_

or way to direct connect, using ip:port :D

**Comment by swiftyspiffy** [comment]
Hey. 2.5 year bump on this. Any progress?

Thx :)

**Comment by mirasrael** [comment]
It should use Server GUID instead

**Comment by D3nnis3n** [comment]
Quick Connect has been implemented:
"eco://connect/866931c6-3be0-45d1-bcb6-d1c2a5127a3a"
