### ISSUE TITLE
Swap Alloy Smelting 1 recipes with Alloy Smelting 2 recipes

### ISSUE THREAD

**Issue by extant1** [StrangeLoopGames/EcoSuggestions#567]
![Skills](https://i.imgur.com/SRlHtFJ.png)

Alloy Smelting 1 unlocks Steel Pipe Recipe however you cannot make Steel until Alloy Smelting 2, these skills should be swapped.

**Comment by D3nnis3n** [comment]
Hello extant1,
the tech tree has since been revamped completely, hence your suggestion is no longer applicable to the current state of the game.
