### ISSUE TITLE
Wood pulp should be a low level fuel

### ISSUE THREAD

**Issue by Knigge** [StrangeLoopGames/EcoSuggestions#568]
Wood pulp should be able to be burnt as a low tier fuel in objects deemed fitting. Both to encourage the removal of wood pulp, which is to costly caloriewise at the moment, and to function as a sink for this item. The most important part however is to have viable fuel for both torches, campfires and even some of the more advanced fuel requiring objects.

**Comment by ClayC90** [comment]
For reference, this is exactly what has been done on CTK for several versions.

It's liked by the people and it also makes sense.

**Comment by Knigge** [comment]
> CTK

https://eco-mods.com/resources/clays-toolkit.3/ ?

**Comment by ClayC90** [comment]
Yes,
The latter link is for supporters.
