### ISSUE TITLE
Search feature

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoSuggestions#572]
I'd like to have a search feature for treasury and all other similar occurances of player lists - as it's hard to find those 5 players (even when alphabetically it takes ages and people with special signs are not really good sorted) when you got 550 registered ones.

**Comment by extant1** [comment]
It would also be nice to have a search feature on the trades tab of the economy viewer window.

**Comment by Isfirs** [comment]
I would like to add that this is viable for crafting lists.

**Comment by D3nnis3n** [comment]
Moved to https://github.com/StrangeLoopGames/EcoIssues/issues/14356
