### ISSUE TITLE
Modifier+Left Click to move entire stacks between storages.

### ISSUE THREAD

**Issue by extant1** [StrangeLoopGames/EcoSuggestions#574]
Assuming the opened inventory of an object is the 'primary storage', using the modifier+left click will move an entire stack so the player does not need to drag it.

![Example](https://i.imgur.com/yNwZcAK.png)

**Comment by Nicolausi113** [comment]
How to move it down to a lower inventory?

**Comment by extant1** [comment]
> How to move it down to a lower inventory?

I suppose the only logical way to do it is that it moves into the first inventory and if that's full move it into the next available one.

**Comment by glajsnake** [comment]
Big +1 on this suggestion.

**Comment by D3nnis3n** [comment]
Already implemented.
