### ISSUE TITLE
Button to unlink all inventories

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoSuggestions#577]
Button in storage menu like collapse all to toggle all links at once,
or a marker in main menu enable/disable automatically linked inventories.
Automatic linking terrifies me.

**Comment by ClayC90** [comment]
as opposite to that, a button to enable all links.

**Comment by Nicolausi113** [comment]
… I should be more precise, not a button to toggle all but to switch all ON/OFF. If one is more experienced with ECO, quickly it looks like this – and where has my object now disappeared to?
![link2](https://user-images.githubusercontent.com/38510829/46819340-c8ea2c80-cd83-11e8-8b56-250332bc33ea.jpg)
