### ISSUE TITLE
Law Clause: Prevent using currency

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoSuggestions#579]
I want a law clause that enables me to prevent trading with a specific currency outside of a district or to enforce the use of a specific currency. E.g. i want to ban all Player Credits and on top want to limit the use of "Ration Stamps" to the Federal Bank Property.

**Comment by D3nnis3n** [comment]
Also add the price clause for Minimum and maxiumum prices and taxing above
or below. :D

MarjieAVolk <notifications@github.com> schrieb am Mo., 17. Sep. 2018, 19:26:

**Comment by MarjieAVolk** [comment]
I'm going to move this over to bugs: https://github.com/StrangeLoopGames/EcoIssues/issues/9412
