### ISSUE TITLE
Law Action: "End Term" and "Start Election"

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoSuggestions#596]
I want to be able to make a law resembling kind of the status of the US President.

I want the leader to have a term of 7 days, being reelectable once (both is possible already), get a wage (possible with "if leader clause" probably in next patch, have a presidents mansions (hopefully possible with the government property next patch) and for this to work i also want the leader to be expelled automatically after his 7 days term, when he reached his limit OR automatically start a new election with the president in office being in automatically as long as he does not retreat. This would both be possible if i had the actions "end term" that removes the world leader from the office and "start election" action that starts a new election and adds the current leader to the election automatically.

**Comment by johnkslg** [comment]
will do.

**Comment by D3nnis3n** [comment]
Possible in 9.0.
