### ISSUE TITLE
Law Clauses for greater possibilities in how the government works

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoSuggestions#599]
I read here https://www.strangeloopgames.com/how-player-created-laws-work/ that it was planned (or even implemented in a early version i did never play) to have possibilities to set the form of government by laws. For the moment, without multiple elected or instated government officials (#598) or using specific players (#597), as well as restricting voting to residents of specific districts (also for specific government positions, e.g. Representative from California, Representative from Alabama) https://github.com/StrangeLoopGames/EcoSuggestions/issues/514 as well as the missing of "Executive Orders" [e.g. limited law creating possibility for specific government officials and the use of some commands like /fine or /unclaim as in the comments of this issue: StrangeLoopGames/EcoIssues/issues/9059 and the possibility to restrict the law making for specific people to specific clauses
there is no possibility yet to do this:
- Absolute Monarchy / Dictatorship
- Representative Democracy
- Technocracy (e.g. demographics farmers which is efficiency > 4 in gathering are allowed to vote on things that is their matter, e.g. limits on crops - smiths may vote on tailings instead, but not on crops)

Would like to see this expanded :)

**Comment by johnkslg** [comment]
👍 👍 👍 👍

**Comment by msgerbs** [comment]
Definitely would like to see this. It would make the government a lot more interesting. Also would be good to make the government an entity with the same capabilities as a player: Own land, own money, own objects, create contracts, perform actions (authorized person performs actions on behalf of the government), etc. Maybe even could have *multiple* governments.

**Comment by Deantwo** [comment]
@msgerbs, most of those this are already implemented in source I believe. It was mentioned in #codestream some time back, so it will likely be in either v7.8 or v8.0 hopefully.

**Comment by D3nnis3n** [comment]
Possible in 9.0.
