### ISSUE TITLE
Room value calculation bug

### ISSUE THREAD

**Issue by tea** [StrangeLoopGames/EcoSuggestions#600]
To be more precise, sometimes furniture doesn't get accounted in room value. I couldn't figure out any specific pattern to it - I'd place one piece of furniture and it adds to the value, I put another and it doesn't. Fiddling around with adding and removing various furniture sometimes helps to work this around. Sometimes it doesn't; in any case, this is quite annoying. On this screenshot you can see small table and a chair are accounted for while table and brazier aren't, even though they are placed in the same room:
![roombug](https://user-images.githubusercontent.com/70251/46026932-33993800-c0f5-11e8-921d-b8342182aa19.png)
I took this right after removing and replacing the table. You can see log messages about "updated" - though wrong - skill value.
I can't remember having this trouble in multiplayer games so it might be limited to singleplayer. Maybe not and I got lucky or forgot it.

It is also worth noting that a) value in the tooltip doesn't match value in the HUD and b) value differential in the log is also wrong but matches difference between these two values.

**Comment by tea** [comment]
Also sorry for a) posting in a wrong tracker - misread README, totally dumb of me and b) not mentioning Eco version - 0.7.7.2, current Steam version

**Comment by elfl0rd** [comment]
@D3nnis3n can you close it as not suggestion? :D
