### ISSUE TITLE
Ability to view Districts on world map

### ISSUE THREAD

**Issue by CobaltEcho** [StrangeLoopGames/EcoSuggestions#601]
PLEASE add a Districts overlay for the world map.  This could make so many things easier!

Where is the farming district?  Umm, no idea.  You have to open browser, view districts, and then try to figure out where you are and points of reference on essentially map with no details or information.  It's all very frustrating.

**Comment by D3nnis3n** [comment]
Ive spoken about this with marjie, she said that if enough players showed there interest in this it could probably get a higher priority, therefore try to get some upvotes :)

**Comment by CobaltEcho** [comment]
For real dude, spread the word!

**Comment by stupidmonkey1** [comment]
Yes - this would be amazing, plz add!

**Comment by elfl0rd** [comment]
needed!

**Comment by cmgjones** [comment]
Awsome idea need this asap !

**Comment by Deantwo** [comment]
I have wondered why this isn't already a think.

**Comment by funnybunnyofdoom** [comment]
this would make my argument for using districts as roads, and not claims a little more sustainable.

**Comment by D3nnis3n** [comment]
I'd prefer claims anyway - especially with government property and different names with sorting for every road to give easy access to build. Would never use districts for roads ;P

**Comment by CobaltEcho** [comment]
I really like using districts for the roads, personally. Or at least we do one for the main Interstate Road. And so far our law for building roads has worked out pretty well.  We also have a Market District in farming districts and Industrial districts and all kinds of stuff. I really like the district system except for the fact you can't see where it is!

**Comment by D3nnis3n** [comment]
Not going to search around on that globe where i am and try to get an exactly 5 block wide district exactly done. Also, how about roads in a district? ;P

**Comment by D3nnis3n** [comment]
Well, i can neither find where i am on a 4km² map there nor can i just place road districts there, as i can't even see if they would fit the landscape there. Time consumption for placing down the claims therefore is less for me.

**Comment by Malenkei** [comment]
I also join this option

**Comment by funnybunnyofdoom** [comment]
We actually use both claims and roads. we have an Admin road, which is a highway. This is an east and south highway that joins the main islands together. Then my district uses districts for our infrastructure. We are poor farmers so we cannot afford the land claims for a road(They _are_ craft able in my world) so districts allow us to more easily and quickly place the roads without having to "admin" them in. 

The main drawback is that it takes 24 hours for districts to go through. I think district votes should go into effect on default when proposed, and then be "repealed"/"removed" if they fail to pass. Waiting 24 hours to set up districts is pretty rough, especially when two other people try to re-district at the same time. It took us 4-5 days to get everyone's district laws passed.

**Comment by D3nnis3n** [comment]
Included in 9.0.
