### ISSUE TITLE
/pay should be done through UI, or at least have a confirmation

### ISSUE THREAD

**Issue by Fikule** [StrangeLoopGames/EcoSuggestions#605]
This would make it easier to pay people directly.

Also, without a confirmation, you are paying an unknown about of tax. Someone on our server lost all their money as they used pay while the tax was 500%

**Comment by johnkslg** [comment]
Did you mean....something like THIS
![image](https://user-images.githubusercontent.com/3536496/46703356-969dcb00-cbdb-11e8-99ab-c09911ca70cd.png)

Just added to 8.0 💃

**Comment by Fikule** [comment]
nice ^^
