### ISSUE TITLE
Pitcher plants and bullrush cannot survive

### ISSUE THREAD

**Issue by alexarthur94** [StrangeLoopGames/EcoSuggestions#613]
On all of the servers I've been on, pitcher plants and bullrush have died out, even with no interference. On one server, I know for a fact that the population disappeared despite no local logging and absolutely zero air or ground pollution in the area. The most extreme example was where pitcher plants started at a population of over 150, but by the end of day three or four, all of them died out even though I don't think there was activity that would have killed them. I think there may be a number in their reproduction algorithm that may need an adjustment, or otherwise their life span.

**Comment by Deantwo** [comment]
This is the suggestion tracker, use the bug tracker to report bugs.
Pam gave you the wrong link.

Here: https://github.com/StrangeLoopGames/EcoIssues/issues

**Comment by alexarthur94** [comment]
Whoops! Just moved it. :)
