### ISSUE TITLE
Suggestion: Remove that stone pile if you place a stair on stone. (See picture)

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#62]
_From @TheDevelon on May 9, 2018 13:59_

![grafik](https://user-images.githubusercontent.com/28627992/39818732-de80e1a8-53a1-11e8-865f-13e5f5acd4ca.png)

Could that stone pile removed if I place a ramp or stair on it?
Only a cosmetic suggestion. ;)

_Copied from original issue: StrangeLoopGames/EcoIssues#7651_

**Comment by D3nnis3n** [comment]
Rubble should not simply vanish by placing objects on it, so it should be picked up.
