### ISSUE TITLE
Tailings decay with the same function as garbage is created

### ISSUE THREAD

**Issue by Knigge** [StrangeLoopGames/EcoSuggestions#621]
I suggest that tailings stored in the environment should decay into dirt after a long time. 

This while releasing ground pollution as now, and also air pollution using the decay-timer function from the garbage creation from items droppped. 

This would make open pit dumps viable, but also have a huge pollution / co2 issue.

**Comment by msgerbs** [comment]
And in the real world it takes more than 2 excavators running for a day to raise sea levels. What's your point?

**Comment by D3nnis3n** [comment]
Tailings do not simply decay.
