### ISSUE TITLE
Tailings storage, disposal and processing

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoSuggestions#622]
Firstly, in real world tailings can be disposed and prepared for processing.
e.g.
http://www.tailings.info/storage/containment.htm
Fresh tailings placed to prepared territory.
To speed up the process can be watered. 
When using natural precipitation-the process takes longer.
Further drains are cleaned or discharged into the sea at great depth.
"Neutralized" tailings can be used for many purposes e.g.:
http://www.nationalslag.org/common-uses-slag
https://watershedmaterials.com/blog/2015/11/24/announcing-a-new-zero-cement-block-formula-made-with-lime-slag-and-natural-aluminosilicates
Creating roads (use instead of stone in stone road and asphalt road)
Creating building blocks (use instead of stone in bricks, reinforced concrete and maube new "foam block")
![b57b5248fd](https://user-images.githubusercontent.com/4980243/48302606-68c7e100-e50f-11e8-8f42-ef964cb69afd.jpg)

Just tailings can be stored in unprepared areas, as well losing toxicity but at the same time creating serious pollution.

So I propose to move from one type of tailings to several.
For a start.
1) Old, "hot" unprocessed tailings, spreads pollution, not used anywhere.
2) New, "aged"\"cooled" tailings, no pollution, can be used in enviroment like sand, can be processed into building blocks\materials.
3) New, "concentrated"\"heavy" tailings, small (1-5%) quantity of tailings after initial processing, spreads LOT OF pollution, not used anywhere, can be stored for more loooong time for neutralization or properly buried.

**Comment by Blanclour** [comment]
I like the idea, and I can honestly say that always burying mountains of tailings underground in a cavern that always needs to be expanded with no hope of getting rid of them is getting old.

Perhaps a way to neutralize tailings using the new water system. Fresh water must be used, and sewage is outputted. This will cause a lot of pollution until water filters can be built and used. The neutralized tailings could then be used in building materials.
