### ISSUE TITLE
Medical Profession

### ISSUE THREAD

**Issue by Xailran** [StrangeLoopGames/EcoSuggestions#630]
I would love to see a medical profession, which uses a variety of different resources to create medicine.
**Things to cure**:
Fall too far? Pushed by bison a few too many times? Get a broken leg, which causes reduced movement speed, or disables jumping. A splint or bandage of some sort is used as a consumable to heal the condition
Eat raw food? Get food poisoning, which reduces your skill point gain. Drink some medicine to cure it.
Could also possibly have diseases that randomly infect people, different diseases requiring different medicines, and having different levels of severity.
So that these conditions aren't game killers, most, if not all of them, should automatically go away over time with rest, but medicine makes them go away immediately, or at least much more quickly.

**Diseases**
While I'm sure you don't need or want me to give a list of diseases that could be in game, the consequences they'd come with, and a specific cure, I do want to talk about being able to _avoid_ diseases.
First of all, if you really don't want to be hit by the latest disease going around, or you spend a lot of time near that one person who seems to always get sick, go to a medical professional and get a vaccine! Would only work for a limited amount of time (a few days), but it has a 99% guarantee of protecting you from that particular disease.
Secondly, diseases make having a balanced diet that much more important! A healthy body will have a better immune system, and thus help to stave off those nasty illnesses.

**Making items**
The medical profession has potential to use resources from basically every other profession. The main one would obviously be farmers, buying herbs/plants to make medicine. But, a doctor might also need wood, for making a splint to treat a broken leg. Need a bandage? That will require cloth. Some specific animal tissue could be used for medicine as well, or maybe crushed iron is needed for that vaccine.
I'm not so sure about this idea, but medical professionals and engineers could work together to create prosthetics, 

**Work tables**
Mill -> for crushing plants, and getting powders for medicine/tablets
Stove -> Used for combining some ingredients into medicine
Carpenter's Table -> Making a splint
(new) Laboratory -> Late game, used to make better medicines, and unlocks vaccines, so players no longer need to visit a doc randomly upon getting sick, can just get a jab and have protection for a week.

**New additions:**
Pollution could also affect health! And the longer you spend directly next to tailings, swimming in sewage/polluted water, etc. the more exposed you would be to diseases.

**Comment by Xailran** [comment]
Could also combine with the chemist idea many people seem to have, and use particular chemicals as sterilizers for bandages, cleaning out wounds, etc.

**Comment by alexarthur94** [comment]
Personally I would prefer not to have to worry about medical issues in the game. It would be especially problematic in the early stages before medicine was researched and medical equipment was developed. And on many servers, we already have a hard time having enough players and enough SP among them to cover all the necessary professions. That's not to say I want to make the game simpler than it is; I just feel like medical problems would feel like more of an encumbrance than an enhancement personally.

**Comment by D3nnis3n** [comment]
I would love it, but considering i own a very-good visited server that has the opposite problem - not enough professions for everyone i see why alexarthur94 is sceptic on this issue.

**Comment by Ketrai** [comment]
> I would love it, but considering i own a very-good visited server that has the opposite problem - not enough professions for everyone i see why alexarthur94 is sceptic on this issue.

That's what the collaboration values are for. Dennis, I think you can also edit the scaling of skills? The only issue is, that specializations are harder to get. Otherwise you could force people into a single profession easily.

**Comment by Xailran** [comment]
I do agree that medicine would make things more complicated and harder at the start of the game, and Eco doesn't need that. I'm not sure how they would balance it honestly. Late game however, I think medicine would fill a very nice space, increasing how much people depend on each other. Currently, a cook depends just on farmers/hunters. Everyone relies on a cook though. Having another "this is essential to a full experience" specialization would balance out late game play in my opinion.

**Comment by Xailran** [comment]
And if you have lots of people on your server, MORE specializations for people to choose from is better than fewer! Would mean you have a wider variety of jobs for people to do, rather than yet another hunter (for example)

**Comment by Xailran** [comment]
> I would love it, but considering i own a very-good visited server that has the opposite problem - not enough professions for everyone i see why alexarthur94 is sceptic on this issue.

And if you have lots of people on your server, MORE specializations for people to choose from is better than fewer! Would mean you have a wider variety of jobs for people to do, rather than yet another hunter (for example)

**Comment by alexarthur94** [comment]
As Ketrai mentioned, though, you can adjust the collaboration values or limit the number of specializations each person can have to ensure that people depend on others. And to me, if you have enough active players to cover all the professions more than once, that actually adds the very real world aspect of economic competition to the game, which I think would be interesting. And the thing about the medical profession is there wouldn't be any realistic way to make it not necessary in the beginning but necessary later. Either you can get injured or sick or you can't. So instead, everyone would have crippled avatars until sometime down the line there was a doctor with the right medicine and equipment.

**Comment by karlthepagan** [comment]
Advanced medicine needs nuclear technology. Both the effects of high mSv pollution (#1394) and the benefits of medical isotopes (#1395) intersect on this topic.

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoSuggestions/issues/1567
