### ISSUE TITLE
Framework for AI agents (connect to server as clients) to improve singleplayer (or low-player) experiences.

### ISSUE THREAD

**Issue by gau-veldt** [StrangeLoopGames/EcoSuggestions#632]
It would be interesting to have a machine learning agent that could connect to the server (this game is supposed to encourage education after all) and play as a "player" to provide a "multiplayer" experience from a single player (or low-player) game - wold be easy enough to do logistically since the game already uses a server/client setup (the agent would be a special case client).

Different ML agents could be trained to play different ways (huntsmith, engineer, cook, builkder, etc) - of course the first one that decides to be a lawyer might result in world destruction ;)

NEAT (Neural Evolution of Augmented Topologies) is a solid choice and some networks could be trained separately (different tasks) and interconnected with goal choosing (using NEAT, MDP or POMDP) which network (behavior) an agent will use next.

More instersting yet would be to have all AI's and the human is just in record mode to film it

**Comment by D3nnis3n** [comment]
Hello gau-veldt,
thanks for your suggestion, we appreciate it :)

Unfortunately your suggestion feels out of scope for Eco. Eco's goal is to build a society with other human players in multiplayer, AI controlled NPCs would counteract that. Development of AI for something that contradicts what we actually want players to experience doesn't seem like a good use of resource usage for us at least in the forseeable future.
