### ISSUE TITLE
USER ISSUE: "public crafting stations" is pretty useless after removing your own benches.

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#635]
_From @elfl0rd on October 16, 2018 4:7_

**Version:** 0.7.7.2 beta
Please, remake this page onto "Available crafting stations"
And allow you to control your own production through it!
![20181016070547_1](https://user-images.githubusercontent.com/4980243/46992320-237fe180-d112-11e8-8ad2-5e96572b102b.jpg)

_Copied from original issue: StrangeLoopGames/EcoIssues#9727_

**Comment by elfl0rd** [comment]
@D3nnis3n due to this behavior changed, this ticket can be closed :P
