### ISSUE TITLE
campsite - missing "sleep"

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#636]
_From @elfl0rd on November 17, 2018 12:6_

Okay, campsite have bed, but not have ability to sleep :P 
![20181117150603_1](https://user-images.githubusercontent.com/4980243/48660878-59e6ae80-ea7a-11e8-8b14-e6368cad97da.jpg)

_Copied from original issue: StrangeLoopGames/EcoIssues#10057_

**Comment by BlazeGuy2** [comment]
_From @Deantwo on November 18, 2018 16:51_

That is actually a useful idea for singleplayer or private servers, so you don't have to use so long before you can fast-forward.

**Comment by elfl0rd** [comment]
This is not suggestion, this is issue.
