### ISSUE TITLE
major skill tree issue digging and mining

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoSuggestions#642]
these items should be moved to surival tree and not be major skill job

ditch digging and busting rocks are not a major profession. more of minor skill just like using a hammer is in the game.

**Comment by Deantwo** [comment]
I trend to take the digging speciality early on and sell mt dogging service to people needing construction help. I don't see why it is a bad thing for it to be a specialty.

If you really hate it too much, you can just change it on your server with modding.

**Comment by midn8t** [comment]
not me ill just kill the 100 animals so i can use shovel 10 times i see no point in taking skill point cost twice you have to unlock farming which incresss specialty cost then you have to take ditch digging shovling to raise it again if you playing on a real server with a in cress in profession costing being 2 times then by time you you can really rack up points. you have to unlock farming, digging, mining , axiing by time you get to doing what you want do next profession be running you  300 points or more.

**Comment by midn8t** [comment]
issue is that no one does and they end up killing every thing in game due to amount of game requires you to eat to do days worth of work when you dont have skills. and amount of points that it racks up as a mutiplayer aginst you.

**Comment by Deantwo** [comment]
Sounds like intended gameplay to me.

**Comment by midn8t** [comment]
dosnt sound realstic to me,, sounds more like a fantasy game.

and its all due to fact that they are putting up artificial berries to general skills that any bozoo can because these are just skills not professions.

**Comment by midn8t** [comment]
also just because something is intended doesn't mean something is correct or worth while or that it adds value or meaning.

**Comment by D3nnis3n** [comment]
Digging is no longer a profession, while mining stayed.
