### ISSUE TITLE
oer eating is still issue

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#645]
_From @midn8t on November 30, 2018 19:52_

amount of food intake is bit over top,

oen buff or deer littler feeds most familys for year.

if i ate as much as this guy does when working I wouldnt work at all id be sleeping all time in a comma.. or dead guys eating 30k caliores day or more.

_Copied from original issue: StrangeLoopGames/EcoIssues#10165_

**Comment by D3nnis3n** [comment]
Closing this issue, as it's being a simple realism issue.

In Eco food is required to do labour and an important game mechanic. All this is done under the assumption that each player actually represents a lot of people on the world for simulation purposes.
