### ISSUE TITLE
Add building forms to pipes

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoSuggestions#647]
Like other building blocks.
for me, e.g. "freeform" (current), "90" (only 2 ends in any case, but needs ability to free rotate or split to multiply form), linear (as prev.)

E.g. for prevent this
![unknown](https://user-images.githubusercontent.com/4980243/49859109-ccdc0e80-fe07-11e8-8c87-88bfbdb6d587.png)

**Comment by elfl0rd** [comment]
As i see, without changing\adding ability to free rotate, need
Vertical and horizontal linear pipe form
From down to side 90, from top to side 90, side to side 90
And "freeform" (current one)

**Comment by redwyre** [comment]
Stacking stored pipes 2x2 or 3x3 per block makes a lot more sense than just one a block

**Comment by elfl0rd** [comment]
Agree, stacking as really better then current behavior.

**Comment by Deantwo** [comment]
Not fixed/implemented.
