### ISSUE TITLE
"Street shop"

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoSuggestions#648]
I want small shop for streets, can be placed outside of house.
Can contain 2-3 trades.
Like this.
![v-ekaterinburge-pensionerka-zhivet-vnutri-ulichnogo-prilavka-dlya-torgovli_1](https://user-images.githubusercontent.com/4980243/49919597-2a2f9880-feb8-11e8-8110-b7d3704487e2.jpg)
![images](https://user-images.githubusercontent.com/4980243/49919599-2a2f9880-feb8-11e8-8cbd-321c01de9c8b.jpg)
![prilavok](https://user-images.githubusercontent.com/4980243/49919600-2a2f9880-feb8-11e8-9545-6e8ddc6a2bca.jpg)

**Comment by Deantwo** [comment]
Yes please. Having to build a full 5×5×5 house every where you want to place a store is quite limiting.
