### ISSUE TITLE
Rolling Mill shouldn't require Robotic Assembly Line.

### ISSUE THREAD

**Issue by Aatch** [StrangeLoopGames/EcoSuggestions#649]
The Rolling Mill makes two high-tier building materials: Corrugated Steel and Flat Steel. Corrugated Steel is Tier 3 and Flat Steel is Tier 4. The problem is that you require a Robotic Assembly Line to make a Rolling Mill, which itself requires Tier 3 materials to be functional. The result is that Corrugated Steel is basically never used, in fact my experience so far suggests that some people don't even know it exists. Furthermore, the fact that Flat Steel requires epoxy doesn't really mean much, since if you can make Corrugated Steel, you can make Flat Steel due to the existence of the Robotic Assembly Line.

The Rolling Mill should probably be built on a regular Assembly Line, not a Robotic one.

**Comment by DragonSupremacy** [comment]
+1. 
You need reinforced concrete just to be able to start making the other tier 3 material, while by comparison framed glass (a tier 4 material no less) just requires a kiln, glass and steel. Those in turn are a mix of tier 1 and tier 2 materials.

**Comment by Blanclour** [comment]
I agree the rolling mill should totally be made in the regular Assembly Line.

**Comment by WeaselDog** [comment]
Great feedback. We have now made the Rolling Mill require the regular Assembly Line.

Thank you for your contribution to Eco!
