### ISSUE TITLE
Suggestion: Some skill category changes

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#65]
_From @GophTheGreat on May 9, 2018 4:40_

From Steam https://steamcommunity.com/app/382310/discussions/4/1694920442952409991/: 

there are four items with the category "cooking", leaving a fully-equipped kitchen with some virtually worthless items (in terms of skill points produced). The butchers table and/or the kitchen could move to the "food prep" category, which would still overlap with the mill, but which would reduce the stacking penalty some. alternately, the recipies at the cast iron stove could be duplicated onto the kitchen or modern stove (as appropriate), letting you discard it once you have both replacements

_Copied from original issue: StrangeLoopGames/EcoIssues#7644_

**Comment by D3nnis3n** [comment]
No longer applicable.
