### ISSUE TITLE
Cattle Farming

### ISSUE THREAD

**Issue by weijki** [StrangeLoopGames/EcoSuggestions#659]
Skill - Cattle farming    
Sub-Skills 
- Dairy
- Breeding
- Wool
- Taming

Cattle             -     Produces                                       -             Harvest Time       - food   
- Cow:     -     Milk, Meat, Manure            -                               12h                           - grass,wheat,corn
- Goat:     -    Milk, Meat Manure          -                                  24h                      - grass,wheat,corn
- Sheep:   -   Wool, Meat, Manure              -                            24h                        - grass,wheat,corn
- Pig    -       Meat Manure         -                                            12h                          - all food    
- Horse -   Riding Meat Manure          -  12h - grass,wheat,corn
- chickens - eggs, meat manure       -      12h 

Skill Dairy / Breeding /Wool / Taming
level 1 : max 5 cattle of subskill on your property
level 2:  max 10 cattle  of subskil  on your property 
level 3:  max 15 cattle  of subskil on your property
level 4  max 20 cattle  of subskil on your property 

Skill Dairy / breeding/ Wool / taming Effency 
level 1: food cost 90%
- milk with hands 
- +1% breeding chance
- make and use scissors or wool 
- stick or fetching 0.5% taming chance
level 2: food cost 75%, able to use little tanks for storing milk or manure 25% less pollution 
- bigger buckets +5% more milk
 - +1%breeding chance
- make and use bigger wool cutters  +5% more wool
- use lasso for taming +1% taming chance
level 3: food cost 50%, able to use larger tank for storage milk or manure   50% less pollution
- electric milking machine +5% more milk
- +2% breeding chance
- use electric scissors more wool
- use whip for taming +1% taming chance
level 4 food cost 25%, able to use the biggest tanks and the stored manure will create no pollution at all
- use automatic electric milking system,  milked automatic when ready
-+3% breeding chance
- use automatic electric sheering system ,sheer automatic when ready
- professional taming +2% taming chance

Skill Dairy / breeding/ Wool / taming Speed
level 1: 
- 5% more milk
- chance for succes breeding 25%
- 5% more wool
- taming chance of 10%
level 2: 
- 15% more milk
 -Chance for succes breeding 50%
- 15% more wool
- taming chance of 20%
level 3: 
- 30% more milk 
- chance or succes breeding 75%
- 30% more wool
- taming chance of 40%
level 4
- 60% more milk
- chance of succes breeding 100%
-60% more wool
-  taming chance of 75%

The cattle can be sold also as meat to butchers or sold to fellow cattle farmer it their breeding subskill is not good enough to breed properly

Cattle produces manure, this can be sold as fertilizer to crop farmers, also sold as raw material for biogas
but it also brings pollution with it, to long on one place makes it pollute the ground. to much manure fertilizer on one spot will lead to dead crops, so crop farmers should be carefull to use manure as an fertilizer.

special storage systems can be used for milk and manure, the better the storing system for manure the less pollution it will give. Also there can be special tanks produced for tractors or trucks to deliver milk or manure to other shops. Also an cattle cart for tractors to deliver alive cattle to the butcher or other cattle farmers.

Horses can be used as transportation and sold, hunters and tamers would benefit of horses.

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoSuggestions/issues/1568
