### ISSUE TITLE
Saving law drafts

### ISSUE THREAD

**Issue by alexarthur94** [StrangeLoopGames/EcoSuggestions#668]
Since laws can take a while to write in some cases, it would be helpful to be able to save partially completed law proposals as a draft to return to later.

**Comment by jthill** [comment]
I think it would be helpful to save them as text, a web form is safe but slowwwww.  Maybe with keystroke accelerators on the choices it could be improved?

**Comment by D3nnis3n** [comment]
That's now possible.
