### ISSUE TITLE
Ability to Amend Laws

### ISSUE THREAD

**Issue by alexarthur94** [StrangeLoopGames/EcoSuggestions#669]
Currently, if one wants to adjust an existing law, it has to be repealed and replaced with a brand new law, which requires starting from scratch. This can be time consuming, especially for longer laws. It would be very helpful if it were possible to propose amending an existing law so that you could make changes to the law without starting from scratch, and then the amended law could replace the older one if it passed the vote.

**Comment by D3nnis3n** [comment]
https://github.com/StrangeLoopGames/EcoSuggestions/issues/510
