### ISSUE TITLE
(Suggestion) Industrial Age

### ISSUE THREAD

**Issue by FugitiveCargo** [StrangeLoopGames/EcoSuggestions#671]
Instead of having engineers manufacture all late game stuff what if they made blueprints kind of like research scrolls but one print per craft to advanced machinery like trucks and cars. Then someone can join a new profession manufacturing and they can then produce this product. But to get machinery to produce the products a production engineer can craft the assembly machines. Be cool to see conveyors and auto assembly along mass production of everything not just cars and trucks. Would be cool to see cars later game that drive faster and are more fuel efficient and can haul more people but only have small items storage. Also add a trucking branch to the manufacturing profession where they can drive a new item semi trucks from point a to b adding the transportation trade and they have to level up there skills to drive bigger and more powerful semis that produce more pollution but then theres a skill that can decrease pollution driving efficency. It would be as if they get better at driving semis. Meaning deattachable trailers that can also upgrade and hold more items requiring more power from the truck connected to pull it. Also be cool to see computers that different manufacturing companies can order smaller parts from or request so many parts kind of like the contract board but more specific to company and a pay before the job is done. And if the order isnt complete would be cool to see a justice / court system with jail and jail time etc.

Would also be cool to see late gane greenhouses/hydrofarms with lamps fans and sprinklers that require power to run and operated and the sprinklers water then you can configure to what you want the room at and they maintain said numbers.

**Comment by Deantwo** [comment]
Unless you are playing on really really big worlds, I don't see "semi trucks" being very useful. Same with people wanting trains. It would be cool, but might be overkill for the scale of the game. If the game eorlds get much much bigger it would be interesting though.
Bigger trucks could probably be added with modding fairly easily.

As for late-game professions and manufacturing, a lot can be made better or more interesting. With the new skill system coming in v8.0 I am hoping some professions/specialities get separated and expanded.

Greenhouses and other advanced farming will likely come in the future. The devs has been asked aboit it before and stated that it will likely be implemented when they go back to working on farming.

As for jail time, I actually made a suggestion about that awhile back.
Here: #536

**Comment by FugitiveCargo** [comment]
I'm used to playing on 4km worlds maybe if eco could have performance improvements including some glitch fixes maybe they could make larger worlds normal.

**Comment by FugitiveCargo** [comment]
I'm new to modding I dint know java code and I found the tutorial confusing.

**Comment by Deantwo** [comment]
@FugitiveCargo, **Eco** is written in .net C# with Unity, not Java.

**Comment by FugitiveCargo** [comment]
I dont understand any coding and the YouTube tutorial for modding is confusing. But I'll try and give it an attempt. Is there a possibility of looking for a new member to the team, and train him?
