### ISSUE TITLE
Economy (Market) Window Missing Necessary Information

### ISSUE THREAD

**Issue by SelfSent** [StrangeLoopGames/EcoSuggestions#678]
When selling goods, the market provides a valuable window into price and location to select the best sale you can make. But, there are confounding factors that are not visible, greatly diminishing it's use:

- While you can see how much a user is willing to buy, and for what price, you cannot see if they have the funds necessary to cover the transaction unless you travel to their store and attempt to sell, or simultaneously open the Currency Report to crosscheck.
- You cannot see if they have the space available to accept your sale; the only way to check this is to travel to that player's store and attempt a sale.

Both of these result in a dimishment of the market window's usefulness, and much wasted time.
Thanks! I love the game.

**Comment by D3nnis3n** [comment]
The first is implemented, the second was denied as of too high resource usage.
