### ISSUE TITLE
USER SUGGESTION: restart voting

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#685]
_From @NortonDK on February 12, 2019 13:13_

Players having the option to vote for a server restart, would be very helpfull in these buggy times

_Copied from original issue: StrangeLoopGames/EcoIssues#11277_

**Comment by D3nnis3n** [comment]
Can be done with this: https://github.com/StrangeLoopGames/EcoIssues/issues/9059
