### ISSUE TITLE
hunter profession is minimally useful. add animal husbandry

### ISSUE THREAD

**Issue by jellomold** [StrangeLoopGames/EcoSuggestions#688]
Since anyone can make a bow and butcher the kill, hunters are basically a wasted point. the new animal AI can be gamed since animals will run for a bit after getting hit then slow and pause, usually still while in range. two head shots and most will fall.  everyone shooting the animals has played a FPS at least once..that's the only shot worth making ;)

anyways, the late game is all about industry leaving something like "hunter" aka "naturalist" quite abandoned. what if it has the only skills to breed/rehabilitate/handle animals, both wild and 'domestic' which is a separately missing thing. we all love chickens and their eggs. and goat milk (shudder).

**Comment by Deantwo** [comment]
Animal husbandry is planned, but no information about when or how.
Might come together with the future farming overhaul.

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoSuggestions/issues/1568
