### ISSUE TITLE
Feature: server history timeline.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoSuggestions#694]
Like
![photo_2019-02-17_19-27-46](https://user-images.githubusercontent.com/4980243/52915867-22420980-32ea-11e9-90b4-fb3fec1b0026.jpg)
Contain all important data, "first join", first gather, first craft, first place, first kill, first research, etc.
Next - contain 10th, 100th, 1000th action. "Dragon crafted hundredth steam truck in the world!"

have filters (by players, time, actions, etc...)
can be downloaded from server to local html with images (and stored\viewed locally!).

**Comment by Conchipedia** [comment]
didn't we also use to have how many items was also created by a single player? 
for example: Conchita has mined 5000 Sandstone and crafted 500 Mortared Stone, 20 Brick etc

**Comment by elfl0rd** [comment]
Nice addition, also for "user".

**Comment by Conchipedia** [comment]
found the OLD Server Submission we did for PAX 2017, this is just my part of that:

**Conchita Build:** Aqueduct 29, Asphalt Road: 2973, Brick: 344, Concrete 807, Concrete Column 203, Concrete Stairs 23, Concrete Window 39, Copper Pipe 4, Corrugated Steel 20, Dirt 7190, Dirt Road 754, Glass 1944, Iron Pipe 19,  Log 697, Log Roof 32, Lumber 221, Lumber Roof 14, Modern Window 3, Mortared stone 3891, Peat Roof 114, Reinforced Concrete 100, Steel Pipe 349, Steel Window 13, Stone Road 3989, Tailings 123, Wood Fence 448, Wood Stairs 30, Wood Window 5, World Object 10

**Conchita Craft:**  Aqueduct 2520, Asphalt Ramp 584, Asphalt Road 12837, Big Shovel 8, Blast Furnace 2, Board 544, Brick Roof 250, Brick 1631, Bucket 1, Campfire 4, Carpentry Table 2, Chair 20, Concrete Column 3807, Concrete Stairs 144, Concrete Window 94, Concrete 14591, Construction Post 1, Coopers Tool Shelve 1, Copper Ingots 1267, Copper Pipe 453, Dirt Ramp 4017, Door 22, Electric Generator 1, Electric Wall Lamp 75, Electronic Assembly 1, Farmers Table 1, Glass 1909, Gold Ingots 2982, Huckleberry Seed 98, Iron Ingots 3207, Kiln 23, Kitchen 1, Lumber 908, Modern Wood Window 3, Mortared Stone 4370, Pitch 5707, Property Claim Flag 108, Quarry 3, Rebar 1137, Reinforced Concrete Roof 510, Reinforced Concrete 3845, Sand 2307, Sanding Block 1, Saw Mill 2, Small Wood Sign 45, Steel Pipes 30, Steel Window 100, Steel 2408, Stockpile 123, Stone Ramp 1555, Stone Roof 1154, Storage Chest 5, Store 5, Streetlamp 37, Table 2, Wood Fence 460, Woodpulp 2720, Wood Sign 6, Wood Stair 50, Workbench 2

Conchita Skillgain: **Agriculture 575, Carpentry 289, Civics 67, Cooking 2, Engineering 509, Masonry 1179,** Smithing 2277, Survival 945

This was a nice addition to Eco

**Comment by ludovi71** [comment]
Also Treasury transaction history would be nice .

**Comment by johnkslg** [comment]
Will definitely by doing this! Maybe for Eco 10.0
