### ISSUE TITLE
Return and rework "road engineer" speciality

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoSuggestions#695]
Contain crafting all roads\ramps.
Have special machinery for road replace, e.g. something like plough - have 2 slot in inventory, while using pickup blocks under working zone to 1 slot, and place to same place from 2 slot.
e.g. manual one (also need mechanical one!)
![photo_2019-02-13_16-39-39](https://user-images.githubusercontent.com/4980243/52915945-0d19aa80-32eb-11e9-8bdc-dc5799b89f8a.jpg)

**Comment by Blanclour** [comment]
I like the idea of a machine which can replace road blocks. Digging up dirt roads and laying down stone roads is particularly frustrating.
