### ISSUE TITLE
Districts view on the minimap

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#71]
_From @ShaydenMac on May 8, 2018 0:8_

Via player.

It's very hard to distinguish where the districts are located as things are currently set up. Would like to be able to see districts on the minimap. 

_Copied from original issue: StrangeLoopGames/EcoIssues#7624_

**Comment by elfl0rd** [comment]
@D3nnis3n John make this as issue, maybe need close this?

**Comment by johnkslg** [comment]
yep
