### ISSUE TITLE
Disable Tailings option.

### ISSUE THREAD

**Issue by erraticengineer** [StrangeLoopGames/EcoSuggestions#713]
Make tailings an option in the config.  That way we don't have someone constantly having to dig out space for tailings.  There's other ways to pollute other than tailings.  That or make them less of a pain in the ass.  They become "Tailing Burying Simulator" for the smelter, to the point where I had one player abandon it and ask for a skill reset.

**Comment by D3nnis3n** [comment]
Won't have that, but it's planned to add recycle options for slag and tailings later on.
