### ISSUE TITLE
Allying Landclaims and Trade between unallied

### ISSUE THREAD

**Issue by erraticengineer** [StrangeLoopGames/EcoSuggestions#714]
This is a thought for larger servers.  Multiple people, friends, group together, and they have a few people per group.  They decide to band together under one flag.  Same applies for another group.  These two groups aren't working together, yet.  But one group has claim with a resource another needs.  So trade is necessary.

They can't talk to each other.  There would be a randomizer used to replace words/letters and remove accidental swears and such from profanity.eco.  But they can use a common trade station.  They put up what they want, and what they're willing to trade for it.

Yes, this can be circumvented with discord or other chatting apps, but this would be more for RPing servers.

**Comment by D3nnis3n** [comment]
Not in the scope of eco, given voice-chat is going a directly different direction.
