### ISSUE TITLE
Remove Tailings, Make Ingots require Coal/Pollution generating fuel, creating air pollution instead of tailings so smiths can deal with air pollution instead of tailing overload.

### ISSUE THREAD

**Issue by erraticengineer** [StrangeLoopGames/EcoSuggestions#718]
Long title but it encompasses everything.
Right now if I make 20 Iron Ingots, I've got a ton of tailings to deal with.  I can go bury them, but then I need to make more ingots.  People have said "Make a community solution", but there shouldn't be a community solution when other specialties don't have this level of trouble.  You can fill up a 5x5x5 stockpile in an hour.

So my suggestion is to remove tailings, as they're not really involved in smelting (it would be slag, or junk metal, but it wouldn't be really harmful), make certain recipes require a certain level of fuel power (ingots, coal or better), and then work on how to handle the air pollution while still maintaining iron ingot/gold ingot/copper crafting.

The air pollution is more realistic in my opinion, and the slag could be milled or pressed into something like rebar for concrete.

**Comment by D3nnis3n** [comment]
Tailings will be replaced with slag in the blast furnace later on, while tailings will be a part of rock crushers. Totally removing them would not be realistic.
