### ISSUE TITLE
More Hewn Log Variations (colours)  like Mortared Stone has

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoSuggestions#719]
Seeing as we have Four types of Mortared Stone
![snap4174](https://user-images.githubusercontent.com/29383891/53105185-8f42e280-3528-11e9-8511-73900996d6d9.png)
and can Process Six types of raw Stone to normal Stone
![snap4175](https://user-images.githubusercontent.com/29383891/53105240-a41f7600-3528-11e9-965b-894f982fd90e.png)
Would it be Possible to Have More Types of Hewn Log seeing as we have different trees in Different Biomes, that can Produce their own type of Log for making that type of Hewn Log and on a workbench they can be processed into normal logs like we do for normal Stone

**Comment by D3nnis3n** [comment]
9.0 will include different tree styles, not necessarily on hewn log level, though.
