### ISSUE TITLE
Profession-specific clothing

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#72]
_From @ShaydenMac on May 8, 2018 0:6_

Via player.

Would like to see profession-specific clothing that would have an effect of possibly reducing calorie consumption based on the proper clothing. 

_Copied from original issue: StrangeLoopGames/EcoIssues#7623_

**Comment by D3nnis3n** [comment]
We have that in the meanwhile, though benefits are still WIP.
