### ISSUE TITLE
Balance: too many stone at mid\late game

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#723]
_From @elfl0rd on February 21, 2019 15:49_

In mid\late game their consumption is low enough that the by-mined stone becomes a problem. For example, a lot of granite with gold mines.

_Copied from original issue: StrangeLoopGames/EcoIssues#11444_

**Comment by BlazeGuy2** [comment]
_From @Conchipedia on February 22, 2019 2:29_

we need more things to be made from Excess stone, in my Mining, i have quite a few Workbenches that are making 1000's of stone but are never linked to any storage, so its just sitting in a void somewhere

**Comment by BlazeGuy2** [comment]
_From @eliotcougar on February 22, 2019 15:48_

Maybe the upcoming change that makes loose stone turn into blocks again can alleviate the issue somehow... Don't know if it's gonna affect stone stored outside of a stockpile... If it does, you would be required to get rid of excess stone from your ore excavation business by piling it nearby in a huge mountain, like in the real world...

Bottomless void pocket dimension in workbenches will be abused if the whole crafting workflow is not changed...

**Comment by D3nnis3n** [comment]
Stones are used to build buildings. There is ever a way to use it.
