### ISSUE TITLE
Chunks are not loaded.

### ISSUE THREAD

**Issue by Malenkei** [StrangeLoopGames/EcoSuggestions#745]
Chunks are not loaded at all or very slowly, this creates critical situations with the technique.

![](https://cdn.discordapp.com/attachments/544243715544186891/552279311718285312/unknown.png)

**Comment by redwyre** [comment]
Could you create this as a bug here: https://github.com/StrangeLoopGames/EcoIssues/issues

**Comment by D3nnis3n** [comment]
Tha
