### ISSUE TITLE
Same Power consumption for all Lights

### ISSUE THREAD

**Issue by gamerpaddy** [StrangeLoopGames/EcoSuggestions#748]
Indoor lights like the Wooden Table Lamp, Steel ceiling light etc. require **250W**
Outdoor lights like the Streelamp and Wall lamp require **100W**

They give both the same amount of light intensity, so i would preffer that they consume the same amount of power. 
Also 100W seems reasonable, 250W is way too much.   1 Huge windturbine for just 4 lamps is a bit too much.

**Comment by D3nnis3n** [comment]
Indoor Lights now all require 60W, outdoor lights all require 100W with the exception of the Double Modern Streetlight that consumes double the amount, e.g. 200W.
