### ISSUE TITLE
exclusive fullscreen mode

### ISSUE THREAD

**Issue by apnotix** [StrangeLoopGames/EcoSuggestions#749]
Is there a way to implement an exclusive full screen mode? Why there are only the borderless fullscreen mode? The checkbox "fullscreen" should be the exclusive fullscreen mode and an additional checkbox for the borderless would be nice. I think this mode would get some performance out of the game. The current performance of the game isn't really good.

My setup:
20-30 fps @Full HD / 2k resolution
Nvidia Zotec 1080 AMP Extreme
Intel Core i7 5820K 6x 3.30GHz / PC 3.8GHz

**Comment by SeanAtr0n** [comment]
Last time I looked there weren't any options for toggling this at runtime in unity, looks like it may be possible now

**Comment by eliotcougar** [comment]
The game is CPU-limited most of the time...
Exclusive Fullscreen mode won't help with performance...
