### ISSUE TITLE
Allow disabling Web UI & punchthrough

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#750]
_From @bartico6 on March 8, 2019 14:27_

Server administrators should be able to disable the Web UI as well as punchthrough for firewalls.
The reason is, when starting the server in a non-elevated environment, I get asked to elevate the server to run `netsh` 3 times, and it's being somewhat annoying to close the elevation prompt multiple times when starting the server.
I also do *not* want the Web UI, but I see no option to disable it.

_Copied from original issue: StrangeLoopGames/EcoIssues#11609_

**Comment by D3nnis3n** [comment]
The Web UI is integral part of the game for now, so this won't happen.
