### ISSUE TITLE
The picture gets behind the sign

### ISSUE THREAD

**Issue by Malenkei** [StrangeLoopGames/EcoSuggestions#753]
The image in the sign is not displayed correctly 
The picture comes out of the sign

![20190313030054_1](https://user-images.githubusercontent.com/36518011/54239445-06becd00-453d-11e9-859e-fb5cafbcbd28.jpg)

**Comment by redwyre** [comment]
Can you post this is a bug at https://github.com/StrangeLoopGames/EcoIssues/issues ?
And include the text you are using
