### ISSUE TITLE
Currency in Bank Should Count as In Circulation

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoSuggestions#760]
Currency in a player's bank account should count as in circulation. Only printed currency in the treasury should count as not in circulation. Many people do not use bank accounts as a savings account, assigning them to a store. Even if it was a savings account, money in a savings account is still in circulation. 

This makes it difficult to judge inflation and amount of currency to print. The more people who use bank accounts, the more difficult it becomes. Currently I have to keep notes to remember the amount of currency I have printed and distributed, which should not be necessary.

**Comment by D3nnis3n** [comment]
That's actually a bug.
