### ISSUE TITLE
Survivalist should be off as default

### ISSUE THREAD

**Issue by criptonauta** [StrangeLoopGames/EcoSuggestions#768]
The topic focuses on Survivalist skill, but in fact it's a chain of facts/events that are preventing the good use of Farming and Chef skills in game.

Survivalist being on as default kills the Farmer and Chef careers since day one, no matter if in a more specialized server or one with no skill limits. That point is further affected when considering the return of making some advanced foods - the foods produced with adv campfire or basic cooking are more than enough if Survivalist is on (except for those obsessed for maximizing xp).
Another point is that a lot of foods are not worth to be produced - why people would invest a lot to make Pasta when it takes a lot of resources and the nutritional facts are not that good? Even when they are sold, either the price is low so it can be accessible for most players or they are not sold at all.

Perhaps it's possible to better balance the calorie consumption during the day inside the game? (I noticed that it takes almost two game days and nights to force someone to eat, unless if under hard work.)

**Comment by Guedez** [comment]
next patch survivalist will not affect calories spent, only max calories
Sure, the fact that only BEAR S U P R E M E, Pineapple Rice and Sweet Salad are worth eating is a problem, but that's not Survivalist fault now, nor will be next patch

**Comment by criptonauta** [comment]
> next patch survivalist will not affect calories spent, only max calories (or so I assume according to the codestream channel on discord)

That's a great thing.

> Sure, the fact that only BEAR S U P R E M E, Pineapple Rice and Sweet Salad are worth eating is a problem, but that's not Survivalist fault now, nor will be next patch

I agree it's not a survivalist problem. But the fact that survivalist - as it is now - comes enabled by default, aggravates the current feeding and food producing issues. 

Correcting the previous info, it took my wife 5 game days and nights to have a real need of food (her survivalist lvl is 5)

It's great that everything is being read and considered... Can't wait for the next release :D

**Comment by D3nnis3n** [comment]
Self Improvement no longer provides calorie cost reduction, which should solve the issue for which you created this suggestion. I'll go ahead and close it therefore.
