### ISSUE TITLE
[Suggestion] Law Clause for Sales Tax Exemptions

### ISSUE THREAD

**Issue by Blanclour** [StrangeLoopGames/EcoSuggestions#770]
A way to make the buying and selling of certain items exempt from sales tax would be very beneficial. Such an example would be for the purpose of true backed currencies, where people use a store that has a fixed exchange rate for a certain item in exchange for a minted currency.

Sales tax cannot be used in this instance because it would make the exchange rate uneven and people would have to pay more then what they originally traded to buy back the backed item from the store.

Another use would be to promote the exchange of certain items and stimulate the economy. The possibilities are endless.

**Comment by johnkslg** [comment]
Should be doable with new law system more easily.
Also would like to do tax credits and deductions

**Comment by D3nnis3n** [comment]
https://github.com/StrangeLoopGames/EcoSuggestions/issues/872
