### ISSUE TITLE
[Suggestion] Modern Street Lights

### ISSUE THREAD

**Issue by Blanclour** [StrangeLoopGames/EcoSuggestions#774]
We have streetlamps, which fit the stone roads and late-mid game aesthetic nicely, but they do not fit a truly modern city. A modern street light that is much brighter, similar to the difference between an electric wall lamp and a steel ceiling light is desirable. It could require oil based materials just like the steel ceiling light, ensuring it appears at the same time as other similarly themed lights.

**Comment by D3nnis3n** [comment]
Thanks for your suggestion, it has been implemented - we got modern single and double streetlamps in Update 9.0!
