### ISSUE TITLE
[Suggestion] Move Framed Glass to the Robotic Assembly Line

### ISSUE THREAD

**Issue by Blanclour** [StrangeLoopGames/EcoSuggestions#777]
Framed glass should be made in the robotic assembly line just like framed glass doors. As a tier 4 material this would make more sense and ensure that it can't be made until society has advanced to a stage worthy of tier 4 materials.

**Comment by WeaselDog** [comment]
Thanks for the suggestion. We have moved both Framed Glass and Framed Glass Door to the Electric Machinist table to delay when Tier 4 is introduced. We will also have new options for Tier 4 in 9.0 as an alternative to Framed Glass.

From our testing we found that Robotic Assembly Line was a little too late, but with the Electric Machinist Table it still requires significant advancement from society before Framed Glass can be made.

Thanks again for your contribution to Eco!
