### ISSUE TITLE
[Suggestion] Trains - Distant Future Patch Suggestions

### ISSUE THREAD

**Issue by Blanclour** [StrangeLoopGames/EcoSuggestions#780]
I write this knowing very well what the developer's current stance on trains is. My hope is that this may prove useful in the future when trains become relevant (I'm surprised they aren't now, considering they are #1 voted on roadmap).

I understand that minecarts are also a part of the entire idea that had been discussed before, but I'm going to focus on suggestions pertaining to standard trains.

Before going on to the suggestions regarding trains, I'd like to point out their particular utility in eco. Are they worth it when there are roads and trucks? Yes they are when the world size is equal to or greater than 1km. While trucks are able to haul reasonable loads at high speeds across great distances, they struggle when it comes to hauling heavy material such as ore. Players are notorious for mining massive amounts of ore, and with the new 8.0 biome patch, their mine could be on the other side of the world.

Yes they could build a road, but trucks will still only be able to haul a small amount each trip. These trips can add up quickly. A train on the other hand, could haul several stockpiles worth of ore in a single trip. In fact, there could be transport contracts for several miners in an area wanting their ore moved. This would make centralized areas where people place their blast furnaces a more viable option and would work well with the new water system, rather then trying to run a potentially 100m-200m pipe out to the location of each mine.

The changes to movement allowing underbrush to slow players down has made trains a viable choice for mere transportation over long distances. Yes there are steam trucks and possibly roads, but not everyone can afford one to start. For players that don't have a vehicle, or for new players, trains are an easy way to travel between important locations where business is conducted on the map.

There ideally should be three locomotive vehicles: Steam, Diesel, and Electric. The width of train track is probably best 2 or 3 blocks wide ( standard rails are 4' 8.5" irl ) if it is to keep scale with the current vehicles in game.

The steam locomotive is the obvious first choice that players could build, and would require massive amounts of coal or wood and would also require water towers powered by the new pipe system to keep the trains running on steam. Slow and not very efficient, the steam locomotive is the heavy transport alternative to the steam truck and could be available around the same period.

I only see a need for a single rail-car of each type to be used through the whole game.  A hopper car, a flatbed car, a boxcar, and an oil tanker car. The hopper car is for materials such as dirt, clay, stone, and ore. The flatbed car is for logs and other items that fit the theme. A boxcar is for goods that normally render as boxes in a stockpile and don't need to be visible during transport. The oil tanker car could come available at a later date when oil drilling is active, it probably would only be used when pipelines are too long and expensive to consider.

The diesel locomotive would be the successor to the steam locomotive and would probably become buildable after robotic assembly lines are actively in use. Advantages would be the ability to pull more rail-cars, is not reliant on water towers, higher speed, and uses petroleum.

The electric locomotive would require players to upgrade train tracks with overhead catenary lines and provide a large amount of electricity. These trains would be faster then diesel locomotives but would have equal or lesser rail-car counts. The reason for this is that the electrification of the rail system is meant to be an expensive and long term project for players to work on in the end game, possibly even after the meteor has already been destroyed. An electric train system's main benefit is that it is reliant on electricity instead of petroleum, which could be powered by clean energy.

I don't expect all of this to make it into the eventual future patch that adds trains, but I hope this suggestion gives some great ideas for the possible implementation and progression of such a system.

**Comment by naed21** [comment]
Great writeup! What do you think about a passenger car? I'd image players would have there houses closer to shops if there was a quicker way to get to and from the mines. Having a train to both move people and goods could see train stations turn into small communities.

We could keep the complexity down and have the flatbed car be used for all non-fluid items, which would also allow the crane to push and pull items out quickly. Then the box car could instead be a passenger car.

**Comment by Blanclour** [comment]
> Great writeup! What do you think about a passenger car? I'd image players would have there houses closer to shops if there was a quicker way to get to and from the mines. Having a train to both move people and goods could see train stations turn into small communities.
> 
> We could keep the complexity down and have the flatbed car be used for all non-fluid items, which would also allow the crane to push and pull items out quickly. Then the box car could instead be a passenger car.

That sounds like a logical compromise, you have my approval.

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoSuggestions/issues/1571
