### ISSUE TITLE
[Suggestion] More Iron Deposits

### ISSUE THREAD

**Issue by trevelmike** [StrangeLoopGames/EcoSuggestions#781]
I am seeing a lot more input and output pipes these with pump jack, steam generator etc this can only mean you will put water in as a requirement which means more pipes. As i have mentioned before the way minerals are right now if this was pre .8 there would be no problem of iron pipes everywhere. (Yes i know you can make copper pipes but still you use copper for wiring) My suggestion that iron be as plentiful as copper is with what i have encountered huge rooms not just a couple stacks and more sandstone.

**Comment by D3nnis3n** [comment]
You can configure the rareness in your worldgenerator.eco. Having done four cycles since release of 8.0 i didn't see any issues coming up about people not having enough iron.
