### ISSUE TITLE
my two cents

### ISSUE THREAD

**Issue by trevelmike** [StrangeLoopGames/EcoSuggestions#787]
This is my response to the upcoming government buildings mentioned on steam. Comment was too long so i moved it here

My two cents i think it is little too early to talk about governments when quite frankly certain aspects of the game are imbalanced. That building looks to be made out of reinforced concrete so that's two steel for rebars......... Nope should be one steel per rebar. On top of that making concrete deals so much pollution i am only able to make pieces of it at a time. It just screams to be made electrical. ON top of that while it is nice you redid the geology of the planet you also created a new need for multiple stockpiles since we have multiple blocks and the only way they stack is by turning them into stone. Of course the laser now costs 50 gold bars among other things and because of the geology rework you find it in one to two chunks. Even worse you have to get twice as much oil to make good amts of epoxy and plastic. Two oil per item. Sure if costs less iron for the barrels but that no reason to inc the cost of epoxy and plastic and we should be able to reuse said oil barrel anyways.

**Comment by johnkslg** [comment]
We have people fulltime balancing, thanks for this feedback! @craig-jong
