### ISSUE TITLE
more category room

### ISSUE THREAD

**Issue by GazToxic** [StrangeLoopGames/EcoSuggestions#788]
Are you planning to integrate rooms categories like restaurant, clothing store, carpentry shop, metal working and so on

**Comment by D3nnis3n** [comment]
Hello GazToxic,
the room system is especially for your personal home, as it gives skillpoints. Adding categories for any possible room type would allow you to get an insane amount of SP and is not the intention of the system. All the types you named are not house rooms, but industrial - we treat those as "Industrial Room" with no SP benefits.
