### ISSUE TITLE
/time is gone?

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoSuggestions#789]
Version: 0.8.1.3

In the [v0.7.8.0 update](https://accounts.strangeloopgames.com/changelog) there was a user level chat command added to see what the server time/day was called `/time`.
When attempting to use that command now it seems to be an admin command that requires a float parameter.

Was `/time` removed for some reason? Is there a new alternative?

**Comment by Deantwo** [comment]
@beastyn, wanna reference to this in the pull request you just made?

**Comment by beastyn** [comment]
@Deantwo 
Yeah, thanks. I will close it then. 
It will be in 0.9
