### ISSUE TITLE
Dev Tool doesn't support all block types

### ISSUE THREAD

**Issue by CompactDisc** [StrangeLoopGames/EcoSuggestions#790]
I'm not sure if this is a bug or an intended feature.

Game version: 
8.1.0, but assumed to be the case in later hotfixes

Description:
Dev tool doesn't include the ability to place natural stone blocks, water, trees, and a few other kinds of blocks.

**Comment by D3nnis3n** [comment]
Stuff like that is typically not built manually (if needed at all), but spawned in via commands. Technically, the dev tool is for supporting the development, not for use by admins - they just can do it, but it's not made for them. Hence i'm closing this issue.

Also, water can be placed via devtool.
