### ISSUE TITLE
So...we need to talk.

### ISSUE THREAD

**Issue by Phlo123** [StrangeLoopGames/EcoSuggestions#793]
![image](https://user-images.githubusercontent.com/17730996/48842039-de4b7100-ed9b-11e8-9250-29da1729f4a2.png)
this is the patch notes released with 7.8.4...O.K.
When I tried to update to the new version 76 of my mods broke, but there is no information in discord that could tell me something changed and all my mods files will require an update.
I know mods mean nothing to the base game and with the current modding community we are easily ignorable; but making mods from start to finish (models, textures, animations, cs files) by myself while taking care of a running server, takes time. I get help from programmers here and there with different cs files but I can't go around asking for favors all the time from strangers on a discord server.
Please, please, PLEASE! , pleaaaase see if there is a way to announce changes that break simple item, maybe even before the update is launched so server with mods have a chance to update to the latest version in the first day of launch.
This is the most basic cs file for a mod someone can make.(I think.)
![image](https://user-images.githubusercontent.com/17730996/48843170-ff619100-ed9e-11e8-800a-5a4e7923febf.png)
But its broken, and the error is:
"Error in AdminMask at 25: Member 'Eco.Mods.TechTree.AdminMaskItem.FriendlyName' overrides obsolete member 'Eco.Gameplay.Items.Item.FriendlyName'. Add the Obsolete attribute to 'Eco.Mods.TechTree.AdminMaskItem.FriendlyName'. (CS0672)
Error in AdminMask at 26: Member 'Eco.Mods.TechTree.AdminMaskItem.Description' overrides obsolete member 'Eco.Gameplay.Items.Item.Description'. Add the Obsolete attribute to 'Eco.Mods.TechTree.AdminMaskItem.Description'. (CS0672)"
I understand the error and its an easy fix, now multiplying that with 76 doesn't really give you the courage to make more mods.
There are endless reasons for updates and changes to be made to a game, especially for one that is in development, but changing FiendlyName to DisplayName... idk.
Again, if there is a way to get this kind of information about changes before they get launched in a update please let me know; if not just ignore this.

**Comment by D3nnis3n** [comment]
Closing this. We're announcing changes in changelogs.
