### ISSUE TITLE
Live stock

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoSuggestions#8]
Animals like cows, horses chickens
so can have plows - and get milk from cows and meat the animal manure could be used for fertilizer like in real life, and then could have crop of alf alfa that like in real life puts nitrogen in the soil grows almost anyways dost need as much water due to deep root system - turns into hay for live stock.

also then could hook up plows to the horses or machines to horses to save on cost of planting and harvest.

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoSuggestions/issues/1568
