### ISSUE TITLE
Medical Skills

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#80]
_From @ShaydenMac on May 2, 2018 23:41_

Via Forum member: http://ecoforum.strangeloopgames.com/topic/4546/medical-skills

"Awesomepro247 

I feel like the game needs more challenges and the medical side will provide new challenges and job opportunities. Yes, the game is already hard, but I think adding a medical field would be interesting. You could have more time spent in pollution, the more calories you spend. You don't die in this game, so I thought that increasing the amount of calories spent would be an option. There could be a new workbench, Apothecary, that makes medicine from herbs and there could be doctors and nurses. There could be random diseases that come from nowhere that increases amount of calories used. This may be a bit too much, but in my opinion, this would make the game more fun and challenging."

_Copied from original issue: StrangeLoopGames/EcoIssues#7557_

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoSuggestions/issues/1567
