### ISSUE TITLE
The Ability to Add All Players or Blacklist

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoSuggestions#815]
**Version:** 0.7.7.2 beta

![snap3017](https://user-images.githubusercontent.com/29383891/46508581-fe4bc300-c835-11e8-90f3-051bf3c7b882.png)
As can be seen above we can ONLY have Public or Specific Citizens options, and because the Door is the **ONLY**  option i have to prevent Access to Public Mine if the mine was being Misused, On Servers with a Massive amount of Players it takes Forever to add everyone individually.
The Public Lets everyone use the Door but there is No way to remove a person from this list so an Option to **ADD ALL** (which we used to have) is really needed again (as it is also really difficult working out who is playing and who isn't and adding those manually).

**Comment by D3nnis3n** [comment]
Merged with #955
