### ISSUE TITLE
Increase XP obtained by logging

### ISSUE THREAD

**Issue by vini2003** [StrangeLoopGames/EcoSuggestions#817]
While playing on a small server, I saw most other professions rank up very fast. Mine, on the other hand - Logging - took an exceptionally long time to level up, due to the fact that to obtain XP, one must:

- Take down a tree, awarding 1 XP * multiplier;
- Take down tree remains, awarding 0.1 XP * multiplier;

Which turns leveling it up into a chore, where, at level three, with an x50 multiplier, one must take down nearly **one hundred trees to reach level four**. When compared to other specializations, the progression in logging is _much_ ,_much_ slower, my mining comrade having already reached level 7 in a matter of days, the butcher being level 7 in less than two days, and me, logging the whole time, barely getting to 4 in one week.

Not only that, it's also worse for the environment to be a logger, since you have to do more damage to the environment than others in order to reach similar progression levels.

All in all, this specialization desperately need an increase in XP earned, either by increasing the XP gained by each tree remain removed, adding a small reward for cutting trunks, or simply giving more XP per tree taken down.

**Comment by vini2003** [comment]
Arguably, one could also decrease XP obtained by other professions, but that still wouldn't stop logging form being a massive, environmentally-dangerous chore.

**Comment by bashemX** [comment]
I think many profession level too fast at the start, especially Hewing.

**Comment by WeaselDog** [comment]
Great feedback. Logging will now be responsible for crafting Hewn Logs, so they have a much easier time gaining experience.
