### ISSUE TITLE
Give more XP for complex recipes

### ISSUE THREAD

**Issue by otting** [StrangeLoopGames/EcoSuggestions#819]
Complex recipes  that take a long time to craft should give more XP than crafting a simple object.
Example: A Screw gives the same amount of XP as finishing a Truck.

**Comment by reggiew17** [comment]
I agree with this, more elaborate and complex the item the better the multiplier.

**Comment by D3nnis3n** [comment]
In Update 9.0 recipes were rebalanced and more complex recipes now also give more XP. :)
