### ISSUE TITLE
Combine Objects in Groups to reduce the amount of Recipes

### ISSUE THREAD

**Issue by otting** [StrangeLoopGames/EcoSuggestions#820]
Many recipes are duplicates of each other with slightly varying ressources, leading to a mass of similar recipes.

Example:
Some Specific Stone to processed Stone, if Sandstone and so on had a Tag like [Rock] you could make a recipe for turn [Rock] into Stone.

Example#2:
Crafting charred Fruits. Every fruit gets a tag [Fruit], one single Recipes turns them into charred Fruit.

Maybe a extra window could be made to select specific Stones, similar to the filter in economy view.

**Comment by D3nnis3n** [comment]
Tagged Crafting is in 9.0.
