### ISSUE TITLE
Bug on Server.Too long name

### ISSUE THREAD

**Issue by NXAO** [StrangeLoopGames/EcoSuggestions#821]
![2019-05-12_19-10-17](https://user-images.githubusercontent.com/4406080/57584921-b5559e80-74e9-11e9-983b-2afa7e49beaa.png)
[Storage Files](https://yadi.sk/d/vcmFaUzT1hv_Zw)
They have too long name:
first ->
>140000006C98CE34F47503E719D3D80001001001F796D65C1800000001000000020000004E0B2A5C0300A8C02764EC020C000000B8000000380000000400000019D3D8000100100166D505004E0B2A5C0300A8C0000000006818D45CE8C7EF5C0100F1170100010006490B0000000000736ACC6C0DAE44E53824A5502B6B043126A49F5E36A7DF2C747E20CB172F3EBEF4BAA2DE07A3C8F9F99B742020A26E0C9612F910AF406C2B15D76A71F8AF73B3C7EBBA613E9D13ABF34FB5DB08B75AAEF8A529E1D6684788D8111F00B1056E64491EA253C734C1A29E0403EFFAF4D50ACBE1D0AB7E99C5457BAF09394F33FE4E

second ->      
>1400000048DF977CF80CB5EB19D3D80001001001F696D65C1800000001000000020000004E0B2A5C0300A8C06E67A6020B000000B8000000380000000400000019D3D8000100100166D505004E0B2A5C0300A8C0000000006818D45CE8C7EF5C0100F1170100010006490B0000000000736ACC6C0DAE44E53824A5502B6B043126A49F5E36A7DF2C747E20CB172F3EBEF4BAA2DE07A3C8F9F99B742020A26E0C9612F910AF406C2B15D76A71F8AF73B3C7EBBA613E9D13ABF34FB5DB08B75AAEF8A529E1D6684788D8111F00B1056E64491EA253C734C1A29E0403EFFAF4D50ACBE1D0AB7E99C5457BAF09394F33FE4E

**Comment by redwyre** [comment]
This happens when authentication is turned off

**Comment by NXAO** [comment]
@redwyre yes and this not normal

**Comment by redwyre** [comment]
Post in EcoIssues or check out #official-support in the discord
