### ISSUE TITLE
Feature request.

### ISSUE THREAD

**Issue by madhatr** [StrangeLoopGames/EcoSuggestions#826]
Everyone seems to leave after the metoer is gone.

Possible game mode, Tower Defense.  More and more meteors rain down in increasing difficulty.

So pew pew needed.  

expansion: Different material make up meteors needed different types of pew pew.

**Comment by D3nnis3n** [comment]
Not fitting into what Eco is meant to do, we'll likely have other endgame content and more different disasters in the future, though.
