### ISSUE TITLE
Remove the industrial tag from wooden elevator call post.

### ISSUE THREAD

**Issue by Hextil** [StrangeLoopGames/EcoSuggestions#829]
Essentially just what the title says, a button to call the elevator shouldn't remove your ability to gain skill points from a room. The elevator itself makes sense as an industrial item, however, making the call post industrial just limits ways you can creatively build a house without adding any realism or fun to the game. It would be far better off as a general item providing no points or a non categorized item.

**Comment by Praefator** [comment]
Been reported as a known bug since its introduction in 8.0 - https://github.com/StrangeLoopGames/EcoIssues/issues/11320.

**Comment by D3nnis3n** [comment]
Duplicate.
