### ISSUE TITLE
Server Option to Enable/Disable Law(s), Also Ability to delete a single law (or a group of laws) rather than ALL laws

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoSuggestions#831]
Sometimes a law might be causing an issue on the Server, and as far as i know the **only** way to get rid of a law is by deleting **ALL** laws.
would be nice to have the option to Choose which laws are enabled/disabled so an Admin can find out which law is Causing the issue, and then Also having the ability to Delete a **single** law

**Comment by Conchipedia** [comment]
possible have a Tick box Option?
For enable and disable and then finally a delete Law entirely option

**Comment by D3nnis3n** [comment]
Laws can be deleted one-by-one forever in the Web UI and now you can do it via commands.
