### ISSUE TITLE
[Suggestion] More furniture/ Building appeal for Mortar line

### ISSUE THREAD

**Issue by bashemX** [StrangeLoopGames/EcoSuggestions#834]
The few furniture you get in the line are not that appealing to a lot of players. A lot don't want to use stone braziers. There should be more furniture at higher levels of the skill. Could have statues, fountains or stone tables for example. 

The early game is too dominated by hewn log and Hewing skill. I understand cutting logs is easier than working with stones but I have to make 4 mason tables just to get a decent rate going. By then the hewer already has massive fortress made out of logs and has set up a store. So what you usually see is 95-99% of houses made of hewn logs. Probably doesn't help a lot of items are made from hewn logs early on. Seems lots of people who take mortaring leave the server early.

Suggest maybe a housing skill bonus or furniture bonus when using mortared building materials.  Just some reason to use mortared things instead of hewn for buildings.

**Comment by D3nnis3n** [comment]
Hello bashemX,
thank you for your suggestion :)

In Update 9.0 we both included statues and fountains as well as high tier ashlar stone furniture. We also made stone a real alternative to hewn logs for your first house, even though the adaption of the tutorial will only follow in a future Update.

As your suggestion has been implemented, i'm closing this issue.
