### ISSUE TITLE
Remove Bison Carcass from Butchery Research

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoSuggestions#835]
Bison population is sensitive early and is vulnerable to extinction. This is realistic and adds to game value.  There is a problem that butchery research requires Bison carcass.  There is a strategy where you research butchery early and then make Bison extinct on purpose.  The person who did this then has a monopoly on both Butchery and Tailoring.

**Comment by otting** [comment]
thats only in a badly generated world, a healthy world has a population of about 40 Bison and they dont just die from hunting.

**Comment by WeaselDog** [comment]
fixed with change to bison mount starting numbers
