### ISSUE TITLE
Add bulldozer

### ISSUE THREAD

**Issue by reggiew17** [StrangeLoopGames/EcoSuggestions#837]
A bulldozer would be abler to push and or flatten land (a grader would also be an option). This would be great for farming a new cooking skills as the farms can be bigger and more elaborate and truly use the tractor equipment.

**Comment by otting** [comment]
there is a Skid Steer, case closed.

**Comment by D3nnis3n** [comment]
Hello reggiew17,
thanks for your suggestion :)

As otting mentioned, we already have the "Skid Steer" that is very capable of flattening an area. We don't think that another vehicle serving the same purpose is required, hence your suggestion will unfortunately not be implemented to the game.
