### ISSUE TITLE
Ability to jump servers with % of goods

### ISSUE THREAD

**Issue by reggiew17** [StrangeLoopGames/EcoSuggestions#839]
Essentially this is like moving where a player can take a percentage of their goods to other servers. 

For example: you friend set up on a different server and you want to join but have put in a significant amount of resources into your current game. Essentially a move server would scrap you current setup (including anything built on your land claims) and deliver it via an air drop once you set up camp on a new server. The penelty is that resources would be greatly reduced (by %) to allow continuation of the game without feeling the complete loss from a server jump.

This will do 2 things:
1. create a compelling reason for others to join servers and support the government and friends while also bringing the resources necessary to get established and help others.
2. Reduce player drop off when a server gets shuttered. Currently I have had three mid game server shut downs that cause me to start over. Even just a small supplies boost would have made the grind better and more tolerable.

**Comment by otting** [comment]
exactly how do you think that would work out with fresh day 1 servers? it makes no sense to me.

You could ask the admin of the server to provide some resources to everyone to make up for the loss.

**Comment by D3nnis3n** [comment]
If at all, only with a disable setting on default. Servers are new civilisations and bringing stuff over is not really the Eco-Way.

**Comment by Conchipedia** [comment]
and someone may have been banned from a server for spamming, no need to reward them for being nasty by joining another server and giving them stuff

**Comment by D3nnis3n** [comment]
Hello reggiew17,
thank you for your suggestion.

Unfortunately your suggestion will not be implemented to Eco. While i see the reasons for your suggestion, we think that taking resources from one to a different server is a major problem for game balance and unfair to all those players that start out freshly on a new server.

I'm therefore closing this issue.
