### ISSUE TITLE
Configurable Vivox proximity filter

### ISSUE THREAD

**Issue by mattkennedynz** [StrangeLoopGames/EcoSuggestions#850]
Hey all, I really dig the Vivox proximity filter concept. However on small/sparse servers it gets lonely after about 20 blocks of separation between players. 

Perhaps this proximity distance could be configurable per player? We've ended up reverting to Discord voice chat to talk over long distances, but it would be cool to use Vivox instead (the 3D sound effect is _very_ cool).

**Comment by redwyre** [comment]
Already planned https://github.com/StrangeLoopGames/EcoIssues/issues/12583
Watch that issue for updates
