### ISSUE TITLE
Colorblind

### ISSUE THREAD

**Issue by antsustr** [StrangeLoopGames/EcoSuggestions#851]
Hi,
As colorblind I would appreciatecolorblind mode, like I know the yellow/green thing when mining only because co-player mentioned that :)

**Comment by otting** [comment]
yeah i didn't it first either... its not the most dramatic thing but it would make life a little easier

**Comment by Conchipedia** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/2082

**Comment by D3nnis3n** [comment]
Hello antsustr,
as there is already an issue created for this suggestion at our bug tracker, i'm closing this suggestion. Issues generally have a higher priority than suggestions.
