### ISSUE TITLE
Suggestion: Configuration for turning voting announcements on\off

### ISSUE THREAD

**Issue by ThorVonAwesome** [StrangeLoopGames/EcoSuggestions#855]
Howdy All!

An issue that popped up on my server, which allows random persons to join, in which cyber-bulling has transpired due to the voting system. Of course those that were involved in the bullying were banned from the server, however it occurred to me that, currently, the system announces when someone voted, who it was that voted, and what they voted. 

Since anonymity is an incredibly important part of a democratically elected body, I thought it might be nice if there was an option to disable the server announcements, either fully or in part. By in part, I simply mean removing the name of the person who voted. Therefore, players could still track the number of votes cast and how they were cast to ensure that there is no voter fraud going on. In addition, players would be allowed to vote how they wanted to, even if it was against their friends, without fear of molestation by those who did not vote along the same lines as they did. 

Just a thought on how to enhance the voting system to mirror a real life implementation of a democratic process. 

Thanks,
ThorVonAwesome

**Comment by D3nnis3n** [comment]
Anonymous Votes are in 9.0.
