### ISSUE TITLE
Calorie Reduction for Road Tool with Basic Engineering

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoSuggestions#856]
Since the calorie reduction from Self-Improvement was removed, the calorie use of the Road Tool is very noticeable.  This is a good thing except for Basic Engineers who want to spend their time building roads. They will constantly run out of calories as they work, like cutting trees without logging.

A way to make Basic Engineer early game more fun is to give them a calorie reduction for using the Road Tool. Engineers are not designed to be a resource gatherer and many players pick Basic Engineer because they want to be an early roadbuilder, so this helps them fulfill that purpose.

**Comment by elfl0rd** [comment]
planned in 0.9 afaik
