### ISSUE TITLE
Maximum sleep time during a single session

### ISSUE THREAD

**Issue by BozoJim** [StrangeLoopGames/EcoSuggestions#857]
I'm requesting a maximum sleep timer during a single sleeping session. The goal being that if you go to sleep but either can't get out of bed for some reason you step away, your character doesn't accidently sleep for 30 days.
I'd like something between true and false. You can sleep, but you can't unintentionally break the save due to forgetfulness, misunderstanding, or a glitch.

**Comment by johnkslg** [comment]
Good idea. But someone may want to sleep for 30 days
**
![image](https://user-images.githubusercontent.com/3536496/60999265-9324a500-a30f-11e9-9c99-94a1b3d165f0.png)
**

**Comment by BozoJim** [comment]
Hypothetically, a friend could put his character asleep, then fall asleep himself and waste 50 days of your 90 day game. Purely hypothetical.
