### ISSUE TITLE
[0.8.2.4+] Food Crops Maximum Yield Too High

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoSuggestions#858]
Since patch 8.2.4, the maximum yield for all of the food crops was increased. In many cases it was increased by 100%. Previously it was already too easy for farmers to overproduce food. Now it is even easier to overproduce because farmers are twice as productive. I suggest to change back to the 0.8.2.3 numbers. 

The following table compares all the yields. Keep in mind all the maximum yields are doubled with Gathering, so Huckleberries can give 16 now and Rice can give 18. Most of the yields with gathering went from single digit to double digits. I will bold some that have huge impact on how farming economy works.

| **Plant** | **0.8.2.3** | **0.8.2.7** |
| --- | --- | ---|
| Agave | 4 | 6 |
| **Beans** | 3 | 6 |
| **Beets** | 3 | 6 |
| BoleteMushroom | 3 | 6 |
| Camas | 3 | 6 |
| CookeinaMushroom | 2 | 4 |
| **Corn** | 3 | 6 |
| CriminiMushroom | 3 | 6 |
| Fern | 4 | 6 |
| Fireweed | 3 | 5 |
| **Huckleberry**| 4 | 8 |
| **Papaya** | 4 | 6 |
| Pineapple | 1 | 3 |
| PricklyPear | 2 | 4 |
| Pumpkin | 2 | 4 |
| **Rice** | 5 | 9 |
| Taro | 3 | 4 |
| **Tomatoes** | 3 | 5 |
| Urchin | 2 | 3 |
| **Wheat** | 3 | 6 |

**Comment by trevelmike** [comment]
While they may be high with the way calories work these days, it's appreciated that you can get more.
