### ISSUE TITLE
Allow server-customizable tutorial

### ISSUE THREAD

**Issue by Praefator** [StrangeLoopGames/EcoSuggestions#859]
As per the title:

In my months of being a server admin, I've noticed that while the tutorial covers the basics well, on a multiplayer server it does come with its caveats, especially given a highly collaborative server. 

For instance, the tutorial as-is will direct people to the nearest raw food source, show how to build hewn logs from a workbench and so on. Useful skills when considering a **singleplayer** context, where you need to do **everything yourself**. Enter a high collab server with several specialists available at any given time, who can process raw materials into their respective processed material at a much higher efficiency, thus giving a player much more bang for their buck (provided the economy is set up for such a scenario, but for sake of the argument I'm assuming my own server's setting where such an economy is present for the entire map's duration). 

Since such a highly collaborative server comes with its own way of doing things, like the following, I would suggest being able to define parameters explaining the server's 101, like:
- Where to chop trees and where to sell them
- Where to gather stone/ores (public mine) and where to sell them
- Where to buy food
- Where to get cheap building materials for a house of their own
- Where to get vehicles and tools

Of course, this would cost time both in terms of development and server admin/staff time, however it would give people incentive to run through the tutorial at least once to give players a general idea of what to expect on a given server, and thus provide a more informed decision on whether the server they connected to is something they want to join.

**Comment by D3nnis3n** [comment]
This is possible via the Ecopedia system now, you can create your own categories, subcategories and pages to explain how stuff works on your server. It's not like the popup of the actual game tutorial, but this is intended as that tutorial will be changed to only pop up a single time per player in the future and is intended to be separate. The only popup remaining will probably be the discord one that will be deattached from the tutorial.
