### ISSUE TITLE
World Gen

### ISSUE THREAD

**Issue by trevelmike** [StrangeLoopGames/EcoSuggestions#860]
So long story short way back in .8.0 i think when the new world gen hit, the world that was created was one big landmass and on tiny island. I had no problems with it. Somewhere between then and now world gen got changed so for the last few new worlds they all had to large islands and one small one. I don't know if its related to no collaboration or something else. It seems not random anymore. 

The main issue and my issue with this is with the size of these islands, it puts a strain on resources. This world doesn't have old growth redwood. That will hurt later on. Other tree like oak and redwood have very little room since its an island as well. My desert biome is a small island and i know its too small to contain the pollution it will create eventually. 

SLG took part in a discussion on the steam about boats and he also does not like these big oceans. It would be better off if it was a lake or river. These islands need to go either way.

**Comment by D3nnis3n** [comment]
You can configure that freely in WorldGenerator.eco.
