### ISSUE TITLE
Objectives message abuse

### ISSUE THREAD

**Issue by Yorkforce** [StrangeLoopGames/EcoSuggestions#864]
Currently players can set a malicious message as thier objective and there is no way for an admin to remove or reset it.

I would like to suggest a new command to reset/delete another players objective as its wide open to abuse such as racism or personal attacks.

**Comment by Deantwo** [comment]
More chat commands? It would be soo much better with actual buttons on the objective window.
But I guess it would take time to add an "admin control panel" for each window.

**Comment by WeaselDog** [comment]
There will be more chat commands coming. I wonder if the commands related to reputation and objectives should be under the user "Manage" section instead of the "Civics" section.
