### ISSUE TITLE
Admin Alert ( for not chat readers )

### ISSUE THREAD

**Issue by meXc** [StrangeLoopGames/EcoSuggestions#867]
Sometimes admins need to give an alert (  for example if some minutes would get lost in a restart, so everyone knows to stop, even when not reading the chat. 
An Alert Message in the middle of the screen ( other games do the same) either in an extra window or just as Text on Screen would be helpful.

**Comment by D3nnis3n** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/9219
