### ISSUE TITLE
Show player in what room he is 

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoSuggestions#869]
copied from https://github.com/StrangeLoopGames/EcoIssues/issues/7310
"And the room panel down the bottom left needs to tell you what room type you're in."
At that moment this panel moved to right.
![image](https://user-images.githubusercontent.com/45708377/62541430-6d34e680-b862-11e9-9bf2-6f3e6c40b296.png)

**Comment by ThePiachu** [comment]
The tooltip should also include the decor value of the room. Very useful for building a house and capitol!

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/197704716-60bdfee1-e767-4ba3-9c4f-e6dab98db1a7.png)
