### ISSUE TITLE
Some sickness/Bacteria suggestions

### ISSUE THREAD

**Issue by Holypeanut187** [StrangeLoopGames/EcoSuggestions#875]
I had an idea earlier today that you may like, I don't have the game yet so I'm not sure what all has been added or taken out, I was thinking there should be a sickness system and with sciences there should be bacteria that you can discover and find other bacteria that kills that certain one and mix them up and have stuff like custom player made Vaccines, Medicines, and other antibiotic stuff. It would also be neat if there was a way that certain bacteria linger and can cause others to be sick and therefore can't work (Some cool sickness effects would be like, More calorie usage, cannot work, and slowed movement). So to get rid of lingering bacteria it would be neat if you could make cleaning sprays that only have ingredients that players mix in with healthy bacteria that they discovered. Early game medicines could be some herbs mixed in a wooden bowl so that players can actually start the game.
With this should come a new skill to start researching the bacteria called something like Biology or Chemistry.

**Comment by p0p-3y3** [comment]
early game herbal remedies could be based on cooking to create the broths/pastes for healing

**Comment by Holypeanut187** [comment]
After a few generations of a certain bacteria being killed by the same bacterial mix, it should have a 10% chance to go immune to one of the bacteria in the mix.

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoSuggestions/issues/1567
