### ISSUE TITLE
Ability to freeze the top row of Storage window

### ISSUE THREAD

**Issue by Rumpelstiltskinny** [StrangeLoopGames/EcoSuggestions#879]
With many storages in close proximity, the storage window entries grow quite long. The ability to freeze the currently viewed storage, akin to MS Excel, would enable efficient manipulation of itemstacks. Perhaps a checkbox to pin the top entry?

**Comment by D3nnis3n** [comment]
That's actually a bug: https://github.com/StrangeLoopGames/EcoIssues/issues/12037
