### ISSUE TITLE
Add server options for ore abundance

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoSuggestions#884]
Mining for ore on a low-pop server / single player is probably the biggest grind in the game, even with a Skeet and an Excavator. It would be nice if servers could easily alter their ore abundance during generation. This would make the game more accessible to people that want to have an easier time with the game while also exacerbating the environmental issues - 10x more ore means 10x more pollution and tailings after all!

**Comment by WeaselDog** [comment]
This option exists in the WorldGenerator.eco config file

**Comment by D3nnis3n** [comment]
Closing, as this setting exists.
