### ISSUE TITLE
Server global production output multiplier setting

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoSuggestions#885]
Some people like to have an easy time with the game and don't have the time to grind all day long. It would be nice if servers / single player worlds had an option for simply scaling the global output of stuff produced to help address the issue.

You could set it between 1 (default) to something like 10, and all it would simply do is multiply outputs of all basic crafting by that multiplier. This option would only apply to "basic items", mostly things used in construction of other things and food, but not end products like vehicles, tools, etc (nobody needs 10 axes while playing singleplayer, but 10 iron ingots would be welcome).

You'd similarly multiply the amount of pollution and (possibly) tailings produced to balance the game that way.

**Comment by WeaselDog** [comment]
Servers have the option to edit these choices on an item-by-item basis. It would be hard for server owners to agree what qualifies as a "basic item" and it would be better to leave it up to the individual servers.

**Comment by D3nnis3n** [comment]
9.0 has the opposite thing - a resource consumption and crafting time multiplier, that basically does the same thing.
