### ISSUE TITLE
Low tech charcoal mounds

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoSuggestions#886]
Currently, you can only make charcoal in blast furnaces, a mid/high-end production building. However, in real life, [you can make charcoal](https://www.youtube.com/watch?v=GzLvqCTvOQY) in really low tech ways using earth mounds. It might be interesting to let players make charcoal like that (at a very slow rate perhaps) using a low tech building made out of say, clay or dirt. This would let them essentially concentrate their fuel from logs to charcoal by spending some fuel and creating some pollution.

**Comment by D3nnis3n** [comment]
Charcoal is now made with Hewn Logs in a Kiln, therefore closing this.
