### ISSUE TITLE
Suggested Experience Values for Mechanics Vehicles

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoSuggestions#889]
I looked at the data below and based on my playtime as Mechanics I have suggested values for the Mechanics vehicles:

- Steam Truck - 25 EXP
- Wooden Elevator - 10 EXP 

Both currently have no assigned experience value as mentioned in https://github.com/StrangeLoopGames/EcoIssues/issues/12865

**Mechanics Experience Data**

- Machinist Tables - 5 EXP
- Lathe - 20 EXP
- Assembly Line - 40 EXP
- Steam Engine - 25 EXP
- Portable Steam Engine - 10 EXP
- Boiler - 3 EXP
- Gearbox - 2 EXP
- Most intermediate goods - 1 EXP

**Comment by D3nnis3n** [comment]
Moved to the issue.
