### ISSUE TITLE
GRAPHIC ISSUE: Wall elements displayed in wrong direction

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#89]
_From @Nicolausi113 on April 28, 2018 23:19_

(v0.7.3.3 also 0.7.2.5) Possibly all wall-elements (bricks, stone, logs) are displayed in a wrong direction if they are inserted in a north-south-wall with gaps between. If windows or doors (or even blocks) are inserted, the texture turns in the right direction. Fancy things happen when a door is opened, the wall opens also :)

![eco wrong elemnts](https://user-images.githubusercontent.com/38510829/39401664-df732418-4b4a-11e8-98be-ce3dc5c54b36.jpg)

Attachment and Suggestion: wouldn't it be best to use the direction keys for such elements, it would clear the code?

_Copied from original issue: StrangeLoopGames/EcoIssues#7478_

**Comment by Nicolausi113** [comment]
Initially I opened this as an issue as the title says and somehow muted it to a suggestion, maybe because there is a suggestion included. What shell happen now? Shell I copy it back?

**Comment by BlazeGuy2** [comment]
I was using a tool to bump over the issues tagged as suggestions, I'll move this one back to the bug area.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoIssues#7939
