### ISSUE TITLE
Reduce Energy Consumption of Indoor Lighting

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoSuggestions#898]
**Suggestion based on idea of Seraphine Hunt on Discord:**
Reduce the energy use of indoor lights to 60W or 40W. I suggest 40W which is the wattage of the incandescent bulbs in my home.

Almost everyone would like to see electric lights used more. Previous discussion was focused on how to make lights more useful, but the problem could just be they use too much electricity to viable.

**Looking at the numbers:**
Right now, wall lamps use 100W. Floor, ceiling, and table lamps each use 250W. An Electric Machinist Table also uses 250W. 

A Steam Engine produces 1000W which only powers 4 Floor Lamps. Burning logs in a Stone Brazier a more efficient method of household lighting if we need a Steam Engine for each 4 lights.

If indoor lamps only use 40W, this means a Steam Engine will power 25 lights. This seems like a much more reasonable number. If they use 60W it will power 16 lights which is still better than the current situation.

**Comment by D3nnis3n** [comment]
Implemented in 9.0
