### ISSUE TITLE
Issue management: give typos their own label in EcoIssues repository

### ISSUE THREAD

**Issue by LWChris** [StrangeLoopGames/EcoSuggestions#899]
Over in EcoIssues, don't label typos with "Low Priority", give them their own "Typo" label. A distinct label has three advantages:

1. It makes filtering for these issues a lot easier when reporting
2. Implies "Low Priority" but also "Easy to fix"
3. Allows you to fix all such "Typo" issues in one go as last commit of any milestone, because typos should be a thing of 1-2 minutes per issue and are easier fixed in a bulk commit that changes the resource file once.

**Comment by D3nnis3n** [comment]
Typo strings should be marked with "Localization" on top of the priority. A combination of Localization and Low Priority implies a Typo automatically. All Localization issues are dealt with by the same person and all of them are made in one go, so this should not be needed when the labels are used correctly.
