### ISSUE TITLE
Undesired Result when Proposing Multiple Districts

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoSuggestions#9]
I looked through the bugs and could not find this one, so sorry if i missed it.

When proposing a district, while another proposal for a district is currently in a voting state, the second district proposal, will overwrite the first district proposal.

Example
Player 1 proposes District A
Player 2 proposes District B within the 24 hr voting period of District A.

If District A passes, the District will get created, then when District B passes after it, District A will be deleted since it was not on the original proposal for District B, since it had not passed at the time of the creation of District B's proposal

Suggested Solutions
Limit the number of Active District Proposals (not desired)
When a District passes, automatically amend the active proposals to include that district
(I understand that this may be troublesome if two district requests happen for the same area of land, not sure what to do about that scenario)
show, and restrict District adjustment of an area that is currently being proposed when creating a new proposal.
Different interface for creating districts as opposed to laws. ¯\_(ツ)_/¯

**Comment by D3nnis3n** [comment]
This is implemented in Update 9.0 where Districts can be proposed one-by-one and will not overwrite other proposed districts due to the use of district maps.
