### ISSUE TITLE
Gray out unusable talents 

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoSuggestions#905]
There is a known issue that some of the talents are not implemented yet. To avoid frustration in the short term for newer players, I suggest to have the following talents grayed out and impossible to pick. I did not include talents where neither choice is implemented.

Here is a list of the talents that should be grayed out sorted by specialization:

- Bricklaying - Frugal Workspace
- Glassworking - Frugal Workspace
- Farming - Frugal Workspace
- Paper Milling - Frugal Workspace

- Hunting - Fisherman, Aggressive Angler
- Logging - Tool Strength, Loggers Luck
- Gathering - Tool Strength

**Comment by WeaselDog** [comment]
@Sekor2600 Has a better idea:
Instead of gray out the symbols just write text for the talent descriptions that they do not function.

**Comment by D3nnis3n** [comment]
Descriptions were changed to note WIP status.
