### ISSUE TITLE
[ISSUE] Can't get non-carriable items clicking a storage

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#92]
_From @matias-b on April 27, 2018 17:0_

**Version:** 0.7.4.0 beta staging-68e3874b (happens in 0.7.3.3 too)

**Steps to Reproduce:**
Click any storage with items

**Expected behavior:**
Get some non carriable item, like clicking a stockpile

**Actual behavior:**
Only get carriable items and not other non-carriable items

_Copied from original issue: StrangeLoopGames/EcoIssues#7461_

**Comment by BlazeGuy2** [comment]
_From @metachronism on April 27, 2018 20:51_

pretty sure this is working as intended

**Comment by elfl0rd** [comment]
@D3nnis3n realized. (Quadbro inventory changes) out in 0.8.0
