### ISSUE TITLE
Loss of Data

### ISSUE THREAD

**Issue by CarlB258** [StrangeLoopGames/EcoSuggestions#922]
Version: 0.8.3.0 beta

Steps to Reproduce:
Create any item and customise it e.g. name it, link inventories etc.

Expected behavior:
Items should retain their customisation when being moved with the Hammer

Actual behavior:
All customisation of item is lost

Do you have mods installed? Does issue happen when no mods are installed?:
No mods installed

**Comment by D3nnis3n** [comment]
Duplicate of an issue.
