### ISSUE TITLE
Powered Cart rebalance \ return to game.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoSuggestions#924]
In current state, powered cart is useless :(
At the technical level where it will be available to you (internal combustion engine) you really choose the truck.
I think that the recipe does not require mechanics workbench (only the work of a blacksmith, and basic engineer and ofc, not combustion engine - something like "low-power steam engine") would be very good to fill the gap between the carts and a steam truck.

Current state
wheelbarrow+small wood cart
-steam truck
--truck+powered cart

Wanted state
wheelbarrow+small wood cart(no profession)
-powered cart(blacksmith+basic engineer)
--steam truck(mechanics)
---truck(industry)

p.s.
Why am I against removing the powered cart from the game.
1) we have too big gap between big carts and steam truck (well seriously, you can make metal, brick and glass things, in 0.8 at this stage you already need big transports, but you're still hauling carts.)
2) I love powered cart model, and browse from the driver's seat

**Comment by elfl0rd** [comment]
> Players just don't like it.

you can't say that without trying.)
The change I have proposed does not require any serious work, "animal husbandry" appear after looooong time.

**Comment by SlayksWood** [comment]
Nothing will save Powered Cart. In any case, its rebalancing will change its model.
It would be nice for me to have a cargo bike like:
![image](https://user-images.githubusercontent.com/45708377/68579499-50253a80-0485-11ea-99bc-d0207c9df99b.png)
It should move a little faster and have more max weight than Wood Cart.
Also can add bike for faster moving without item transpartation.

**Comment by elfl0rd** [comment]
> a cargo bike like:

Aaand you got same control issues.

**Comment by D3nnis3n** [comment]
"you can't say that without trying :)"

They didn't like it when it was the only option, what do you think the reason for a steam truck was? *g*

There is no way we would implement a re-balance of the cart any time soon, so the fear of animal husbandry being to far away is negligable. The cart wouldn't come back in the design it is now. In general i feel the best compromise is to actually have animal-powered options with husbandry.

**Comment by D3nnis3n** [comment]
^

**Comment by SlayksWood** [comment]
@D3nnis3n 
turning around a tricycle (if it is correctly designed) is much easier than turning around cart with horses or other animals.There was a lot of experience in this in my childhood with horse cart.

**Comment by D3nnis3n** [comment]
May very well depend on your skills. It looks very easy here on the countryside, it obviously isn't, but what they can do is having a short radius when going to the right or left. The tricycle in Eco didn't manage that, due to technical reasons in how it's build, not skill.

**Comment by elfl0rd** [comment]
Fine in 0.9
