### ISSUE TITLE
Mom I don't want to eat Beans! I want my XP!

### ISSUE THREAD

**Issue by TheOvermind** [StrangeLoopGames/EcoSuggestions#926]
Don't you hate when you're trying to plant Beans/Camas/Rice and you eat them?
Well, these doesn't happens with seeds (And yet, you can eat them too). 

So, how about these crops are treated like seeds?
You shouldn't be able to eat them with right click while in your hotbar.

**Comment by D3nnis3n** [comment]
That's intended, as there the food item itself is a seed. (But people may want to eat the food, as it is food with values!) We've already made it so that when you actively try to plant them, you can't eat them. If that doesn't work you can open a bug report.
