### ISSUE TITLE
Statue-Making Skill

### ISSUE THREAD

**Issue by Crack-Attack** [StrangeLoopGames/EcoSuggestions#929]
A skill which adds the ability to make statues, such as this modded lion statue. (not sure what the mod is, found the picture on the screenshot channel on the Eco discord.)
![image](https://user-images.githubusercontent.com/41523253/68437235-62a22a00-018e-11ea-8487-e546825eb052.png)

**Comment by D3nnis3n** [comment]
Hello Crack-Attack,
thanks for your suggestion, we really appreciate it.

We introduced statues with Update 9.0, but they are made by already existing professions to boost them. A profession only for statues seemed a bit too much.

I'm therefore closing this suggestion.
