### ISSUE TITLE
Add server rules function

### ISSUE THREAD

**Issue by msgerbs** [StrangeLoopGames/EcoSuggestions#952]
Currently, servers generally have signs at spawn which list the rules. This works okay, but it would be nice to have a "rules" setting for servers which could be seen from the server list.

**Comment by D3nnis3n** [comment]
Server Rules can be added via Ecopedia in Update 9.0 or you can use one of the plenty mods that implement such a feature, there won't be a specific feature just for the rules from our side, though.
