### ISSUE TITLE
UI skill book

### ISSUE THREAD

**Issue by Astrija** [StrangeLoopGames/EcoSuggestions#959]
I would like to offer several options for changing skills books. It may seem inconvenient to you, but this is only a proposal to increase the amount of information per unit screen area.
Figure 1. Changes.
![unknown3](https://user-images.githubusercontent.com/13696708/74675670-1327bd00-51c5-11ea-91b9-f8d44396aa56.png)

Figure 2. The result of the change.
![unknown2](https://user-images.githubusercontent.com/13696708/74675637-fe4b2980-51c4-11ea-9a56-d6795b6e8f45.png)

Figure 3. More compacted changes.
![unknown1](https://user-images.githubusercontent.com/13696708/74675641-00ad8380-51c5-11ea-9ae7-692614b6b9f8.png)

**Comment by D3nnis3n** [comment]
The Skill UI has changed since this suggestion was opened, hence i'm closing it.
