### ISSUE TITLE
Server Java-Edition

### ISSUE THREAD

**Issue by BlackRose01** [StrangeLoopGames/EcoSuggestions#961]
Hey there,

ist es geplant, dass der Server in Java implementiert wird? Ich habe das Problem, dass ich gerne einen eigenen Eco-Server betreiben möchte aber ich auf diesem kein Mono zum Laufen bekomme. Auch falls ein Plugin-System geplant ist wäre dies zum Vorteil, da viele Modder konformer mit Java durch Minecraft sind.

**Comment by D3nnis3n** [comment]
Nein, das wird es nicht geben, der Eco Server läuft aber ab 9.0 mit .NET Core 3 nativ auf Linux.
