### ISSUE TITLE
[0.9] The last pair of mining perks are too good not to have them both...

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoSuggestions#978]
I really dig the last two perks you can get from your Mining 6 skill. The problem is, they are both really good and they would synergize so well together, but unfortunately you can't pick both of them. Unless you know you will always have a mining buddy, picking one will always make you wish you could have them both.

It would be nice if say, higher-tier mining equipment reduced the chance of creating the double rock so you could just pick the "grab all" perk, but then you'd probably want to replace the other perk with something else.

Maybe have a perk tied to the processing of ore, like Frugal? This way you could have a distinction between the mining miners and the processing miners, which might be a bit more of an interesting choice.

**Comment by D3nnis3n** [comment]
The goal of the two perks is a mining team, each of the players picks one of them and work together. Making one of the perks useless via adding the effect to tools doesn't seem like a good thing to do, tools rather will be focused on AoE, so i'm closing this suggestion for now.
