### ISSUE TITLE
Ability to offload mats directly into a stockpile

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#98]
_From @ShaydenMac on April 26, 2018 22:18_

From Youtube: https://youtu.be/cY5Y5piZm38

"please add the ablity to offload the dirt/stone directly into a stockpile, having to take it out stack by stack takes awhile and it hinders the progress you can go before having to break.﻿"

_Copied from original issue: StrangeLoopGames/EcoIssues#7443_

**Comment by BlazeGuy2** [comment]
_From @FWerewolf on April 28, 2018 14:2_

Please also skid steer unloads dirt/stone directly into the truck.

**Comment by elfl0rd** [comment]
@D3nnis3n both suggestions realised.
