### ISSUE TITLE
Allow hunting of animals on anyone's property

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoSuggestions#984]
I've played a bit as a hunter on a public server and it's always a bit infuriating when you chase a deer only for it to end up on someone's property and be immune from arrow damage. I think you should be able to hunt animals on anyone's property since:

- I don't think you can grief with it
- Animals naturally wander around, so you can't fence them in or protect them with a property (yet at least)
- I don't think people have enough property claims to make some sort of nature reserve, and even if they would, this would be better handled on a government level

**Comment by Elliander** [comment]
In Eco, do you have to clean up dead animals? I genuinely don't know as I don't hunt, but if anything is left behind where it dies that would pose a problem.

Regardless, it's not an accurate reflection of real life (.i.e. if you hunt on public land and the deer roams into my yard you have to stop shooting at it) although in that case the larger issue is stray bullets going onto private property. 

That being said, a fair compromise would be to allow you to propose an open hunting law. Just as users can propose laws to restrict hunting on public lands.

**Comment by D3nnis3n** [comment]
Update 9.0 has laws that can overwrite property permissions, so you will be able to do that via laws in the new update :)
