### ISSUE TITLE
[Server] A way to set minimum RAM to join

### ISSUE THREAD

**Issue by Elliander** [StrangeLoopGames/EcoSuggestions#999]
Running a large server of 16 square kilometers I have noticed that the RAM usage goes between 7 GB and 10 GB. For the client, it's around 7 GB to 8 GB. Players who join the world that have lots of RAM tell me there is no lag, while players who have 4 GB of RAM tell me it is very laggy.

Looking at Network tab, very little bandwidth is used and ping is relatively low, so my overall conclusion here is that some players simply cannot play in a very large world, but they think the problem is server side when it's client side.

The average person seeing this might think they need to migrate to dedicated hosting services, which for a giant world would be bad since the RAM goes above the expected amount on occasion so performance would suffer.

I put a note in the description of the server about this, but if I could set it to only allow people to join with enough RAM to actually play in the server that would be best. Alternatively, if the client could recognize how much RAM, and the world size the player is trying to join, it could give them a heads up that the server isn't suitable for their computers for such and so reason.

As it stands, the minimum requirements to play is definitely dependent on world size.

**Comment by D3nnis3n** [comment]
As we only support world sizes up to 4km² and this would be a big workaround, this is not going to happen.
